### ISSUE TITLE
LaTeX支持不好

### ISSUE THREAD

**Issue by allonli** [JaxsonWang/WP-Editor.MD#100]
同行完全不识别，![image](https://user-images.githubusercontent.com/3733955/32991891-b5e4ae40-cd7e-11e7-8256-ded58f515011.png)
$$A \times B$$会被错乱成 ![image](https://user-images.githubusercontent.com/3733955/32991894-c2c891d0-cd7e-11e7-9e89-20965c872ecf.png)

**Comment by JaxsonWang** [comment]
应该这样写：
```
$$A \\times B$$
```

请把单`\`都改成`\\`
