### ISSUE TITLE
语法高亮设置四个选项的提示都是下面的这个

### ISSUE THREAD

**Issue by hoseahsu** [JaxsonWang/WP-Editor.MD#103]
Warning: json_encode() expects exactly 1 parameter, 2 given in /home/hosealeobh6o3sfela2l7eqo/wwwroot/wp-content/plugins/WP Editor.MD/Admin/skelet/core/core-options.php on line 338

**Comment by JaxsonWang** [comment]
这个不影响，你可以把wp的debug暂时关闭。如果你的是生产环境的话。

**Comment by hoseahsu** [comment]
找到原因了，PHP版本问题
