### ISSUE TITLE
安装之后无法打开编辑器页面，显示 Fatal Error

### ISSUE THREAD

**Issue by haoxi911** [JaxsonWang/WP-Editor.MD#104]
打开了WP_DEBUG之后显示如下错误：

`
Fatal error: Cannot declare class WPCom_GHF_Markdown_Parser, because the name is already in use in /var/www/html/wp-content/plugins/jetpack/_inc/lib/markdown/gfm.php on line 0
`

看上去是和Jetpack冲突了，我用的是最新版本的Jetpack和最新版本的Wordpress。

**Comment by JaxsonWang** [comment]
本地测试没有出现你说的情况。

不过我还是把函数名修改下吧。

**Comment by JaxsonWang** [comment]
Fix https://github.com/JaxsonWang/WP-Editor.MD/commit/b64feadd55df68c0e9d33b2fcdce90d430eb9cc5
