### ISSUE TITLE
something wrong with '_'

### ISSUE THREAD

**Issue by JoscarJiang** [JaxsonWang/WP-Editor.MD#105]
example like $$f(x) = \\int_{-\\infty}^\\infty\\hat f(\\xi)\,e^{2 \\pi i \\xi x}\,d\\xi$$
the body behind the _ became italic, and the formula did not work well.

**Comment by JaxsonWang** [comment]
It is recommended to write this: `$$f(x) = \\int_{-\\infty}^\\infty\\hat f(\\xi),e^{2 \\pi i \\xi x},d\\xi$$`。

Modify all slashes to double slashes

**Comment by JoscarJiang** [comment]
Oh,sorry. It was a wrong case. Actually I use double slashes. However, at last I find that's just the problem of rendering on the right frame( I don't know whether you have the problem ), the final effect is correct on the post. Thanx.
