### ISSUE TITLE
Katex 中的 \overrightarrow{n} 此类的公式是否不支持？

### ISSUE THREAD

**Issue by OscarShen** [JaxsonWang/WP-Editor.MD#106]
![image](https://user-images.githubusercontent.com/13450440/33666784-01aa9056-dad6-11e7-8922-e28029bfa958.png)
![image](https://user-images.githubusercontent.com/13450440/33666937-6e8707c2-dad6-11e7-83c4-1ccea9955e04.png)

上一个图是官方的输出，下一个图是我的定义。公式整个消失了。

**Comment by JaxsonWang** [comment]
支持，具体请看：https://github.com/JaxsonWang/WP-Editor.MD/issues/105

**Comment by OscarShen** [comment]
并不支持，我 post 之后仍然没有显示。
![image](https://user-images.githubusercontent.com/13450440/33751544-9701ff18-dc16-11e7-9920-0c8764bad62b.png)
![image](https://user-images.githubusercontent.com/13450440/33751550-a1d38ab0-dc16-11e7-82da-0d5482dc8bd1.png)

**Comment by JaxsonWang** [comment]
@OscarShen 麻烦您能把公式粘贴给我吗，我想测试下给您个结果，谢谢

**Comment by OscarShen** [comment]
$$\\displaystyle \\overrightarrow{n}={{(f_x(x_0,y_0),f_y(x_0,y_0))}\\over{\\sqrt{f_x^2(x_0,y_0) + f_y^2(x_0,y_0)}}}={\\nabla f(x_0,y_0)\\over |\\nabla f(x_0,y_0)|}$$

![image](https://user-images.githubusercontent.com/13450440/33751874-dabe1abe-dc18-11e7-800c-825e6c5659f0.png)

**Comment by JaxsonWang** [comment]
感谢回馈，结果出来了，目前的问题是katex.js版本过低。

如果你继续我给你个临时的修复方案：https://github.com/Khan/KaTeX/releases到这里去下载v0.8.3版的katex然后替换插件中`Katex`文件夹所有的文件！

![image](https://user-images.githubusercontent.com/16836692/33754175-010f3c7c-dc26-11e7-85e4-9d09409348c5.png)

还有你的写法想多行公式展示，请参考如上截图。

https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Document/latex.md

**Comment by JaxsonWang** [comment]
Fix https://github.com/JaxsonWang/WP-Editor.MD/commit/dc86eaf43066c60402279cc80185dae90dd7a12b
