### ISSUE TITLE
与WPBakery Visual Composer兼容问题

### ISSUE THREAD

**Issue by mekery** [JaxsonWang/WP-Editor.MD#107]
非常强大的Mardown编辑器，赞一个！

我使用了WPBakery Visual Composer这个插件，启用WP-Editor后，使用了Visual Composer创建的页面或文章无法保存或更新，其它普通页面、文章不受影响。

**Comment by JaxsonWang** [comment]
@mekery 您说的插件是这个吗:https://wordpress.org/plugins/wpglobus-for-wpbakery-visual-composer/

我尝试好像没什么问题，可以的话请打开wp的debug模式，把log贴上来，谢谢
