### ISSUE TITLE
能否自定义KaTeX的调用符号？

### ISSUE THREAD

**Issue by Dixeran** [JaxsonWang/WP-Editor.MD#108]
默认是$$---$$, 能不能自定义这个符号呢..

**Comment by JaxsonWang** [comment]
可以。具体请看：https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Editor.md/js/editormd.js#L3615-L3664

不过我也打算换个，主要是和代码块中`$`引起冲突

**Comment by Dixeran** [comment]
感谢 👍 。
给也想自定义的朋友：
主要修改https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Editor.md/js/editormd.js#L3615-L3634
和TeX有关的正则。
