### ISSUE TITLE
Crayon Syntax Highlighter无法显示 

### ISSUE THREAD

**Issue by xperezxin** [JaxsonWang/WP-Editor.MD#111]
①使用了WP-Editor.MD之后，Crayon Syntax Highlighter无法显示 
②请问是否可以显示正常的编辑的文本选项？有时候如果需要选择字体颜色，字体大小，都不能通过默认的编辑框去选择，而WP-Editor.MD本身又占用了编辑框，目前没有切换编辑到默认的编辑选项

**Comment by xperezxin** [comment]
建议WP-Editor.MD编辑框和默认的编辑框分开，不能直接替换掉需要的时候无法使用的情况！

**Comment by JaxsonWang** [comment]
1. 插件会改变语法块的结构，对Crayon Syntax Highlighter要求不符合，所以你二选一吧
2. 这是Markdown编辑器，和富文本不一样，如果改成你说的，那失去了Markdown文本编写的意义了
