### ISSUE TITLE
公式中的小于号失效

### ISSUE THREAD

**Issue by lcx366** [JaxsonWang/WP-Editor.MD#114]
当我在文章中插入 $$ S < 0$$ 时，不会被编译，大于号和等于号都没有问题，不知该怎么才能让它显示小于号。

**Comment by JaxsonWang** [comment]
好的 已收到

**Comment by JaxsonWang** [comment]
测试：
BUG案例展示：
![image](https://user-images.githubusercontent.com/16836692/34761432-bc3179f4-f61e-11e7-93bf-278463a42350.png)

正常案例展示：
![image](https://user-images.githubusercontent.com/16836692/34761448-dc1b3264-f61e-11e7-9760-875ba2cac289.png)

显然是或者字符类型不同导致。

定位：https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Jetpack/latex/latex.php#L22

`wp_html_split`导致此BUG核心，搜索相关的资料：https://wordpress.org/support/topic/bug-in-wp_html_split-with-unclosed-php-tag/

解决：暂无

**Comment by alpha-mind** [comment]
期待此问题能够解决，因为小于号 (<) 很常见。谢谢！

**Comment by JaxsonWang** [comment]
@lcx366 @alpha-mind 已解决[FIX](https://github.com/JaxsonWang/WP-Editor.MD/commit/8e0e0299a0e1f9bdfaa605bd086145fbffd3a324)

**Comment by JaxsonWang** [comment]
问题再次复现

**Comment by JaxsonWang** [comment]
临时解决方案：
修改`wordpress/wp-includes/formatting.php`该文件的第`651`行，该行：
```php
			.     '<'           // Find start of element.
```
修改成：
```php
			.     '<<'           // Find start of element.
```

**Comment by JaxsonWang** [comment]
FIX TO https://github.com/JaxsonWang/WP-Editor.MD/commit/0d5436d1752173d75093b734da82c460c63dd6d1

**Comment by alpha-mind** [comment]
非常感谢！现在的 WP Editor.MD 更趋完美了！ @JaxsonWang
