### ISSUE TITLE
建议wp-editor目录toc命令不区分大小写

### ISSUE THREAD

**Issue by soxo** [JaxsonWang/WP-Editor.MD#116]
建议wp-editor把那个目录toc，能支持大写toc。也就是正文输入[toc]或者[TOC]都能使用。建议不区分大小写。因为有些第三方markdown工具是用的大写TOC，这样导进wp-editor就要手动改成小写才能显示目录。谢谢。

**Comment by JaxsonWang** [comment]
安装TOC插件是不支持大写TOC的，所以这个我没办法。你可以向那个作者反馈这个问题
