### ISSUE TITLE
插入seq无法显示问题

### ISSUE THREAD

**Issue by sonymoon** [JaxsonWang/WP-Editor.MD#117]
在md编辑器中写入：
<p> ```seq
   haggd->for:tt
  ``` </p>
 
预览文章时，对应html元素的class为“line-numbers prism-highlight prettyprint”
无法渲染成正常的时序图
我使用的是3.5版本

**Comment by sonymoon** [comment]
我使用的是3.5版本

**Comment by JaxsonWang** [comment]
正确示例：

```
$seq
haggd->for:tt
$
```

文档：[时序图](https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Document/use-zh_CN.md#%E6%94%AF%E6%8C%81%E6%97%B6%E5%BA%8F%E5%9B%BE%E5%BA%8F%E5%88%97%E5%9B%BE)

**Comment by the-eric-kwok** [comment]
@JaxsonWang 文档链接挂了，可以更新一下么？

**Comment by JaxsonWang** [comment]
@the-eric-kwok 

[Markdown参考文档](https://raw.githubusercontent.com/JaxsonWang/WP-Editor.md/docs/Example/Markdown.md)
[Katex参考文档](https://raw.githubusercontent.com/JaxsonWang/WP-Editor.md/docs/Example/KaTeX.md)
[绘图参考文档](https://raw.githubusercontent.com/JaxsonWang/WP-Editor.md/docs/Example/Mermaid.md)
[思维导图参考文档](https://raw.githubusercontent.com/JaxsonWang/WP-Editor.md/docs/Example/MindMap.md)
[插件使用文档](https://raw.githubusercontent.com/JaxsonWang/WP-Editor.md/docs/zh-CN/synopsis.md)
