### ISSUE TITLE
安装wp-editor插件后写文章页面打不开，报500错误

### ISSUE THREAD

**Issue by bigbigbigbear** [JaxsonWang/WP-Editor.MD#119]
我的wordpress版本是4.9.3版本，php是7.1.4，安装wp-editor插件后写文章页面打不开，报500错误，停用插件后可以打开，不知道怎么解决

**Comment by DavadDi** [comment]
升级到3.5版本后遇到了同样的问题

**Comment by JaxsonWang** [comment]
如有安装jetpack请关闭该插件的md语法功能

**Comment by JaxsonWang** [comment]
[Fix](https://github.com/JaxsonWang/WP-Editor.MD/commit/a0c4fe4923ae34978957ab644c455bc1584ca171)
