### ISSUE TITLE
文章详细页的嵌套列表格式出错

### ISSUE THREAD

**Issue by GreatDuan** [JaxsonWang/WP-Editor.MD#121]
在编辑器预览界面是显示正确的嵌套列表，正式发布的列表显示不正确，如下：
![image](https://user-images.githubusercontent.com/20787331/36294636-0baf1f20-131d-11e8-8f7d-7655e6dd1a07.png)

**Comment by JaxsonWang** [comment]
请查看文档：https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Document/markdown.md
