### ISSUE TITLE
时序图文章页面无法查看,但编辑文章时右侧的实时预览可以看到

### ISSUE THREAD

**Issue by mooseen** [JaxsonWang/WP-Editor.MD#125]
使用WP-Editor时,在编辑文章添加时序图，右侧的实时预览可以看到时序图，但是发布文章后显示的是文字，而不是图。

**Comment by JaxsonWang** [comment]
请确保设置打开时序图支持

其次语法请看[文档](https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Document/use-zh_CN.md#%E6%94%AF%E6%8C%81%E6%97%B6%E5%BA%8F%E5%9B%BE%E5%BA%8F%E5%88%97%E5%9B%BE)
