### ISSUE TITLE
The Markdown I created under WP-Editor.MD is not displaying in the WP Job Manager Single Page.

### ISSUE THREAD

**Issue by louierosero-gss** [JaxsonWang/WP-Editor.MD#129]
### As you can see in the image below, I used the double hashtag (##) to make this paragraph into header 2 tag.

![screen shot 2018-03-21 at 15 57 12](https://user-images.githubusercontent.com/32447469/37699061-a9584d38-2d20-11e8-87ef-a25a1adba780.png)

### But when I check the page of it. This is what is look like. The double hashtag (##) is only displaying as a part of the paragraph.
![screen shot 2018-03-21 at 15 59 35](https://user-images.githubusercontent.com/32447469/37699112-e11576ba-2d20-11e8-9dc2-5ddb830ef26d.png)

### Here is the HTML Code generated when I try to Inspect Element this single page.
![screen shot 2018-03-21 at 16 01 45](https://user-images.githubusercontent.com/32447469/37699204-65342a2c-2d21-11e8-9d51-8063dc30618f.png)
#### As you can see, that double hashtag (##) is not generated into Header 2.

*Anyway, this is only not working in the Single Page of WP Job Manager.*

**Comment by JaxsonWang** [comment]
I'm sorry I don't plan to support it, mainly WP Job Manager is too complicated.
