### ISSUE TITLE
License isn't compatible with GPL-2.0 or newer versions

### ISSUE THREAD

**Issue by Gabrielchihonglee** [JaxsonWang/WP-Editor.MD#13]
According to WordPress's [Plugin Guidelines](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/), plugins must be compatible with the GNU General Public License v2, or any later version, to be hosted on WordPress.org. The license you are using is MIT which doesn't satisfy the rule.

Please note that if you are going to host it in WP in the future, thanks! :)

**Comment by JaxsonWang** [comment]
Thank you for reminding
