### ISSUE TITLE
> *的语义解析问题。

### ISSUE THREAD

**Issue by erosnick** [JaxsonWang/WP-Editor.MD#131]
![image](https://user-images.githubusercontent.com/3668972/37867462-ef1b7466-2fd3-11e8-97b9-33de21f112e7.png)
刚开始使用，遇到了如图所示的问题，反复测试都可以重现。

**Comment by erosnick** [comment]
我没有描述清楚，问题是编辑器和预览里的文字变成了斜体。

**Comment by JaxsonWang** [comment]
这个是样式，网页样式都是这样的。前端可以自己去定义。

----------
该邮件从移动设备发送



--------------原始邮件--------------
发件人："Eros "<notifications@github.com>;
发送时间：2018年3月25日(星期天) 中午12:32
收件人："JaxsonWang/WP-Editor.MD" <WP-Editor.MD@noreply.github.com>;
抄送："JaxsonWang "<wangjin@boxrom.com>;"State change "<state_change@noreply.github.com>;
主题：Re: [JaxsonWang/WP-Editor.MD] > *的语义解析问题。 (#131)
-----------------------------------

我没有描述清楚，问题是编辑器和预览里的文字变成了斜体。

**Comment by erosnick** [comment]
噢噢，了解了，感谢。
