### ISSUE TITLE
输入法不能正常呼出

### ISSUE THREAD

**Issue by vzxxbacq** [JaxsonWang/WP-Editor.md#133]
在iOS平台上无法正常的呼出输入法的输入框。
在windows上输入框也经常会飘到左上角。
切换了多种输入法，不知道有什么解决方法吗？
谢谢。

**Comment by JaxsonWang** [comment]
iOS的是什么浏览器？我的iOS11.X Safari是正常的，能弹出输入框。

最好上个截图看看~

**Comment by vzxxbacq** [comment]
抱歉没有表述清楚，是在ipad的键盘模式下无法呼出输入框。
![img_0006](https://user-images.githubusercontent.com/29952934/38025599-8283fb58-32bb-11e8-98b2-6b2fe38efbc1.png)
![img_0007](https://user-images.githubusercontent.com/29952934/38025603-851fa006-32bb-11e8-8a5e-c68c5c6c9df0.png)
如图所示，在编辑器中无法键入中文（但是标点是全角字符）
但在其他输入框中是正常的

**Comment by JaxsonWang** [comment]
emmm，我没有这样的设备，没有办法去测试。

不过移动端我建议用类似Markdown App去写文章再复制进去。

**Comment by yichengchen** [comment]
iphone上无法输入中文……
