### ISSUE TITLE
请问如何使用自己的style.css？

### ISSUE THREAD

**Issue by JadeVane** [JaxsonWang/WP-Editor.md#134]
感谢作者制作的插件，使用体验很好，目前我自己依照习惯制作了自己的style.css，此文件包含代码高亮，表格，公式等，我希望所有主题都使用我这个css，请问可以实现吗？需要修改或者替换哪些文件？

**Comment by JaxsonWang** [comment]
您可以在`wp后台-外观-自定义-额外css`添加自己所需要的样式。
