### ISSUE TITLE
预览和显示的不一致

### ISSUE THREAD

**Issue by zxy1001** [JaxsonWang/WP-Editor.md#135]
预览非常漂亮，但是在博客中显示的时候样式不一致，是否要修改主题的css来适配？

**Comment by JaxsonWang** [comment]
预览不一致可能是主题的样式不完善，需要自己添加对应的样式~

**Comment by zxy1001** [comment]
可以从插件中提取样式替换吗？非常喜欢预览时的样式

**Comment by JaxsonWang** [comment]
这个可以的，但不是每个主题的css id class都一样，你可以自己提取editormd.css添加样式。
