### ISSUE TITLE
HelpGuru主题中markdown未生效

### ISSUE THREAD

**Issue by Ctyr** [JaxsonWang/WP-Editor.md#139]
你好，

我在默认主题下测试正常。但是切换到HelpGuru主题下，用markdown语法写文章时，点预览是正确渲染的，但是保存了之后，再打开页面，显示的又是raw markdown页面，请问这个是什么原因，我需要再提供给你哪些信息？

**Comment by JaxsonWang** [comment]
你这个有点麻烦，主题特定的函数导致渲染失效。

如果需要的请加群帮你搞一下。

QQ群号：246727127
