### ISSUE TITLE
WP-Edit和Wordfence Security的兼容性问题

### ISSUE THREAD

**Issue by codeBooks** [JaxsonWang/WP-Editor.md#140]
WP-Edit版本5.0
Wordfence Security版本7.1.3

在启用WP-Edit以后,在Wordfence Security的ALL Options中的最后一个配置选项里,报错:
`Fatal error: Uncaught Error: Cannot access protected property App\WPMarkdownParser::$contain_span_tags_re in C:\AppServ\www\wordpress\wp-content\plugins\wp-editormd\src\App\WPComMarkdown.php:429 Stack trace: #0 C:\AppServ\www\wordpress\wp-includes\class-wp-hook.php(286): App\WPComMarkdown->wp_kses_allowed_html(Array, 'post') #1 C:\AppServ\www\wordpress\wp-includes\plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 C:\AppServ\www\wordpress\wp-includes\kses.php(641): apply_filters('wp_kses_allowed...', Array, 'post') #3 C:\AppServ\www\wordpress\wp-includes\kses.php(790): wp_kses_allowed_html('post') #4 C:\AppServ\www\wordpress\wp-includes\kses.php(737): wp_kses_split2('<strong>', 'post', Array) #5 [internal function]: _wp_kses_split_callback(Array) #6 C:\AppServ\www\wordpress\wp-includes\kses.php(721): preg_replace_callback('%(<!--.*?(-->|$...', '_wp_kses_split_...', '<strong>Hold an...') #7 C:\AppServ\www\wordpress\wp-includes\kses.php(532): wp_kses_split('<strong>Hold an...', 'post', Array) #8 C:\AppServ\www\wordpre in C:\AppServ\www\wordpress\wp-content\plugins\wp-editormd\src\App\WPComMarkdown.php on line 429`

**Comment by JaxsonWang** [comment]
好 晚上有空我看看。

**Comment by codeBooks** [comment]
好的 谢谢!

**Comment by JaxsonWang** [comment]
Fix https://github.com/JaxsonWang/WP-Editor.md/commit/db31b5ca985d0d4243ba1ad1df5105ce3382c941

V5.0.1推送了
