### ISSUE TITLE
升级5.0后突然网站站点无法访问

### ISSUE THREAD

**Issue by xieisabug** [JaxsonWang/WP-Editor.md#142]
在之前4.1版本的时候是没有问题的，可是升级了5.0之后，后台还是可以进入，没有问题，站点就进不去了，报了500错误

**Comment by xieisabug** [comment]
我直接开了debug，错误是下面的
Fatal error: Cannot access protected property App\WPMarkdownParser::$contain_span_tags_re in /var/www/html/wp-content/plugins/wp-editormd/src/App/WPComMarkdown.php on line 429

**Comment by JaxsonWang** [comment]
好，感谢反馈，我会尽快做兼容

**Comment by JaxsonWang** [comment]
Fix https://github.com/JaxsonWang/WP-Editor.md/commit/db31b5ca985d0d4243ba1ad1df5105ce3382c941

V5.0.1推送了
