### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WP-Editor.md#143]
If you have any questions, please join Telegram instructions:https://t.me/wpeditormd

**Comment by qbass** [comment]
Hey Jaxson, that link leads to a server error 500, but [https://t.me/wpeditor.md](https://t.me/wpeditor.md) seems to work. Is this your correct address?

**Comment by erickwoc** [comment]
![image](https://user-images.githubusercontent.com/16463312/39402492-5a40a984-4b93-11e8-9681-9bba1fd983d4.png)
![image](https://user-images.githubusercontent.com/16463312/39402497-7545031a-4b93-11e8-9dca-2b54c3cb2c26.png)
Seems the link doesn't work.

**Comment by JaxsonWang** [comment]
oh it is https://t.me/wpeditormd

----------
该邮件从移动设备发送



--------------原始邮件--------------
发件人："EricKwok "<notifications@github.com>;
发送时间：2018年4月29日(星期天) 上午9:56
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："淮城一只猫 "<wangjin@boxrom.com>;"Author "<author@noreply.github.com>;
主题：Re: [JaxsonWang/WP-Editor.md] Notice (#143)
-----------------------------------


 
 Seems the link doesn't work.

**Comment by JaxsonWang** [comment]
@qbass @erickwoc Sorry, "t.me" seems unable to access.
![image](https://user-images.githubusercontent.com/16836692/39402561-f02ca01e-4b94-11e8-9c89-2f68fc140b0a.png)

You can search for "wpeditormd" group name, thank you
