### ISSUE TITLE
以#号开头的代码块渲染错误

### ISSUE THREAD

**Issue by erickwoc** [JaxsonWang/WP-Editor.md#144]
这是markdown写的代码块
![_ _20180429095126](https://user-images.githubusercontent.com/16463312/39402511-b3dad082-4b93-11e8-8bed-2c09ec3f9e3e.png)

这是渲染出来的效果
![image](https://user-images.githubusercontent.com/16463312/39402527-16353330-4b94-11e8-8f61-1470e8f40735.png)

看起来好像和#号有关，其他的代码块没有这个问题
![image](https://user-images.githubusercontent.com/16463312/39402555-d5e4879e-4b94-11e8-8025-4a8fe2d4a883.png)
![image](https://user-images.githubusercontent.com/16463312/39402557-e04ac252-4b94-11e8-9e5a-8d40dd2f2865.png)

做了个小测试，基本确定与#号有关
![image](https://user-images.githubusercontent.com/16463312/39402546-acb02752-4b94-11e8-8130-80a99874ddb1.png)

![image](https://user-images.githubusercontent.com/16463312/39402539-82fde070-4b94-11e8-8fd1-81059fd5d233.png)

**Comment by JaxsonWang** [comment]
测试下的确有这个问题。下个版本修复~谢谢反馈

**Comment by JaxsonWang** [comment]
Fix https://github.com/JaxsonWang/WP-Editor.md/commit/c25cf72dffd6856e85541783b398172636107e17
