### ISSUE TITLE
5.0.3 有异常

### ISSUE THREAD

**Issue by gaga-change** [JaxsonWang/WP-Editor.md#147]
![image](https://user-images.githubusercontent.com/21301350/39502982-cb6f6fa0-4df5-11e8-815d-fe8e066827a5.png)

**Comment by JaxsonWang** [comment]
应该是没有初始化变量导致的，你直接点击保存就行。

至于警告这里我可以做个判断。

**Comment by gaga-change** [comment]
就是`Query Monitor`这个插件提示的这个异常，就过来issues一下。还有`WP Rollback`好像不支持回退`WP Editor.md`的版本。

**Comment by JaxsonWang** [comment]
是的 我没有在WP SVN存放历史版本，主要文件太多拉取费时间。

如果想退回老版本你可以加群，群共享有历史版本。

**Comment by gaga-change** [comment]
ok
