### ISSUE TITLE
Warning??

### ISSUE THREAD

**Issue by darkknightzero** [JaxsonWang/WP-Editor.md#148]
```php
Warning: 
require_once(/home/www/htdocs/wp-content/plugins/WP-Editor.md-master/vendor
/autoload.php): failed to open stream: No such file or directory in /home/www/htdocs/wp-content
/plugins/WP-Editor.md-master/wp-editormd.php on line 27
 Fatal error: require_once(): Failed opening required '/home/www/htdocs/wp-content/plugins/WP-Editor.md-master/vendor/autoload.php' 
(include_path='.:') in /home/www/htdocs/wp-content/plugins/WP-Editor.md-master/wp-editormd.php
 on line 27 
```
I find sth. wrong in this plugin . So how to solve this problem?
WP - Version 4.94

**Comment by JaxsonWang** [comment]
Please do not download and install from github,Suggested download in wordpress plugin library:https://wordpress.org/plugins/wp-editormd/

Github needs to install dependencies. For more information read [https://github.com/JaxsonWang/WP-Editor.md#%E5%BC%80%E5%8F%91-development](readme.md)
