### ISSUE TITLE
请问一下 Masrkdown 转换的实现机理？

### ISSUE THREAD

**Issue by mashirozx** [JaxsonWang/WP-Editor.md#149]
请问是编辑时就把 markdown 转换好储存在数据库中的，还是每次有访问请求时即时转换的呢？

**Comment by JaxsonWang** [comment]
当你发布文章将md转化html，存入数据库。
其次你的每个文章的Markdown也同样存入数据库。
只是post多出一个字段

----------
该邮件从移动设备发送



--------------原始邮件--------------
发件人："Mashiro "<notifications@github.com>;
发送时间：2018年5月4日(星期五) 下午4:43
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[JaxsonWang/WP-Editor.md] 请问一下 Masrkdown 转换的实现机理？ (#149)
-----------------------------------

请问是编辑时就把 markdown 转换好储存在数据库中的，还是每次有访问请求时即时转换的呢？

**Comment by mashirozx** [comment]
@JaxsonWang 明白了，谢谢！
