### ISSUE TITLE
安全漏洞问题

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WP-Editor.MD#15]
详见地址：[中国国家信息安全漏洞库](http://www.cnnvd.org.cn/vulnerability/show/cv_cnnvdid/CNNVD-201706-002)

跨站攻击实例： [http://lncken.cn/?p=258](http://lncken.cn/?p=258)

本人尽快修复，并加速推送1.8版本，请知悉！！！

**Comment by JaxsonWang** [comment]
[Fix](https://github.com/JaxsonWang/WP-Editor.MD/commit/dcad8592ee840dec8751f9c4d400167ab846b429)

**Comment by giuem** [comment]
No Fix!

```
<img src="https://github.com/JaxsonWang/WP-Editor.MD/raw/master/Interface-logo.jpg" onload="alert(1)">
```

我看了下文档，应该使用 on* 方式过滤，但是我试了没有效果

**Comment by JaxsonWang** [comment]
第一次载入不会提示，但是如果在文章写入攻击脚本的话，存在问题...目前还在排查

**Comment by giuem** [comment]
看起来是编辑器的 BUG？

**Comment by JaxsonWang** [comment]
@giuem 是的，有人给出个修复[建议](https://github.com/pandao/editor.md/issues/258)，然而并不管用

**Comment by giuem** [comment]
这个编辑器自带的 XSS 过滤太弱了，要不要考虑引入第三方库，比如 [js-xss](https://github.com/leizongmin/js-xss) 进行过滤？

**Comment by JaxsonWang** [comment]
呃，不加了，先加个解析html开关，以后再说吧...感觉这个没啥用，都是从内部使用的编辑器...

**Comment by JaxsonWang** [comment]
```html
var htmlTagRegex = /\<(\w+)\s*([^\>]*)\>([^\>]*)\<\/(\1)\>/ig;
```
此正则只能适配闭合标签，如果是`<img />`就无法适配了，所以自己修改正则如下：
```html
var htmlTagRegex = /\<(\w+)\s*([^\>]*)\>([^\>]*)\<\/(\1)\>|\<\s*([^\>]*)\s(.*?)\/>/ig;
```
测试是可以，但是还是有存在xss脚本攻击存在

**Comment by JaxsonWang** [comment]
好吧，更暴力些，直接屏蔽`img`标签：
```html
//适配单标签和闭合标签
            html = html.replace(new RegExp("\<\s*" + tag + "\s*([^\>]*)\>([^\>]*)\<\s*\/" + tag + "\s*\>|\<\s*([^\>]*)\s(.*?)\>", "igm"), "");
```
暂时这样吧

**Comment by JaxsonWang** [comment]
[Fix](https://github.com/JaxsonWang/WP-Editor.MD/commit/f1e7720de45edd0ef76ce69d33ae85666e38d0a5)

**Comment by giuem** [comment]
只屏蔽 img 是不够的。。。。还有 video 标签，这个编辑器借助了 jQuery 来处理正则，这本身就是不对的。你可以试一下这个代码 

```
$('<video src="https://github.com/JaxsonWang/WP-Editor.MD/raw/master/Interface-logo.jpg" onerror="alert(1)">')
```

会直接弹窗


对 WordPress 不是很熟悉，不知道有没有相关的处理 XSS 的函数，在入库前过滤一下就好了

**Comment by JaxsonWang** [comment]
好吧，头都大了，直接引入xss脚本吧。没啥问题了...

[Fix](https://github.com/JaxsonWang/WP-Editor.MD/commit/a6224b6e2f46f962fa3b32339697662ce5a1cf9e)

**Comment by giuem** [comment]
那个，，，好像还有问题
现在编辑器那是没问题了，但是 XSS 代码还是会入库，还是会解析。

万恶之源还是在 Markdown 解析那

**Comment by JaxsonWang** [comment]
@giuem 好吧，忘了入库验证，现在看起来没啥问题了。

[解决入库XSS跨站攻击](https://github.com/JaxsonWang/WP-Editor.MD/commit/49f67baeb0761ef493d8a3cd01e1c1ac8e78e280)

**Comment by giuem** [comment]
这也太暴力了，会误伤的....

script javascript 这些关键字是可能出现在 pre 里的

**Comment by JaxsonWang** [comment]
呃，没想到这么多，现在好了，测试也没啥问题了。

[FIX](https://github.com/JaxsonWang/WP-Editor.MD/commit/28bc42b7203257b2e77868c623d1fc872b07378e)

**Comment by JaxsonWang** [comment]
又发现一个问题，入库xss验证，导致高亮失效，正在排查！

**Comment by JaxsonWang** [comment]
从`$m_AllowTag`数组删除`code`和`pre`，虽然可以了，不知有啥影响

**Comment by giuem** [comment]
建议你写一个单元测试，把所有的用法，还在各种语言的高亮，还有xss攻击写上，这样每次改代码就不会这么蛋疼了

**Comment by JaxsonWang** [comment]
嗯，我现在有个问题啊，就是过滤的时候，比如高亮：
```html
<pre class=""line-numbers"><code class=""language-javascript"">
</code></pre>
```
过滤多出个双引号...

还有使用md插入图片也会被过滤：

```html
<img src="%5C%22http://www.zhsrc.cn/wp-content/uploads/2017/05/2017052805085442.png%5C%22" alt="&quot;测试&quot;">
```

看了XssHtml没头绪
