### ISSUE TITLE
新版本无法正常使用功能

### ISSUE THREAD

**Issue by Loidfkdsmbd** [JaxsonWang/WP-Editor.md#151]
您好，我是wp editor的一位使用者，我更新了最新版的wp editor，但是更新完发现，所有的功能都不能用了，比如插入代码，文字加黑加粗， 摁下相应的图标没有反应，请问这是什么情况？

**Comment by JaxsonWang** [comment]
请贴上调试信息

**Comment by Loidfkdsmbd** [comment]
系统环境 | Linux
-- | --



















@JaxsonWang

**Comment by Loidfkdsmbd** [comment]
系统环境	Linux
运行环境	Apache
PHP版本	5.6.34
PHP运行环境	fpm-fcgi
Browser Information	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
WordPress版本	4.9.5
插件版本	5.0.5
jQuery版本	1.12.4
当前用户权限	administrator
WordPress地址	https://dfkdsmbd.cc
站点地址	http://dfkdsmbd.cc
常规设置	task_list => off 
imagepaste => off 
live_preview => off 
sync_scrolling => off 
html_decode => off 
static_cdn => //cdn.jsdelivr.net 
编辑器设置	theme_style => default 
code_style => default 
语法高亮设置	highlight_mode_auto => on 
line_numbers => off 
highlight_library_style => default 
highlight_mode_customize => off 
Emoji表情设置	support_emoji => off 
文章目录设置	support_toc => off 
科学公式设置	support_katex => off 
流程图设置	support_flowchart => off 
时序图设置	support_sequence => off 
sequence_style => simple 
高级设置	jquery_compatible => off 
katex_compatible => off 
@JaxsonWang

**Comment by JaxsonWang** [comment]
请强制刷新浏览器缓存再重试，大部分浏览器刷新方式：`ctrl+f5`

或者你可以进入`访客模式`测试是否存在问题

**Comment by Loidfkdsmbd** [comment]
刷新后没有改变，以访客身份可以正常阅读文章 @JaxsonWang

**Comment by JaxsonWang** [comment]
可能刷新方式不对，实在不行你可以去浏览器设置清除数据也可以。
