### ISSUE TITLE
Google Chrome下 文章编辑页控件加载问题

### ISSUE THREAD

**Issue by codeBooks** [JaxsonWang/WP-Editor.md#152]
在Google Chrome下,文章编辑也的控件点击以后无效,href指向为"javascript:;".
开发者模式console显示
`load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.5:9 JQMIGRATE: Migrate is installed, version 1.4.1
editormd.min.js?ver=5.0.6:1 on`

WP editor调试信息:
系统环境	WINNT
运行环境	Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1
PHP版本	7.1.1
PHP运行环境	apache2handler
Browser Information	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
WordPress版本	4.9.5
插件版本	5.0.6
jQuery版本	1.12.4
当前用户权限	administrator
WordPress地址	已隐藏
站点地址	已隐藏
常规设置	task_list => on 
imagepaste => on 
live_preview => off 
sync_scrolling => on 
html_decode => off 
static_cdn => //cdn.jsdelivr.net 
编辑器设置	theme_style => default 
code_style => default 
语法高亮设置	highlight_mode_auto => on 
line_numbers => on 
highlight_library_style => dark 
highlight_mode_customize => off 
Emoji表情设置	support_emoji => off 
文章目录设置	support_toc => on 
科学公式设置	support_katex => off 
流程图设置	support_flowchart => off 
时序图设置	support_sequence => off 
sequence_style => simple 
高级设置	jquery_compatible => off 
katex_compatible => off 

chrome版本:
65.0.3325.162（正式版本） （64 位）

**Comment by JaxsonWang** [comment]
参考：https://github.com/JaxsonWang/WP-Editor.md/issues/153
