### ISSUE TITLE
编辑器按钮失效（点击无效）

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WP-Editor.md#153]
最近收到很多关于该问题的例子。

 - 首先确保浏览器缓存已经清除，如果清除还存在问题继续排除。
 - 进入访客模式，或者更换其它浏览器进行测试，如果是正常可以判断是扩展问题（例如油猴脚本导致的），否则继续排除问题。
 - 暂完

**Comment by wda43779** [comment]
editor.md中函数editormd.mouseOrTouch有问题。
https://github.com/pandao/editor.md/blob/master/editormd.js#L4468
它原本的目的是判断设备是否有触摸屏，然后只给按钮添加“click”事件或则只添加“touchend”事件。但是没有考虑到有触摸屏的笔记本，此时只工具栏按钮只添加了“touchend”事件，即按钮不能用鼠标点击，触摸屏就可以点击，开发者工具模拟手机可以点击。

**Comment by XUANLANcognition** [comment]
@wda43779谢谢大神，又买了一台没触摸屏的本子，问题已解决;-)

**Comment by JaxsonWang** [comment]
@wda43779 这个倒是没在意 不过谢谢你反馈 我会测试看看，感谢

**Comment by dtsdao** [comment]
@wda43779 解决方案：
将[https://github.com/pandao/editor.md/blob/master/editormd.js#L4479](https://github.com/pandao/editor.md/blob/master/editormd.js#L4479)换为
`return mouseEventType+touchEventType;`即可解决
不知为何要设计这么个没乱用的函数= =

**Comment by JaxsonWang** [comment]
@dtsdao 之前有人PR，也是解决过的。下个版本整合该PR
https://github.com/JaxsonWang/WP-Editor.md/pull/29/files
