### ISSUE TITLE
高亮问题

### ISSUE THREAD

**Issue by Tokyo-Lei** [JaxsonWang/WP-Editor.md#154]
1 自动加载模式 编辑器内高亮正常，文章页面 HTML语言高亮不显示，其它语言高亮正常。
2 版本是5.0.6版本，没升级之前是好使的

**Comment by JaxsonWang** [comment]
请刷新下网页缓存，一般是这个导致的：

> Chrome浏览器：
> Windows和Linux操作系统:  Ctrl+Shift+R
> Mac OS: Cmd+Shft+R

> 火狐浏览器：
> Windows和Linux操作系统:  Ctrl+Shift+R
> Mac OS: Cmd+Shft+R

实在不行清除浏览器数据。

请确保语法声明是`html`区分大小写。

**Comment by Tokyo-Lei** [comment]
都排除了，前端代码看到
http://cdn.jsdelivr.net/npm/prismjs@1.14.0/components/prism-html.min.js
这个报404 找不到文件，其它CDN也是一样的。

**Comment by JaxsonWang** [comment]
请进入该文章点击`更新`按钮重新渲染即可。
