### ISSUE TITLE
在编辑器框打字的时候，鼠标点击会出现多行全选中的现象，有时候还会错乱，用的最新版wp

### ISSUE THREAD

**Issue by viruscoding** [JaxsonWang/WP-Editor.md#157]
非常感谢大神，插件真的是好用到不行。

- 今天写文章的时候出现了这个问题，还有时候鼠标上下滚动页面的时候，编辑框内的文字也会莫名其妙的多行选中。
- 插入图片的时候，突然多行选中，导致这几行被插入图片的那行代码替换。
- 一度怀疑自己修改了哪行代码，导致不兼容，其他人有这个情况吗？

**Comment by JaxsonWang** [comment]
多行？我这使用正常...

不清楚你的咋回事，要不然排除法看看？
