### ISSUE TITLE
插入带括号的链接时预览框的渲染逻辑有问题

### ISSUE THREAD

**Issue by the-eric-kwok** [JaxsonWang/WP-Editor.md#158]
**5.0.7 版本**

预览框渲染出错
![image](https://user-images.githubusercontent.com/16463312/39917099-15dffcbc-553f-11e8-8abd-d8f1259a2a92.png)
但是渲染出来的实际页面没有问题

插入的链接是[https://wiki.archlinux.org/index.php/Samba_(简体中文)#.E6.B7.BB.E5.8A.A0.E7.94.A8.E6.88.B7](https://wiki.archlinux.org/index.php/Samba_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)#.E6.B7.BB.E5.8A.A0.E7.94.A8.E6.88.B7)

**Comment by JaxsonWang** [comment]
不管怎么样，这样写法就是不规范吧...

**Comment by erickwoc** [comment]
可是有的网址会带括号啊……
也许可以试试嵌套？压栈什么的？
而且为什么最终渲染正常而预览不正常呢

**Comment by JaxsonWang** [comment]
@erickwoc 这个是内核问题了，我抛给`marked.js`了，至于解决看他们怎么说的。

地址：[Marked.js问题反馈](https://github.com/markedjs/marked/issues/1268)

**Comment by JaxsonWang** [comment]
Marked.js 0.4.0 解决以上问题 插件6.0.4更新推送
