### ISSUE TITLE
5.0.7版本保存或发布后原文被替换成格式化内容

### ISSUE THREAD

**Issue by vincent-xw** [JaxsonWang/WP-Editor.md#159]
首先感谢您开发出如此强大的插件方便博客文章的书写。下面简单描述一下我遇到的问题
前几日更新插件后今天尝试书写新的文章。书写阶段一切正常。但是点击保存或发布以后页面刷新后原本文本编辑框内的md文档会被自动替换成格式化后的HTML文档，即``### 标题``这种会显示成``<h3>标题</h3>``等一系列转换后的内容。求教为何会出现这种情况。谢谢。
插件版本：5.0.7
wp版本：4.9.5–zh_CN

**Comment by JaxsonWang** [comment]
[博客](https://iiong.com/wordpress-plugins-wp-editormd.html)

原理请看博客下面那张图，至于你这个原因请看博客QA解答

**Comment by vincent-xw** [comment]
感谢您的回复，参考了您给的博客链接以及查了一下数据库。
在上次插件更新前编辑的文章数据库有一个对应字段``post_content_filtered``用来存储md格式文档，对应的``post_content``字段存储格式化后的内容。
而新版本插件``post_content_filtered``字段也存储的是格式化后的内容，我想这是我遇到问题的主要原因。不知这个是wp的问题还是新版插件的引起的。
