### ISSUE TITLE
建议把编辑时默认的工具栏留出来

### ISSUE THREAD

**Issue by unlockingc** [JaxsonWang/WP-Editor.md#161]
有时候安装别的插件如Prism For WP,会有编辑栏按钮,感觉wp-editor把那个覆盖了会有点尴尬.

**Comment by JaxsonWang** [comment]
请确保下面选项打勾：
![image](https://user-images.githubusercontent.com/16836692/39965206-5acca058-56c7-11e8-9997-d852806f5a43.png)

保留原来的工具栏是毫无意义的，因为是无效存在。

其次`Prism For WP`的编辑按钮，同样在wp-editor.md是无效的。因为这是markdown文本编辑器然不是可视化编辑器，请不要混淆编辑器。

**Comment by unlockingc** [comment]
哦
