### ISSUE TITLE
How to use MindMap(如何使用思维导图)？

### ISSUE THREAD

**Issue by oklutu** [JaxsonWang/WP-Editor.md#163]
如题谢谢.如下的示例文件智能看到第一行的editor插件开发
```mind
-editor插件开发
-思维导字
-构思如何开发 3m
-查看新插件的提交代码修改量
-查看修改文件列表
-比对单个文件主要修改位置
-插件开发格式要求
-测试 6m
```

**Comment by JaxsonWang** [comment]
类似下面的效果：

\`\`\`mind
       -editor插件开发
         -思维导字
         -构思如何开发 3m
         -查看新插件的提交代码修改量
         -查看修改文件列表
           -比对单个文件主要修改位置
           -插件开发格式要求
         -测试 6m
\`\`\`

\`\`\`mind
- 我的
	- 时间管理
		- thinkido;
		- Task lists;
	- 时间日志
		-日总结
		-每日成长
	- 7天时间看一生
		- Task l ists;
		- time manager;
		- 兼职市场
\`\`\`

**Comment by JaxsonWang** [comment]
@oklutu 数据已经更新了 就是这样 你复制那个空格没了，所以渲染失败
