### ISSUE TITLE
代码高亮、公式、流程图等等功能都不好用

### ISSUE THREAD

**Issue by Feleti** [JaxsonWang/WP-Editor.md#165]
Linux
运行环境	nginx/1.12.2
PHP版本	7.2.4
PHP运行环境	fpm-fcgi
浏览器信息	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
WordPress版本	4.9.5
插件版本	6.0.1
jQuery版本	1.12.4
当前用户权限	administrator
WordPress地址	https://feleti.cn
站点地址	https://feleti.cn
常规设置	task_list => on 
imagepaste => on 
live_preview => on 
sync_scrolling => on 
html_decode => on 
static_cdn => //cdn.staticfile.org 
编辑器设置	theme_style => default 
code_style => default 
语法高亮设置	highlight_mode_auto => on 
line_numbers => on 
show_language => on 
highlight_library_style => default 
customize_my_style => nothing 
highlight_mode_customize => off 
Emoji表情设置	support_emoji => on 
文章目录设置	support_toc => on 
科学公式设置	support_katex => on 
FlowDiagram Settings	0 => 
Sequence Settings	0 => 
高级设置	jquery_compatible => on 
katex_compatible => off

**Comment by JaxsonWang** [comment]
more info to [https://iiong.com/wordpress-plugins-wp-editormd.html#comment-145](https://iiong.com/wordpress-plugins-wp-editormd.html#comment-145)
