### ISSUE TITLE
关于异步加载 js，导致语法高亮不能用的问题

### ISSUE THREAD

**Issue by Fisher-Wong** [JaxsonWang/WP-Editor.md#166]
1. 首先感谢一下。
2. 上次我提过一次 issue，您说是有其它prism冲突。
3. 后来我仔细看了一下，是异步js加载导致的。
4. 我用的是 Async JavaScript插件，本来只是想加快一下首屏加载速度，没想到冲突。
5. 找了个链接，貌似是prism 的问题？[How to load PrismJS asynchronously](http://veithen.github.io/2015/03/22/prismjs-async.html)
6. 我本人的网页（目前没开异步加载，能正常语法加亮）[ONVIF协议摄像机管理平台开发(12)获取视频流媒体地址GetProfiles和GetStreamUri](https://www.itmangoto.cn/2018/01/03/onvif-get-streamuri/)

**Comment by JaxsonWang** [comment]
关于这点 前端的Prism.js加载使用的是[AutoLoader](http://prismjs.com/plugins/autoloader/)加载插件，猜测这类可能和你说的异步加载产生冲突。其次我的脚本都是写在页脚上，很大的程度提高页面加载速度。

至于其他优化我会寻找更好的方案。

感谢反馈，祝使用愉快。
