### ISSUE TITLE
关于more过滤的问题

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WP-Editor.MD#17]
测试发现一个问题

目前在文章插入`<!--more-->`会被php XssHtml过滤。

我对php不是太熟了，看了也没看出啥，请求大佬帮助！

测试路径：`WP-Editor.MD/Jetpack/markdown/xsshtml_test.php`

[xsshtml.class.php](https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Jetpack/markdown/xsshtml.class.php)

将`<!--more-->`加入白名单即可！

**Comment by JaxsonWang** [comment]
@giuem dalao

**Comment by giuem** [comment]
最近在忙期末项目，还有期末考🌚

我下午看一下……

**Comment by giuem** [comment]
问题出在 `strip_tags` 这个函数

https://secure.php.net/manual/zh/function.strip-tags.php

>Note:
>HTML 注释和 PHP 标签也会被去除。这里是硬编码处理的，所以无法通过 allowable_tags 参数进行改变。

解决办法可能会有点脏， 比如先把 `<!--more-->` 替换成 `{!--more--}` 之类的，然后过滤完 xss 再替换回去

**Comment by JaxsonWang** [comment]
你这个说得我好迷糊...

**Comment by giuem** [comment]
在 https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Jetpack/markdown/xsshtml.class.php#L88 这里就已经把 `<!--more-->` 过滤了，因为这是 HTML 注释。

所以你只要在这句之前把 `<!--more-->` 替换成 `{!--more--}`，然后在 `getHtml()` 的时候把  `{!--more--}` 换回 `<!--more-->`

**Comment by JaxsonWang** [comment]
解决了，谢dalao
