### ISSUE TITLE
菜单添加自定义按钮

### ISSUE THREAD

**Issue by Lion-R** [JaxsonWang/WP-Editor.md#170]
我在官方的编辑菜单上添加了我的自定义按钮，但是用了这个编辑器以后就没有了，怎么能够把我的显示出来。

![image](https://www.kzwr.com/kzwrfs?fid=0e67eb7195c548deb230a1c81d31d64507ks.png)
![image](https://www.lion-r.cn/wp-content/uploads/2018/05/LCGBUG-2.png)

**Comment by JaxsonWang** [comment]
再加一次，然后别更新了，更新会丢失文件的
