### ISSUE TITLE
WP-Editor.md升级6.0.4版本后，WordPress中无法启用

### ISSUE THREAD

**Issue by happyMeiyo** [JaxsonWang/WP-Editor.md#175]
无法启用插件，因为它引起了一个**致命错误（fatal error）**。

Parse error: syntax error, unexpected T_STRING in /data/home/qxu1098390297/htdocs/wp-content/plugins/wp-editormd/wp-editormd.php on line 15

**Comment by JaxsonWang** [comment]
请确保插件最新版，并且PHP 5 >= 5.3.0

**Comment by happyMeiyo** [comment]
@JaxsonWang 我使用的是WordPress 4.9.6，WP-Editor.md 6.0.4。只是我不了解php，不知道如何解决这个问题。感谢！

**Comment by happyMeiyo** [comment]
升级阿里云服务器的PHP版本至5.5
