### ISSUE TITLE
&转换为&amp;的问题

### ISSUE THREAD

**Issue by JadeVane** [JaxsonWang/WP-Editor.md#176]
在代码块中包含字符&，例如插入下列代码块：
```
command && command
```
实时预览是正常的，但是发布网页之后`&`就变成`&amp;`了。
```
command &amp;&amp; command
```
而且在编辑界面是没办法更改的。
目前暂时的解决办法是停用插件，在wordpress自带的编辑界面点击网页代码选项，在html代码里面进行修改，改完再启用插件。

**Comment by JaxsonWang** [comment]
像这些实体字符先去类似的[转义工具](http://www.css88.com/tool/html-escape/)网站，将转换过的字符串复制到编辑器。

因wp有自带的过滤，针对这些优化比较麻烦，并且对此需求很少。所以稍微麻烦些，就这么弄吧。

**Comment by JadeVane** [comment]
直接输入转移后的字符的方法我试过，但不行，输入`&`显示的是`&amp;`，而输入`&amp;`显示的还是`&amp;`

**Comment by JaxsonWang** [comment]
@JadeVane 

没仔细看，这是输入代码块出现的？代码块对`&`进行反转义的。你是不是用别的什么高亮插件的？之前有人遇到类似的问题，是别的高亮插件导致的

**Comment by JadeVane** [comment]
试了一下，确实是高亮插件的问题，抱歉
