### ISSUE TITLE
实时预览的效果和WordPress网站页面解析出来的效果不一致

### ISSUE THREAD

**Issue by ScnuWang** [JaxsonWang/WP-Editor.md#177]
网站页面解析出来的效果是乱的，
请教一下，该如果解决？

**Comment by JaxsonWang** [comment]
更换主题或者修改当前主题样式。

[编辑器预览效果最终不影响前端文章效果！文章的样式取决于你的主题样式表，和本插件没有关系！](https://github.com/JaxsonWang/WP-Editor.md/blob/docs/zh-CN/synopsis.md#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)

**Comment by ScnuWang** [comment]
OK，多谢
