### ISSUE TITLE
一个小小的提议……？

### ISSUE THREAD

**Issue by hjthjthjt** [JaxsonWang/WP-Editor.md#180]
插件炒鸡棒(๑•̀ㅂ•́)و✧
希望可以有直接调用 SM.MS 的 API 来实现上传/粘贴上传的功能，而不是直接上传入媒体库_(:з」∠)_

附：SM.MS API : [https://sm.ms/doc/](https://sm.ms/doc/)

**Comment by JaxsonWang** [comment]
有这个想法的，我有空会加入的

**Comment by hjthjthjt** [comment]
非常感谢！
