### ISSUE TITLE
以缩进形式写的代码块不能正确地显示

### ISSUE THREAD

**Issue by hermitgreen** [JaxsonWang/WP-Editor.md#182]
以TAB缩进的代码区块在预览中可以正确显示，但是发布之后，HTML代码中该区块并未被\<code\>包围

**Comment by hermitgreen** [comment]
我不知道怎么贴图QAQ

**Comment by JaxsonWang** [comment]
tab缩进等价于<pre><code>代码块展示，并不是单独的code行内代码块显示。如果没有相关样式请检查主题是否带有代码块样式。

**Comment by hermitgreen** [comment]
thanks，问题已解决！
