### ISSUE TITLE
Mermaid 支持不縮放選項

### ISSUE THREAD

**Issue by david50407** [JaxsonWang/WP-Editor.md#183]
Mermaid 提供了一個不縮放的選項，希望 WP-Editor 可以支持這個參數讓 Mermaid 不自動縮放

ref: https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js#L156

**Comment by JaxsonWang** [comment]
主要是配置Mermaid可选选项没啥好的方案，给我时间看看有啥好的方法。

**Comment by JaxsonWang** [comment]
upgrade to https://github.com/JaxsonWang/WP-Editor.md/commit/c8f2d4edc1233abf477965c4eb6766fe603787ac
