### ISSUE TITLE
能不能恢复从本地加载js的功能啊

### ISSUE THREAD

**Issue by Zxilly** [JaxsonWang/WP-Editor.md#184]
这样我就可以用Autoptimize来聚合所有的js文件了

**Comment by JaxsonWang** [comment]
相信我，这是最好的方案...无论是流量还是速度，比Autoptimize合并好多了。。。

**Comment by Zxilly** [comment]
那能不能给一个从自己的CDN加载的接口啊。。。总感觉第三方的服务会一夜挂掉。。。

**Comment by JaxsonWang** [comment]
改动量太大，主要是编辑器本身就依赖很多库文件，使用几家的CDN已经安稳几年了，放心使用，就算是挂掉我也及时更新地址。

**Comment by Zxilly** [comment]
bootcdn的挂了,全是404

**Comment by JaxsonWang** [comment]
那就使用cdn.jsdelivr.net吧，下个版本只单独留下cdn.jsdelivr.net

**Comment by JaxsonWang** [comment]
如果恢复本地js zip基本是40M之大，wp服务器会拒绝的。。

**Comment by Zxilly** [comment]
能不能把所有的js聚合成一个文件啊,如果开的功能多的话加载那么多js的http开销相当大

**Comment by Zxilly** [comment]
我试着实现一下,考完来弄,回头交个PR

**Comment by JaxsonWang** [comment]
不需要PR了，本身就这样。
如果你有特定的需求请fork该项目自己该吧。
