### ISSUE TITLE
更新到新版本后编辑器界面没了。。。

### ISSUE THREAD

**Issue by Zxilly** [JaxsonWang/WP-Editor.md#185]
![image](https://user-images.githubusercontent.com/31370133/41850883-c2cb2c98-78b8-11e8-8813-f8c1002ff580.png)

**Comment by JaxsonWang** [comment]
到插件里找到wp-editor.md点击查看详细然后安装此插件重新安装下

**Comment by Zxilly** [comment]
![image](https://user-images.githubusercontent.com/31370133/41851655-30be15b0-78bb-11e8-8baf-08375fa91b1a.png)
更新后好了，谢谢大佬

**Comment by moshanghan** [comment]
![image](https://user-images.githubusercontent.com/30591457/42135865-e13e1a3a-7d83-11e8-8ed3-4778d5979e9b.png)
