### ISSUE TITLE
编辑器显示问题

### ISSUE THREAD

**Issue by moshanghan** [JaxsonWang/WP-Editor.md#187]
wordpress版本：4.9.6
php版本：5.5
![image](https://user-images.githubusercontent.com/30591457/42140679-07c103d8-7dd5-11e8-8cf4-7c5285067d33.png)
  编辑器显示不正常

**Comment by JaxsonWang** [comment]
关闭额外对原生编辑器的插件（排除插接法）

**Comment by moshanghan** [comment]
感谢回复
我关闭了Kindeditor For Wordpress
这样算正常吗？
![image](https://user-images.githubusercontent.com/30591457/42143829-e15e2be8-7de9-11e8-955a-dd7e51561b0b.png)

**Comment by JaxsonWang** [comment]
@moshanghan 看起来还是不正常，第一行有空白。干脆全部停用，然后再一个一个启用看看。

**Comment by JaxsonWang** [comment]
那就启用吧，卸载wp-editor.md即可

**Comment by moshanghan** [comment]
要对wp.editor.md 说bye-bye了？

**Comment by moshanghan** [comment]
![image](https://user-images.githubusercontent.com/30591457/42145469-5e8c0504-7df4-11e8-8a04-5c4d16ee6d9e.png)
全部禁用了
![image](https://user-images.githubusercontent.com/30591457/42145472-67b5d34e-7df4-11e8-839d-361d88a985c1.png)
就开了这个
然而，还是异常

**Comment by JaxsonWang** [comment]
理论上是没有问题的，如果插件都排除完毕，请继续排除是不是主题（切换默认主题）。

再之浏览器扩展插件导致什么的。自行排除，毕竟就你一个案例问题。
