### ISSUE TITLE
语法高亮失效

### ISSUE THREAD

**Issue by H-xie** [JaxsonWang/WP-Editor.md#188]
按照wordpress的更新提示，更新了插件。（6.0.5.1版本）
所有文章的语法高亮显示格式均不可调整。没有提示什么错误，反复在语法高亮页重新选中`自动加载模式`仍然不可行。

**Comment by JaxsonWang** [comment]
请在前端有语法高亮打开控制台F12，有红色错误请贴出来。

**Comment by H-xie** [comment]
F12打开控制台，但是没有红色的错误
点击 <code> 标签看到它的 styles 都是来自我使用的theme

**Comment by H-xie** [comment]
在指明代码块的语言后，语法高亮才会生效
如：
```
```bash
xxxxx some code xxxxx
```

如果只是 ``` 在插件中指定的语法高亮是无法生效的。这是bug吗？还是作者的设定？

**Comment by JaxsonWang** [comment]
没有指定对应的语法类型是不显示的，PrismJS是是根据语法高亮来渲染的。
具体查看：https://prismjs.com/
