### ISSUE TITLE
两个表格之间语法失效

### ISSUE THREAD

**Issue by playNoA** [JaxsonWang/WP-Editor.md#189]
两个表格之间页面语法失效，编辑时预览好好的，WP页面就不显示语法

![wp-before](https://user-images.githubusercontent.com/7344597/42413439-92d82df8-8252-11e8-9ca0-a97350454424.png)
![wp-after](https://user-images.githubusercontent.com/7344597/42413440-978ce03c-8252-11e8-991a-1ee84ea58936.png)

**Comment by JaxsonWang** [comment]
不同的md语法请换一行，插件的md风格支持“标准”Markdown / CommonMark和Github风格的语法。相对比较严格。例如你的表格后应该换行在另起标题，
