### ISSUE TITLE
希望支持粘贴图片到阿里云OSS

### ISSUE THREAD

**Issue by liyangpro** [JaxsonWang/WP-Editor.md#190]
目前插件支持了SM图库，但是毕竟第三方图库不是很放心，希望能支持阿里云OSS，腾讯之类的自己能掌控的地址。
其他都挺不错的，感谢作者。

**Comment by JaxsonWang** [comment]
这个有wp插件集成的，你可以安装它们使用同样可以达到使用效果。再加上我可能没精力维护这么多插件共能了。
