### ISSUE TITLE
Cannot input Chinese on iPhone Safari

### ISSUE THREAD

**Issue by twei7** [JaxsonWang/WP-Editor.md#191]
The plugin works well on desktop. But when I try on my phone, I am not able to type in any chinese character, despite the input method is already switched to chinese.

WP Editor.md Version 6.0.5.1
Wordpress: 4.9.7
iPhone 6s, IOS 11.4

**Comment by JaxsonWang** [comment]
已确认移动端工具栏覆盖可编辑器区域导致无法写作。
下个版本条件该区域样式问题。

**Comment by JaxsonWang** [comment]
包括中文输入不全的奇葩问题

**Comment by JaxsonWang** [comment]
已确认内核问题，并且发现原有issue：https://github.com/codemirror/CodeMirror/issues/3137
但目前官方没有解决该问题。

有个临时解决方法：https://www.qyh.me/space/java/article/codemirror-ios-input-chinese-bug
不过这个方法并不是很完美，此问题暂时搁浅吧。

建议移动端下个markdown写作App，再把内容复制发布即可。
