### ISSUE TITLE
开启了html解析之后，本来的markdown 语法在发表文章后变成了html标签

### ISSUE THREAD

**Issue by XGZepto** [JaxsonWang/WP-Editor.md#192]
rt，并且开了多语言以后非主语言的编辑界面还是原始的样式。

**Comment by JaxsonWang** [comment]
确定期间没运行清理垃圾的插件？

**Comment by XGZepto** [comment]
@JaxsonWang  
有那么一丝丝关联的插件：

- Autoptimize
- Jetpack
- Smush

**Comment by JaxsonWang** [comment]
说实话，这个的确很迷，而且遇到像你这样情况也就几个，问了情况无法重现问题。
再说插件因素实在是太多了，希望你能够提供更有用的信息：
例如在转换html之前你操作了什么？等

**Comment by Zxilly** [comment]
多语言的锅，XG你要不要试试WPML @XGZepto
