### ISSUE TITLE
代码框内的问题

### ISSUE THREAD

**Issue by farmerluo** [JaxsonWang/WP-Editor.md#193]
比如类似以下代码：
```bash
modprobe br_netfilter
cat <<EOF >  /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sysctl -p /etc/sysctl.d/k8s.conf
ls /proc/sys/net/bridge
```

通过html查看时cat <<EOF >会变成cat < <EOF >，<<中间多了一个空格。

可参考这个文档内的问题，类似的情况全部都多了一个空格。
http://www.huilog.com/?p=996

**Comment by JaxsonWang** [comment]
我在默认主题以及自带的高亮中：
![image](https://user-images.githubusercontent.com/16836692/42940412-efc94f32-8b8b-11e8-9770-77d968866d5e.png)
![image](https://user-images.githubusercontent.com/16836692/42940417-f457ef54-8b8b-11e8-9b07-dddd889d002e.png)

看起来是正常，你博客用别的语法高亮插件，我猜测可能它有关系，至于这个我就帮不到的了，这应该算起来是那个插件bug...

**Comment by farmerluo** [comment]
知道问题原因了，关闭“让WordPress自动校正嵌套错误的XHTML代码”就好了
