### ISSUE TITLE
一直显示这个，无法正常加载不知道什么原因

### ISSUE THREAD

**Issue by lovezeropython** [JaxsonWang/WP-Editor.md#194]
一直显示这个，无法正常加载不知道什么原因

![image](https://user-images.githubusercontent.com/35518020/43173706-e5580ac8-8fe8-11e8-8aee-e8a44ee69509.png)

![image](https://user-images.githubusercontent.com/35518020/43173697-d994b5b0-8fe8-11e8-9d80-905d7e449d2f.png)

**Comment by JaxsonWang** [comment]
请提交更多有用的信息，例如控制台的一些报错信息。
