### ISSUE TITLE
unexpected T_STRING 导致无法启用插件

### ISSUE THREAD

**Issue by peipeihh** [JaxsonWang/WP-Editor.md#195]
启用插件时，报如下错误信息：

Parse error: syntax error, unexpected T_STRING in /data/home/qxu1192700241/htdocs/wp-content/plugins/wp-editormd/wp-editormd.php on line 15
无法启用插件，因为它引起了一个致命错误（fatal error）。

版本：
WordPress版本为 4.9.7–zh_CN
WP Editor.md 6.0.7版本

更多信息：半年前安装WP Editor.md，一直用到最近升级到6.0.5版本出现问题，今天升级到6.0.7问题还是存在。删除插件重新安装，问题还是重现。

**Comment by peipeihh** [comment]
下载了5.0.8版本手动上传安装，也报同样的错误。

**Comment by Zxilly** [comment]
目测是php版本问题，你的php版本是？

**Comment by peipeihh** [comment]
我使用的PHP版本为5.2.17。不知道editor这边推荐兼容的php版本是多少？

**Comment by JaxsonWang** [comment]
@peipeihh 最低5.3，不过国内虚拟机基本都上5.3了。你可以联系服务商调整下。

**Comment by peipeihh** [comment]
我用的是阿里云，他们升级需要更新服务器规格，比较麻烦，我想先用之前的wp-editor版本，你这里有没较早前的版本，我这边手动安装回老版本。若有的话，麻烦发送到我邮箱peipeihh@qq.com。多谢了。

**Comment by peipeihh** [comment]
多谢。
