### ISSUE TITLE
cdn屏蔽

### ISSUE THREAD

**Issue by kririae** [JaxsonWang/WP-Editor.md#196]
cdn.bootcss.com屏蔽了所有的.cc域名，请求修复
katex等用不了
![image](https://user-images.githubusercontent.com/24610355/43385318-0a5ff122-9413-11e8-8045-78fbfc90e04e.png)

**Comment by JaxsonWang** [comment]
建议使用jsdelivr，国内是网宿代理，质量还可以。bootcdn更新很慢，所以 有些资源不存在

**Comment by kririae** [comment]
@JaxsonWang 如何切换？

**Comment by JaxsonWang** [comment]
![image](https://user-images.githubusercontent.com/16836692/43386547-84dcdfd4-9416-11e8-9ccf-6eb37f9d3552.png)
您这是从来不看下设置么？

**Comment by kririae** [comment]
QAQ抱歉没看到QAQ

**Comment by kririae** [comment]
@JaxsonWang 抱歉没看到QAQ
