### ISSUE TITLE
Mermaid 绘图无法显示

### ISSUE THREAD

**Issue by Skywt2003** [JaxsonWang/WP-Editor.md#197]
在文章编辑界面的 Markdown 预览部分，部分 Mermaid 绘图是可以显示的，但是发布文章后查看文章的页面，Mermaid 绘图就全部无法显示，变成空白，代码也不显示。

在绘图文档（https://raw.githubusercontent.com/JaxsonWang/WP-Editor.md/docs/Example/Mermaid.md）粘贴到编辑器里后，最后有几个 Mermaid 代码粘贴到文本编辑器里都无法显示预览，只会显示出代码。文章发布后仍然只显示代码。

我使用默认的 Mermaid 绘图配置。我打开了“支持绘图”选项。我已经将插件升级到最新版本。

希望尽快解决～谢谢～

**Comment by JaxsonWang** [comment]
mermaid文档有错误，修正：https://raw.githubusercontent.com/JaxsonWang/WP-Editor.md/docs/Example/Mermaid.md

**Comment by Skywt2003** [comment]
在文本编辑器里正常显示，但是发布后看文章就无法显示了……

https://skywt.cn/posts/%E7%BB%98%E5%9B%BE%E6%B5%8B%E8%AF%95/

**Comment by JaxsonWang** [comment]
麻烦你到插件设置-绘图设置 点击下保存的按钮。看了下是设置数据没出来。

**Comment by Skywt2003** [comment]
哇，可以了！谢谢～～～
