### ISSUE TITLE
Wordpress 下个版本将会使用全新的编辑器，会对 WP Editor.md 插件有影响吗？

### ISSUE THREAD

**Issue by Skywt2003** [JaxsonWang/WP-Editor.md#199]
今天看到wordpress仪表盘出现“A new, modern publishing experience is coming soon.”的广告了，说如果要旧版编辑器则需要安装插件，wordpress更新后将自动内置“古腾堡”编辑器……会影响 wp editor.md 插件吗？qwq

**Comment by JaxsonWang** [comment]
不太清楚，但肯定有相关api可以关闭古腾堡编辑器的。
