### ISSUE TITLE
窗口大小变化时出现错位

### ISSUE THREAD

**Issue by TechCiel** [JaxsonWang/WP-Editor.MD#2]
RT，在如下情况发生，编辑器空间变大变小时，似乎没有resize编辑器
1. 窗口大小改变
2. 收起左侧后台导航菜单
3. 将两栏布局变为一栏

**Comment by JaxsonWang** [comment]
您说的错位 具体是什么的？我尝试您说的那几种情况，并没有出现错位问题，或者是编辑器无变化的问题。

**Comment by TechCiel** [comment]
一会我看看提供一下截图

**Comment by TechCiel** [comment]
感受一下...无法完美的Resize
![image](https://cloud.githubusercontent.com/assets/22628325/24955328/8b6714e0-1fb5-11e7-9738-04ae1372e37c.png)
![image](https://cloud.githubusercontent.com/assets/22628325/24955349/99f841c8-1fb5-11e7-8314-55abaf67c74e.png)
![image](https://cloud.githubusercontent.com/assets/22628325/24955357/a61f1a12-1fb5-11e7-8cc2-0058619c0da5.png)
![image](https://cloud.githubusercontent.com/assets/22628325/24955369/b68785d8-1fb5-11e7-9f56-6caefdf48b6c.png)
![image](https://cloud.githubusercontent.com/assets/22628325/24955479/2dbbda46-1fb6-11e7-9f68-c6185cb196fc.png)
![image](https://cloud.githubusercontent.com/assets/22628325/24955502/3eded18e-1fb6-11e7-8056-e4b35dbee2fa.png)
![image](https://cloud.githubusercontent.com/assets/22628325/24955510/4ae0724e-1fb6-11e7-9ec5-30d46ce4fef1.png)

**Comment by TechCiel** [comment]
这次MSIE11也没救得了我

**Comment by JaxsonWang** [comment]
这个没思路啊，用了这么多天，都无所谓了...
