### ISSUE TITLE
更新后编辑器无法显示

### ISSUE THREAD

**Issue by yyyyyyyhb** [JaxsonWang/WP-Editor.MD#20]
![snipaste20170621_201652](https://user-images.githubusercontent.com/8311904/27383689-ad11dc16-56be-11e7-9b22-21d9d94461b2.png)
就是最新的两个版本都这样

**Comment by JaxsonWang** [comment]
开启Debug
你可以在安装目录下的`wp-config.php`文件，搜索`WP_DEBUG`关键词把`false`改成`true`保存文件，再开启插件报什么错误，贴上了

**Comment by yyyyyyyhb** [comment]
没有报错，仅仅是显示不了

**Comment by yyyyyyyhb** [comment]
默认主题

**Comment by JaxsonWang** [comment]
那就删除插件看看..重新装

**Comment by yyyyyyyhb** [comment]
Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Markdown_Parser has a deprecated constructor in ~/public_html/wp-content/plugins/wp-editormd/Jetpack/lib/markdown/extra.php on line 73

Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; MarkdownExtra_Parser has a deprecated constructor in ~/public_html/wp-content/plugins/wp-editormd/Jetpack/lib/markdown/extra.php on line 1554

**Comment by JaxsonWang** [comment]
您的PHP是什么版本的？

**Comment by yyyyyyyhb** [comment]
PHP7.1

**Comment by JaxsonWang** [comment]
好的 等等我找这个版本测试下

**Comment by yyyyyyyhb** [comment]
好的~

**Comment by JaxsonWang** [comment]
解决了...

**Comment by yyyyyyyhb** [comment]
我下载了GH开发版，没有报错了但还是不显示

**Comment by JaxsonWang** [comment]
请详细贴出的环境：PHP版本，Web软件类型版本，WP的版本

**Comment by giuem** [comment]
请列一下使用的插件和主题

**Comment by yyyyyyyhb** [comment]
全部插件停用后确定是因为启用了Accelerated Mobile Pages插件才会不显示，Accelerated Mobile Pages是默认设置可否帮忙看下

**Comment by JaxsonWang** [comment]
这个插件很强大，以至于我无法下手...要不然你暂时放弃某个吧
