### ISSUE TITLE
编辑器空格、换行无法正常输出

### ISSUE THREAD

**Issue by gyucudu** [JaxsonWang/WP-Editor.md#201]
我在编辑器中插入一段代码，比如是这样：
```
while (true){
    System.out.println("Test");
}
```
在编辑器的预览中还显示得不错，但是发布之后就变成这样了，十分别扭
```
while (true){ System.out.println("Test"); }
```
而且我看原版的编辑器似乎也有类似这样的问题，忽略了换行和空格，而且如果用< p > 和 < br / >标签配合着写虽然也可以，但是看着总感觉有点不爽
请问能修复一下这个小问题吗？（或者是说我什么地方搞错了，有什么设置项没有开启）
如果是小问题的话，可以提供一个思路：保存的时候不要过滤<  p  > 和 <  br   /    > 标签(因为Github的编辑器会识别这两个标签，所以加了空格)

**Comment by JaxsonWang** [comment]
[移除WordPress短代码中自动添加的 br 和 p 标签](http://zmingcx.com/remove-the-shortcode-br-and-p-tag.html)
插件没有上面所述的函数，请到你的主题function.php检查是否存在上述的代码，如果有请删除。

**Comment by gyucudu** [comment]
我已在我当前主题中的function.php删除了上面链接中提到的函数，可惜情况似乎没有什么变化。
![01](https://user-images.githubusercontent.com/22651550/43962567-9f8e3eae-9cea-11e8-9caf-4f78a83e8a94.png)
![02](https://user-images.githubusercontent.com/22651550/43962555-9593d90e-9cea-11e8-9346-435430879e34.png)

**Comment by gyucudu** [comment]
我删除了之前的文章并重新写了一篇，可惜这个问题似乎仍然存在。
![01](https://user-images.githubusercontent.com/22651550/43963640-74f4c872-9ced-11e8-93fc-f9d26bca7548.png)
![02](https://user-images.githubusercontent.com/22651550/43963643-764b54b6-9ced-11e8-9aae-9ae204fe2adc.png)

**Comment by JaxsonWang** [comment]
切换默认主题再看看。

**Comment by gyucudu** [comment]
在首页上看上去有改善，但是打开文章后仍和上面第二张图中的一样。
![01](https://user-images.githubusercontent.com/22651550/43963920-479f6afc-9cee-11e8-845c-4ad457c04892.png)

主题是 Twenty Seventeen

**Comment by JaxsonWang** [comment]
确定更换主题 文章数据同样也更新了？

如果还存在问题请停用其它插件除了编辑器以外

**Comment by gyucudu** [comment]
主题我已经确定更换为了WordPress自带的Twenty Seventeen
文章我又删了重新写了另外一篇，同时并关闭了除编辑器外所有的插件
情况确乎是有些好转了，文章打开后代码块的排版仍然正常。但是tab和空格没有表现出来
![img_20180810_225520](https://user-images.githubusercontent.com/22651550/43964989-a58efe14-9cf0-11e8-9bb8-307f38d4b144.jpg)

**Comment by JaxsonWang** [comment]
"但是tab和空格没有表现出来"
具体是什么意思？截图？

**Comment by gyucudu** [comment]
如图所示
![img_20180810_231222](https://user-images.githubusercontent.com/22651550/43965876-fc0c89f8-9cf2-11e8-8e2e-c09162a3744f.jpg)
![img_20180810_231250](https://user-images.githubusercontent.com/22651550/43965899-05e02cc8-9cf3-11e8-8abc-e9d845c49cde.jpg)

**Comment by JaxsonWang** [comment]
在代码块效果存在，但正常编辑因为有脚本攻击问题过滤这些。如果你需要请用`&nbsp;`替代。

请排查你的插件兼容问题。
