### ISSUE TITLE
预览没有问题，就是博客的真实文章页面插件没有生效

### ISSUE THREAD

**Issue by jiangdongGitHub** [JaxsonWang/WP-Editor.md#202]
博客文章：http://jiangdong.me/%E8%92%8B%E5%86%AC%E6%97%A5%E5%BF%97-daily-one/

系统环境	Linux
运行环境	Apache
PHP版本	7.0.8
PHP运行环境	cgi-fcgi
浏览器信息	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15
WordPress版本	4.9.8
插件版本	6.0.7
jQuery版本	1.12.4
当前用户权限	administrator
WordPress地址	http://jiangdong.me
站点地址	http://jiangdong.me
常规设置	task_list => off 
imagepaste => off 
imagepaste_sm => off 
live_preview => on 
sync_scrolling => on 
html_decode => on 
static_cdn => //cdn.jsdelivr.net 
编辑器设置	theme_style => default 
code_style => default 
语法高亮设置	highlight_mode_auto => off 
line_numbers => off 
show_language => off 
copy_clipboard => off 
highlight_library_style => default 
customize_my_style => nothing 
highlight_mode_customize => off 
customize_highlight_style => nothing 
customize_highlight_javascript => nothing 
Emoji表情设置	support_emoji => off 
文章目录设置	support_toc => on 
科学公式设置	support_katex => off 
绘图设置	support_katex => off 
高级设置	jquery_compatible => off 
katex_compatible => off 
hide_ads => off

**Comment by JaxsonWang** [comment]
什么叫“博客的真实文章页面插件没有生效”？

**Comment by jiangdongGitHub** [comment]
效果和预览的时候不一样，我没装插件和装了插件，文章的显示都是一样
http://jiangdong.me/%E8%92%8B%E5%86%AC%E6%97%A5%E5%BF%97-daily-one/

**Comment by JaxsonWang** [comment]
> 编辑器预览效果最终不影响前端文章效果！文章的样式取决于你的主题样式表，和本插件没有关系！
