### ISSUE TITLE
本来的markdown 语法在发表文章后变成了html标签

### ISSUE THREAD

**Issue by ncs19960831** [JaxsonWang/WP-Editor.md#203]
看了关闭的issue，里面有个和我差不多的，但是有些不同，所以单开一个issue。
问题如题，但是基本上可以确定是因为Gutenberg插件引起的问题，即使选择了“Replace the Gutenberg editor with the Classic editor.	”依然出现这个问题，卸载Gutenberg问题解决。

> `系统环境	Linux
> 运行环境	nginx/1.14.0
> PHP版本	7.2.X
> PHP运行环境	fpm-fcgi
> 浏览器信息	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
> WordPress版本	4.9.8
> 插件版本	6.0.7
> jQuery版本	1.12.4
> 常规设置	task_list => on 
> imagepaste => on 
> imagepaste_sm => on 
> live_preview => on 
> sync_scrolling => on 
> html_decode => off 
> static_cdn => //cdn.jsdelivr.net 
> 编辑器设置	theme_style => default 
> code_style => default 
> 语法高亮设置	highlight_mode_auto => on 
> line_numbers => on 
> show_language => on 
> copy_clipboard => on 
> highlight_library_style => default 
> customize_my_style => nothing 
> highlight_mode_customize => off 
> Emoji表情设置	support_emoji => on 
> 文章目录设置	support_toc => on 
> 科学公式设置	support_katex => on 
> 绘图设置	support_mermaid => on 
> mermaid_config => { theme: "default", themeCSS: undefined, logLevel: 5, arrowMarkerAbsolute: false, startOnLoad: true, flowchart: { htmlLabels: true, curve: "linear" }, sequence: { diagramMarginX: 50, diagramMarginY: 10, actorMargin: 50, width: 150, height: 65, boxMargin: 10, boxTextMargin: 5, noteMargin: 10, messageMargin: 35, mirrorActors: true, bottomMarginAdj: 1, useMaxWidth: true }, gantt: { titleTopMargin: 25, barHeight: 20, barGap: 4, topPadding: 50, leftPadding: 75, gridLineStartPadding: 35, fontSize: 11, fontFamily: '"Open-Sans", "sans-serif"', numberSectionStyles: 4, axisFormat: "%Y-%m-%d" } } 
> 高级设置	jquery_compatible => off 
> katex_compatible => off 
> hide_ads => on

**Comment by JaxsonWang** [comment]
如果使用Gutenberg重新编辑markdown文章就会污染文章数据转换成html，所以没什么办法，只能重写或者彻底禁用Gutenberg编辑器。

**Comment by ncs19960831** [comment]
但是以后wordpress 极有可能会取消旧版的文档编辑器，这样不是就会很尴尬么:D

**Comment by JaxsonWang** [comment]
你的意思是你不仅仅用wp-editor.md还需要用到Gutenberg或者经典编辑器？目前来看WP不太可能放弃经典编辑器。这些我也不是太清楚，等他出来再说吧。
再说用editor.md足够了，没必要再用富文本编辑器了。

**Comment by ncs19960831** [comment]
可能是我的理解错误，也就是说wp-editor.md是独立于wordpress编辑器以外的独立编辑器对吗？
那我也就不担心了~谢谢
