### ISSUE TITLE
[toc] tag not rendering on general page view

### ISSUE THREAD

**Issue by baram204** [JaxsonWang/WP-Editor.md#204]
## Env

**Client**

OS: windows 7 64bit
Browser : Chrome 68.0.3440.106

**Server**

WP : 4.9.8
DB : mysql
Theme : Twenty Seventeen 1.6

**Plugins**

![image](https://user-images.githubusercontent.com/11155414/44009471-161291c6-9ee7-11e8-9348-8612608cf3e7.png)

I think, there is no plugin affects markdown render process.

## Symtoms

When I write a article, Editor pane renders `[toc]` tag well.

![image](https://user-images.githubusercontent.com/11155414/44009332-0e2a5d32-9ee6-11e8-9a4b-7d7fcadc472a.png)

But, When I see article in general page view, It won't work.

![image](https://user-images.githubusercontent.com/11155414/44009569-ddd84d72-9ee7-11e8-9d11-f338ad5bc0b1.png)

## Reproduce

1. oepn markdown editor.
2. use `[toc]` tag
3. then publish it.
4. see It on general view page.

**Comment by JaxsonWang** [comment]
I think you need install this Table of Contents Plus Plugin for [WordPress](https://wordpress.org/plugins/table-of-contents-plus/) if not installed it.
