### ISSUE TITLE
图片不支持居中

### ISSUE THREAD

**Issue by yu243e** [JaxsonWang/WP-Editor.md#205]
页面的文本
<div align=center>
	
![](http://120.79.156.255/wordpress/wp-content/uploads/2018/08/2-1-300x177.png)
</div>
在实时预览中可以看到居中效果
在实际显示不出来。
如果有可替代的居中居右居左也行。

**Comment by yu243e** [comment]
\<div align=center>
	
\![]\(http://120.79.156.255/wordpress/wp-content/uploads/2018/08/2-1-300x177.png)
\</div>

**Comment by JaxsonWang** [comment]
为何不直接富文本编写？html加杂markdown看着都难受。
```
<div align=center>
<img src="http://120.79.156.255/wordpress/wp-content/uploads/2018/08/2-1-300x177.png">
</div>
```

本来markdown就不支持文章排版，你要是有特殊需求建议直接html编写就行了。
