### ISSUE TITLE
列表，表格中的katex公式不能在实时预览中正确显示

### ISSUE THREAD

**Issue by felinae98** [JaxsonWang/WP-Editor.md#206]
![image](https://user-images.githubusercontent.com/23295345/44246217-930b4a80-a20f-11e8-8238-fde6ddf82550.png)
![image](https://user-images.githubusercontent.com/23295345/44246224-a1596680-a20f-11e8-8497-33021bd725d7.png)

**Comment by JaxsonWang** [comment]
你确定设置选项打开了？
![image](https://user-images.githubusercontent.com/16836692/44247667-9eaf3f00-a218-11e8-9d8b-f98ebeb7c8cb.png)

**Comment by TangYuming** [comment]
![image](https://user-images.githubusercontent.com/23295345/44248430-10898780-a21d-11e8-8af1-bf9954932c38.png)
开了呀，不在表格列表里正常的

**Comment by JaxsonWang** [comment]
已确定原[editor.md](http://pandao.github.io/editor.md/)存在问题，该问题将下个版本解决。
![image](https://user-images.githubusercontent.com/16836692/44249841-5ac23700-a224-11e8-93fe-e3c53139c7d7.png)

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/Editormd/commit/dec95d8d45620e52faa0774e4287b6654bdbfc14
