### ISSUE TITLE
改用MathJAX后预览无法显示

### ISSUE THREAD

**Issue by JemmyLoveJenny** [JaxsonWang/WP-Editor.md#207]
由于需要用到LaTeX的mhchem宏包，所以我没有用KaTeX，而是该用了MathJAX加extensions的形式显示公式。  
```
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<script type="text/x-mathjax-config">
	MathJax.Ajax.config.path["mhchem"] =
	"https://cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.0";
	MathJax.Hub.Config({
		TeX: {
			extensions: ["[mhchem]/mhchem.js"]
		}
	});
	MathJax.Hub.Config({
		tex2jax: {['$','$'], ['\\(','\\)']]}
	});
</script>
```

就是页面中有这一段<script>标签就可以正常显示公式。  
但是在编辑的时候就预览不到公式的效果，请问是为什么呢？  
我确定在编辑的页面也同样加载了这段<script>  
原本以为是因为$符号在预览界面没有显示出来，所以我还改过以@替代$，但是在预览的地方@正常显示出来了，还是没有变成公式。  
我就不太知道是为什么了呢……？

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/Editormd/blob/master/src/editormd.js#L1445-L1469

https://github.com/JaxsonWang/Editormd/blob/master/src/editormd.js#L1961-L1972

https://github.com/JaxsonWang/Editormd/blob/master/src/editormd.js#L3764-L3784

https://github.com/JaxsonWang/Editormd/blob/master/src/editormd.js#L4000-L4019

你需要修改原有的资源加载文件以及业务逻辑。建议fork [Editormd](https://github.com/JaxsonWang/Editormd)替换js文件即可。

**Comment by JemmyLoveJenny** [comment]
好的，谢谢！
