### ISSUE TITLE
新版本6.1.0&6.1.1有插入图片链接无法显示问题

### ISSUE THREAD

**Issue by iinstam** [JaxsonWang/WP-Editor.md#210]
上一版本完全没问题
关闭WP-Editor.md也能正常显示
所以推断应该是更新的bug

**Comment by JaxsonWang** [comment]
请说清楚，什么叫“插入图片链接无法显示”，截图更好

**Comment by iinstam** [comment]
简单的说 就是正常的图片![](http://xx.jpg)会出现无法显示问题
在未更新前没有动过文章，更新后就无法显示，关闭WP-Editor.md能正常显示图片

**Comment by JaxsonWang** [comment]
![image](https://user-images.githubusercontent.com/16836692/44301314-4f1b6100-a347-11e8-927f-cf3ff1a19116.png)
![image](https://user-images.githubusercontent.com/16836692/44301319-5b072300-a347-11e8-9b2c-fc573fc9aaf0.png)
![image](https://user-images.githubusercontent.com/16836692/44301323-5f334080-a347-11e8-92c2-a926dbd91041.png)

没有出现你说的情况。

**Comment by iinstam** [comment]
![](http://upload-images.jianshu.io/upload_images/9630244-ac34a521f99ca548.jpg)

**Comment by JaxsonWang** [comment]
@iinstam 你确定url是正确的？

如果不能显示请在当前页面按F12在`console`窗口如果出现红字字符串请截图或者复制上来。

**Comment by iinstam** [comment]
正常预览文章里面是有这个问题的，而且是在更新后就出现了，所以就立刻反馈给作者了

**Comment by iinstam** [comment]
我的问题是出在更新插件后，而不是链接是否正确噢，因为链接已经正常放了一个月了

**Comment by JaxsonWang** [comment]
99%是你的环境有问题，不管是不是url是否能用，不排除你现在的环境下依然有之前缓存问题。

你可以换个浏览器或者访客模式重新加载一次再看看。

否则请在当前页面按F12在console窗口如果出现红字字符串请截图或者复制上来。

**Comment by iinstam** [comment]
好的，我在看看吧
