### ISSUE TITLE
有js文件404

### ISSUE THREAD

**Issue by windvalley** [JaxsonWang/WP-Editor.md#211]
版本为最新的6.1.1版本。
启用"语法高亮设置"--"自动加载模式"后出现下面的文件404错误：
https://cdn.jsdelivr.net/npm/prismjs@1.15.0/components/prism-txt.min.js

**Comment by JaxsonWang** [comment]
并没有txt这个语法，具体支持语言类型请参考[https://prismjs.com/#languages-list](https://prismjs.com/#languages-list)

**Comment by windvalley** [comment]
多谢！

**Comment by xiebruce** [comment]
我也是报这个错，这个报错不能去掉么？另外还有个title的错
<img width="1439" alt="xnip2018-11-10_22-16-29" src="https://user-images.githubusercontent.com/13575500/48302332-472e2000-e536-11e8-929f-5fe9c54da55a.png">
