### ISSUE TITLE
使用插件时候浏览在wordpress展现效果不同

### ISSUE THREAD

**Issue by fanyikoukouchi** [JaxsonWang/WP-Editor.md#212]
在github显示效果并不是高亮显示

**Comment by JaxsonWang** [comment]
具体案例展示？例如文章截图。

**Comment by fanyikoukouchi** [comment]
![](http://ww1.sinaimg.cn/large/006ApRv6ly1fujoft6edhj30th09t74k.jpg)

**Comment by JaxsonWang** [comment]
你确定语法高亮设置开启了？

确定语法声明是`cpp`？

**Comment by JaxsonWang** [comment]
看了下你的博客，有jQuery错误，你到高级设置开启兼容模式看看。

**Comment by fanyikoukouchi** [comment]
以解决，谢谢
