### ISSUE TITLE
启用支持KaTeX科学公式后，代码段会在前端页面出现多行变为1行的情况

### ISSUE THREAD

**Issue by windvalley** [JaxsonWang/WP-Editor.md#213]
如题，感谢。

**Comment by JaxsonWang** [comment]
具体展示？

**Comment by JaxsonWang** [comment]
截图更好

**Comment by windvalley** [comment]
前端页面：
![image](https://user-images.githubusercontent.com/6139938/44517919-7da88b80-a6fb-11e8-8779-a4d8cecda974.png)

后台显示：
![image](https://user-images.githubusercontent.com/6139938/44517995-b2b4de00-a6fb-11e8-89ef-2c0634711645.png)

**Comment by windvalley** [comment]
不启用“支持KaTeX科学公式”这个选型就没问题

**Comment by JaxsonWang** [comment]
插件是最新版的？

**Comment by windvalley** [comment]
是的，6.1.2版本

**Comment by JaxsonWang** [comment]
无法判断问题出处。

请切换默认主题再继续测试是否还出现这样的情况。

**Comment by windvalley** [comment]
经测试，使用默认主题：Twenty Seventeen版本：1.7 ，也是出现相同的问题。

**Comment by JaxsonWang** [comment]
那可能你的代码和插件引起冲突了，可以分享下你的代码？

--------------原始邮件--------------
发件人："WXG "<notifications@github.com>;
发送时间：2018年8月23日(星期四) 晚上6:57
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："淮城一只猫 "<i@iiong.com>;"Comment "<comment@noreply.github.com>;
主题：Re: [JaxsonWang/WP-Editor.md] 启用支持KaTeX科学公式后，代码段会在前端页面出现多行变为1行的情况 (#213)
-----------------------------------

 
经测试，使用默认主题：Twenty Seventeen版本：1.7 ，也是出现相同的问题。

**Comment by windvalley** [comment]
代码有点长，我就不贴了，不过我试出问题的特点了。只要有两个或两个以上变量赋值给变量的情况就会出现这种问题，比如：
foo1=$bar1
foo2=$bar2

**Comment by JaxsonWang** [comment]
又是这个蛋疼的问题。

之前因为这个改了多少次，估计修复比较长。这几天看看怎么弄

**Comment by windvalley** [comment]
好的，辛苦大神

**Comment by JaxsonWang** [comment]
各位大佬走过请顺手解决这个bug吧...实在是没头绪解决》

**Comment by JaxsonWang** [comment]
已解决：https://github.com/JaxsonWang/WP-Editor.md/commit/78f2b59fb8b00b663b4ba42f65114be3998abe23
