### ISSUE TITLE
求助！主题的前台编辑页无法加载编辑器

### ISSUE THREAD

**Issue by MR-zn** [JaxsonWang/WP-Editor.md#217]
我的主题在前台也有新建文章的一个页面，主要是给低权限的用户进行投稿，目前使用过程中碰到了2个问题。

1. 未启用本插件之前，前台编辑器正常可使用。
2. 启用本插件后，后台正常，但前台的编辑器无法正确加载，显示异常，并且无法投稿。
3. 是否有个折中的办法，可能适配我主题的前台编辑器比较麻烦，但是本插件可以只设置只在后台加载吗？

## **未启用前正常**：
![qq 20180827125939](https://user-images.githubusercontent.com/30922257/44641470-a41b3f00-a9f9-11e8-82ec-9c84912e2d4f.jpg)

## **启用后加载异常、并无法提交文章**
![qq 20180827130015](https://user-images.githubusercontent.com/30922257/44641468-a1b8e500-a9f9-11e8-8d5f-6317c3ec0bee.jpg)

**Comment by JaxsonWang** [comment]
前端用户投稿这个是插件实现的？如果是请分享插件名称我可以去尝试解决你的问题。

**Comment by MR-zn** [comment]
前台的投稿是主题自带的，我给你域名可以吗: http://panmiaorong.top

**Comment by MR-zn** [comment]
前台的投稿是主题自带的，我给你域名可以吗: http://panmiaorong.top

**Comment by MR-zn** [comment]
我已经把管理员账号发送到你的邮箱：i@iiong.com; 或者你注册了之后我给你管理员权限  可以吗

**Comment by JaxsonWang** [comment]
某些主题前端用户展示中心会有文章发布系统，如果按照该插件在前端会出现禁用WP原生编辑器导致无法正常使用。

**Comment by lingjianhao** [comment]
我的主题也出现同样的问题，只要启动这个插件，后台编辑正常使用，前台就出现问题了。我使用的是lensnews主题。插件很好用，可以每次后台编辑文章后都要停用前台用户才能发布文章。希望能修复一下！

如果需要主题用来测试，联系我‘企鹅‘： 321481600 或者email: bharals@163.com

**Comment by JaxsonWang** [comment]
新版本插件(6.1.5)理论上会解决你们这样的情况。如果还出现可以在主题的function.php添加代码：
```php
add_filter('editormd_autoenable', '__return_false');
```

我没有你们主题相关案例 只能等插件推送再做判断。

**Comment by MR-zn** [comment]
我有主题的压缩文件，发送到你邮箱可以吗

**Comment by MR-zn** [comment]
大大，更新了你的插件，开关功能很赞，但是前台目前还是异常，我想了个折中的办法：就是怎么样才能在前台禁用编辑器，只在后台启用markdown

**Comment by JaxsonWang** [comment]
@MR-zn 可以提供下主题？保证不外泄，测试完毕就删除。

**Comment by JaxsonWang** [comment]
@MR-zn 直接发到i@iiong.com邮箱即可。
