### ISSUE TITLE
这个插件貌似会屏蔽到主题的一些JS

### ISSUE THREAD

**Issue by nonozone** [JaxsonWang/WP-Editor.md#218]
我的一个模版，使用了这个插件之后，前台的 一些js无法运行，有点兼容性问题。

**Comment by JaxsonWang** [comment]
开启兼容模式，在高级设置里。

--------------原始邮件--------------
发件人："nonozone "<notifications@github.com>;
发送时间：2018年8月28日(星期二) 晚上10:33
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[JaxsonWang/WP-Editor.md] 这个插件貌似会屏蔽到主题的一些JS (#218)
-----------------------------------

 
我的一个模版，使用了这个插件之后，前台的 一些js无法运行，有点兼容性问题。

**Comment by nonozone** [comment]
还有一个问题希望能解决下，比如标题的时候 ## 我们后面一般直接接文字，但是这样的话，在wp-editor里并不会生效，需要在后面加一个空格才可以。希望可以改善下。

**Comment by JaxsonWang** [comment]
插件语法遵循标准markdown语法，事实上你说的那个并不标准的。再说现在很多markdown工具基本都是空格生效。所以没必要做什么改善。
