### ISSUE TITLE
麻烦问一下，如何插入空行

### ISSUE THREAD

**Issue by magicdmer** [JaxsonWang/WP-Editor.md#220]
请问如何插入空行，我使用br标签还有结尾加两个空字符都没有效果

**Comment by JaxsonWang** [comment]
![image](https://user-images.githubusercontent.com/16836692/44919989-6576e300-ad71-11e8-9830-a7b20c77f7a5.png)
![image](https://user-images.githubusercontent.com/16836692/44919995-6871d380-ad71-11e8-90d9-ca65a074bd42.png)
![image](https://user-images.githubusercontent.com/16836692/44920005-7162a500-ad71-11e8-82eb-373bc02259c3.png)
确保勾选了？
