### ISSUE TITLE
可以更改编辑器里markdown预览的css吗？

### ISSUE THREAD

**Issue by Skywt2003** [JaxsonWang/WP-Editor.md#224]
后端编辑器里，markdown实时预览的css实在是太丑了（包括linux下，编辑器里，字体会使用非等宽的字体，代码看起来很难受……），插件目录里没找到css文件，可以自定义预览的css或者直接调用博客的css吗？

**Comment by JaxsonWang** [comment]
有条件可以自己修改代码或者PR: https://github.com/JaxsonWang/Editormd
