### ISSUE TITLE
关于使用ninja form等插件的问题

### ISSUE THREAD

**Issue by haoasdasdf** [JaxsonWang/WP-Editor.md#226]
你好，我在使用自带editor的时候，

在页面插入form的话直接写入例如“[ninja_form id=1]”就可以了

在使用本editor后，输入以上后不显示form。

由於我对markdown记法不是很熟，所以想请问该如何插入以上form？

谢谢

**Comment by JaxsonWang** [comment]
“[ninja_form id=1]”这个看起来是WP的短代码，理论上用WP Editor.md插入短代码是不受影响的。

请确定是安装WP Editor.md插件出现你说的情况？

**Comment by JaxsonWang** [comment]
的确出现你说的情况。不过这个很好解决，去wp-editor.md设置-高级设置：将“兼容模式”打上勾即可使用。

**Comment by haoasdasdf** [comment]
谢谢你！开启兼容模式后果然好了！
