### ISSUE TITLE
WP-Editor.md使用注意事项

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WP-Editor.md#229]
### KaTeX注意事项：

`$ s > 1 $` => 单行公式
`$$ S > 1 $$` => 多行公式
代码块公式(```katex/latex/math)不再受支持！

公式字体大小：https://github.com/JaxsonWang/WP-Editor.md/issues/228

有条件请使用[Wp-HyperMD](https://github.com/JaxsonWang/Wp-HyperMD)
WP-Editor.md未来只维护性更新

**Comment by Skywt2003** [comment]
已发布文章都会受到影响吗？

**Comment by JaxsonWang** [comment]
@Skywt2003 具体是什么使用WP Hypermd？还是公式？如果是插件是不受影响的，公式是会受到影响的。

**Comment by Skywt2003** [comment]
我的公式……把$$当成行内公式用，而且很多很多都是用math代码块写的……

**Comment by Skywt2003** [comment]
有什么解决方案吗……
