### ISSUE TITLE
前端显示应该怎么设置

### ISSUE THREAD

**Issue by yulinyige** [JaxsonWang/WP-Editor.MD#23]
我在后台安装了 WP-Editor.MD 插件, 在后台写文章非常完美, 就是我想要的效果.
但是在前台显示文章就出现各种乱七八糟的格式, 于是, 下载了 pris,引入, 只有一部分格式完整, 另外一部分出错.
控制台错误消息:

`prism.js:38 Uncaught TypeError: Cannot set property 'tab' of undefined
    at prism.js:38
    at Object.run (prism.js:2)
    at Object.highlightElement (prism.js:2)
    at HTMLDocument.highlightAll (prism.js:2)`

请问, 怎么完整引入整个前端呢 ?

**Comment by JaxsonWang** [comment]
这个应该是插件受到你前端主题（或者其他插件）的影响吧？
需要排除下干扰因素：
尝试切换默认主题，停用其他插件，看看是否正常
