### ISSUE TITLE
Disable Markdown Editor

### ISSUE THREAD

**Issue by kayvanaarssen** [JaxsonWang/WP-Editor.md#231]
Hi,

We also use Visual Composer for our website and Markdown.
It would be nice to have an option on the page to disable the Markdown Editor in elements. So that we can enable it on elements that we want it on and disable it on others where we want to have normal text etc.

Would you make that possible.

**Comment by JaxsonWang** [comment]
Sorry, we don't know what Visual Composer is in the Chinese environment. 
Please elaborate on the problems you have encountered and see what I can do for you?

**Comment by kayvanaarssen** [comment]
Hi,
See: https://visualcomposer.io
Its an visual page editor.
It would be nice if we can switch between Markdown and Visual Composer and if we can use the markdown editor in a normal text element in visual composer.

**Comment by kayvanaarssen** [comment]
Yes I want to be able to use the WP Markdown.md module in Visual Composer either as an element or as normal option.
But the default Wordpress Editor now gets completely disabled. I get the point why. But it would be really nice to have an option, to enable it.
Visual Composer does the same thing if you install it you can see it.
Also here in a screenshot:

<img width="444" alt="schermafbeelding 2018-09-11 om 13 28 20" src="https://user-images.githubusercontent.com/672841/45357453-90a9cf80-b5c6-11e8-8776-1f4e8dc796d4.png">

**Comment by JaxsonWang** [comment]
Ok, I see. Although this is not a bug, I need time to solve him. It is expected that the effect will be seen in the next version.

My current idea is similar to the picture:
![image](https://user-images.githubusercontent.com/16836692/45357881-480c0980-b5fa-11e8-995d-50bfc001a5ac.png)

Do you think so?

**Comment by kayvanaarssen** [comment]
Yeah that would be awesome.
Also Visual Composer is extendable. Contact Form 7 and Gravity Forms also do that.
Then you get an extra Element in Visual Composer to use functions of the plugin.
That would be awesome for WP Markdown.MD to also have.

And also make the Toggle button available in the Text Editor like I showed you with Visual Composer.
So we can at least start using Visual Composer on different KB posts.

ideal world would be that we can make quick KB things in Markdown (Full Markdown) and more Client related documentation etc. in Visual Composer with Markdown elements so that we can give some more Layout / default style options to it so that it's more clear.

Now that is not possible since your plugin completely blocks the default WP editor ;) 

Thanks for the quick response anyway.

**Comment by JaxsonWang** [comment]
@kayvanaarssen 
What do you think of this effect? Does it suit your appetite?
![ezgif-3-c3345b2b67](https://user-images.githubusercontent.com/16836692/45592377-675dba80-b99d-11e8-9552-47aa12481c3a.gif)

**Comment by kayvanaarssen** [comment]
@JaxsonWang Something like that would be awesome.
If you can integrate WP Editor.MD also in Visual Composer as a block or in the text element, than it would even be more awesome! Love you see that.

This is allready a big step forward.
