### ISSUE TITLE
希望能够配置静态资源的前缀域名

### ISSUE THREAD

**Issue by sharpbai** [JaxsonWang/WP-Editor.md#233]
目前为了大多数用户方便，静态资源都走的是`cdn.jsdelivr.net`，而且不可配置。希望能够配置成自定义域名。因为公共CDN的可达性和信息泄漏是不愿意接受的。

**Comment by sharpbai** [comment]
我想了下应当叫做把资源内嵌化比较合适。因为大多数场景下，使用博客本身的域名即可。但是针对部分有自定义域名需求的用户，使用自定义域名(CDN)才有需求。

感觉可以把使用到的资源打包到`wp-content/plugins/WP-Editor/`下面，像其他插件一样。这样一来，对于普通人可以选择低成本的安全(博客域名)或低成本的快速(使用公用CDN)。对于有进一步需求的用户，可以使用任意的插件(比如某些CDN化静态资源的插件)，把资源域名替换成自定义的域名(如自己的CDN域名)。

我现在暂时的做法是每次更新后，批量的把`cdn.jsdelivr.net`的字样全部替换成我个人的CDN域名。然后访问CDN域名会回源到WP博客的域名，然后WP博客这边nginx会做匹配把`/wp`和`/npm`的请求都用`proxy_pass`转发到`cdn.jsdelivr.net`。如[这篇文章](https://blog.sharpbai.com/2018/09/%E8%A7%A3%E5%86%B3nginx%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86cdn-jsdelivr-net%E5%A4%B1%E8%B4%A5%E9%97%AE%E9%A2%98/)所示。

**Comment by JaxsonWang** [comment]
插件离线资源大概20M，在wp仓库服务器网络对国内是不友好的。所以我打算提供资源包下载地址，用户自己上传到服务器或者CDN是自己的事情，只需要填入地址即可。

**Comment by sharpbai** [comment]
嗯嗯，这样操作可以，大家都比较方便

**Comment by JaxsonWang** [comment]
功能已实现：https://github.com/JaxsonWang/WP-Editor.md/commit/202f61273bc4b66fc9513672e898f7dd490373be

**Comment by sharpbai** [comment]
测试可用~感谢~
