### ISSUE TITLE
当使用```包围代码块时，第一行会多一个空格

### ISSUE THREAD

**Issue by Chlience** [JaxsonWang/WP-Editor.md#234]

**Comment by JaxsonWang** [comment]
我这本地没有这个问题。
目前猜测是你主题CSS样式导致的。

**Comment by Chlience** [comment]
![image](https://user-images.githubusercontent.com/22586392/45424076-f29e2e00-b6c7-11e8-974a-e4fdb5da632c.png)

**Comment by Chlience** [comment]
好的，我看看
