### ISSUE TITLE
对-(列表) 解析问题

### ISSUE THREAD

**Issue by zhangman523** [JaxsonWang/WP-Editor.md#237]
两个以上的- 第二个样式就会换行

**Comment by JaxsonWang** [comment]
参考https://github.com/JaxsonWang/WP-Editor.md/issues/235

本地环境没有问题，请切换默认主题再重试，否则归纳你现在主题有问题。

**Comment by zhangman523** [comment]
@JaxsonWang 发现问题了，两个列表之间不能有空行。多谢回复。我关掉了。
