### ISSUE TITLE
后台写作时第一个字符无法显示

### ISSUE THREAD

**Issue by ncs19960831** [JaxsonWang/WP-Editor.md#238]
> PHP版本 | 7.2.8
PHP运行环境 | fpm-fcgi
浏览器信息 | Mozilla/5.0 (Windows NT 10.0; Win64; x64)   AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
WordPress版本 | 4.9.8
插件版本 | 6.1.4
jQuery版本 | 1.12.4
当前用户权限 | administrator
---
此为部分Log，此插件版本出现后台写作时第一个字符无法显示的问题，使用F12调试更改布局参数暂时规避。因为本人不懂php，所以请大佬找找原因，现在在
> div class="CodeMirror-sizer" style="margin-left: 20px; margin-bottom: -7px; border-right-width: 23px; min-height: 74px; padding-right: 0px; padding-bottom: 0px;"

这个标签里面的margin-left改为20可以接受（默认0px），但是可能根本原因不在这里，但是我也没有办法找到原因。

**Comment by JaxsonWang** [comment]
屏幕分辨率？

**Comment by ncs19960831** [comment]
1600*900

**Comment by JaxsonWang** [comment]
这分辨率的确有显示问题，下个版本修复该问题。
请耐心等待。
