### ISSUE TITLE
文章内超链接设置target属性

### ISSUE THREAD

**Issue by potoo0** [JaxsonWang/WP-Editor.md#239]
可以添加一个功能来设置超链接是新标签页打开吗？我写的文章，内部附的超链接都是当前标签页打开，有些麻烦

**Comment by JaxsonWang** [comment]
好的，这个功能尽量下个版本添加。

**Comment by potoo0** [comment]
哇！太好啦。谢谢。

**Comment by JaxsonWang** [comment]
[该功能已实现，请耐心等待下一版本更新](https://github.com/JaxsonWang/Editormd/commit/598483a65b742f106b7f805e70138335c23f1fa1)
