### ISSUE TITLE
jQuery问题

### ISSUE THREAD

**Issue by Zxilly** [JaxsonWang/WP-Editor.md#240]
会使部分使用jQuery的插件报错，类似 
```
 $ is not a funtion
```

比如 **AMP For WP**  的后台界面
开启兼容模式无用

**Comment by Zxilly** [comment]
同时希望能在release中提供latest的插件包，本地没有composer环境

**Comment by JaxsonWang** [comment]
Accelerated Mobile Pages插件在WP Editor.md 6.1.4测试没有问题。
后台我是直接调用wp jquery 不存在你说这个问题。
排查下你的环境。
