### ISSUE TITLE
Version 6.1.5 切换编辑器已知BUG

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WP-Editor.md#241]
如果文章包含`\`符号切换编辑器则会丢失。特别是公式一类。

以下并非BUG：

Q：打开历史文章，进入编辑器发现文章数据变成html数据？
A：这个主要是历史文章没有编辑器切换状态值，没有状态值就默认显示html数据。所以你需要在右边点击编辑器切换一次就正常了。（但这样会导致markdown风格异变，参考：https://github.com/JaxsonWang/WP-Editor.md/issues/246）

Q：前端文章数据变成markdown文章数据，没有解析怎么办？
A：请参考：https://github.com/JaxsonWang/WP-Editor.md/issues/247 我提供的截图。主要是“撰写 - markdown”选项需要打开。

**Comment by qiujiangkun** [comment]
按照你的做法，全都无效。
后端的```在前端会解析成''`。
前端#不能正常解析。
后端编辑器现实的并非最新版本。
并且不时会导致整个站点打不开
