### ISSUE TITLE
6.15升级后 编辑器无法

### ISSUE THREAD

**Issue by AlanWeekend** [JaxsonWang/WP-Editor.md#242]
点击启用 无效，已经在插件中心启用插件了，6.14之前的版本正常
![tim 20180918102830](https://user-images.githubusercontent.com/24834613/45660892-9d31a900-bb2d-11e8-8229-7b11760335ff.png)

**Comment by JaxsonWang** [comment]
把
![image](https://user-images.githubusercontent.com/16836692/45660931-c4887600-bb2d-11e8-980f-030a6581d34f.png)勾去掉重试

**Comment by AlanWeekend** [comment]
取消勾选后，只出现默认的可视化编辑器，Markdown编辑器还是无法启用。
![tim 20180918102830](https://user-images.githubusercontent.com/24834613/45661175-e2a2a600-bb2e-11e8-8c78-b69eef968508.png)
但是，同时安装Markdown Editor插件，两个插件同时启用，WP Editor.md可以显示
![tim 20180918102830](https://user-images.githubusercontent.com/24834613/45661231-1f6e9d00-bb2f-11e8-9c29-1c6e72c5cd0a.png)

**Comment by AlanWeekend** [comment]
补图
![2](https://user-images.githubusercontent.com/24834613/45661263-4f1da500-bb2f-11e8-8e26-f6d35d9f681a.png)
![tim 20180918102830](https://user-images.githubusercontent.com/24834613/45661265-52189580-bb2f-11e8-9b02-a1d8eec63132.png)

**Comment by JaxsonWang** [comment]
请不要安装其它markdown插件。
请尝试写入标题再切换是否管用，如果还不管用的话请尝试打开历史文章是否还是以markdown编辑器显示。

**Comment by AlanWeekend** [comment]
写入标题后再点击启用可以了，谢谢~

**Comment by JaxsonWang** [comment]
好的 下次我在文档重点说明这一点。要不然更多人以为是插件问题。

**Comment by lingjianhao** [comment]
![](https://ws1.sinaimg.cn/large/007cqnI0gy1fvdhzipezpj31aj0p9wfg.jpg)

升级后虽然可以用，但是总是提示“插件资源包已损坏，请在下面提示链接中重新下载！”

**Comment by JaxsonWang** [comment]
@lingjianhao 请到编辑器设置 - 编辑器静态资源地址填入`https://cdn.jsdelivr.net/wp/wp-editormd/tags/6.1.5`再保存。

![image](https://user-images.githubusercontent.com/16836692/45661479-4e394300-bb30-11e8-9985-b70689301eb1.png)
如果你需要自定义请按照提示来做。
