### ISSUE TITLE
自定义编辑器静态资源地址功能资源状态检测错误

### ISSUE THREAD

**Issue by sharpbai** [JaxsonWang/WP-Editor.md#243]
如图所示, 实际我的资源已经生效并且下载了最新资源，实际提示为已经过期
![image](https://user-images.githubusercontent.com/3499990/45662916-79269580-bb36-11e8-868a-38db79a85e7b.png)

**Comment by JaxsonWang** [comment]
- 请不要删除资源包任意文件
- 请确定你的地址是正确的。例如`你的“编辑器静态资源地址” + /assets/version.json` 的地址可以打开的：
  https://cdn.jsdelivr.net/wp/wp-editormd/tags/6.1.5//assets/version.json
