### ISSUE TITLE
文章由默认编辑器切换为 WP-Editor.md 编辑器后 Markdown 解析失效

### ISSUE THREAD

**Issue by Skywt2003** [JaxsonWang/WP-Editor.md#245]
同学的网站也遇到了一样的问题，即文章由 wordpress 默认编辑器切换为 WP-Editor.md 编辑器后 Markdown 解析失效。
文章实时预览没有问题，但是发布后或者预览文章，就会发现 Markdown 解析失效。例如这个预览页面：
[https://skywt.cn/?p=1697&preview=true](https://skywt.cn/?p=1697&preview=true)

原来应该被解析为 h1、h2 等等的 ’#‘ 都没法被解析……

**Comment by Skywt2003** [comment]
wordpress怎么退回以前版本的插件

**Comment by markofrain** [comment]
对啊，怎么回退，不太了解

**Comment by markofrain** [comment]
此处没有旧版本https://wordpress.org/plugins/wp-editormd/advanced/

**Comment by Skywt2003** [comment]
是的，所以用 Rollback 插件也不能回滚……

**Comment by markofrain** [comment]
@Skywt2003 如果你使用云服务器或主机的话，可以先从备份上拿下来

**Comment by JaxsonWang** [comment]
@markofrain 
@Skywt2003 
搞错了，这不是bug，你们都少了一个选项。具体参考：https://github.com/JaxsonWang/WP-Editor.md/issues/247

撰写 - markdown 打上勾，否则会失效。

**Comment by qiujiangkun** [comment]
无效
![image](https://user-images.githubusercontent.com/33482468/45692188-c6355680-bb8c-11e8-879c-95845059eb4c.png)
![image](https://user-images.githubusercontent.com/33482468/45692212-d2b9af00-bb8c-11e8-975d-010042c4665b.png)
![image](https://user-images.githubusercontent.com/33482468/45692246-e402bb80-bb8c-11e8-9155-6e747118a0c0.png)

**Comment by qiujiangkun** [comment]
问题出现于更新md插件后

**Comment by JaxsonWang** [comment]
@qiujiangkun 请重新更新一次文章再看看？

**Comment by qiujiangkun** [comment]
无效，而且更新文章后，后台又退回去了，前台正常显示，但是没有md语法
