### ISSUE TITLE
WP-Editor更新后Markdown解析失效

### ISSUE THREAD

**Issue by CaptainSlowWZY** [JaxsonWang/WP-Editor.md#246]
我更新之后新写的文章全都解析失效了。
就是更新之后贴上去的，然后以前的文章更改后更新也会解析失效。
网页上显示出来的是Markdown源码，但是后台预览是正常的。
然后以前的文章点进去变成了html。
还有markdown斜体的**会被解析成__，例如：
源码：
*abcd*
显示效果：
_abcd_（后台预览也是这样子的）

**Comment by Skywt2003** [comment]
同，'*'符号会被解析成下划线'_'

**Comment by JaxsonWang** [comment]
@CaptainSlowWZY 
@Skywt2003
这个应该是php解析风格问题，6.1.5上架太仓促了。没来得及弄，可以的话我下个版本调整下风格吧。

**Comment by Skywt2003** [comment]
有什么暂时的使用斜体的解决方法吗？

**Comment by qiujiangkun** [comment]
md全部失效，代码无法正常显示。后台预览确实可以的。
而且后台编辑器不显示最新版本
