### ISSUE TITLE
Image Drag and Drop not working as it should

### ISSUE THREAD

**Issue by kayvanaarssen** [JaxsonWang/WP-Editor.md#248]
Hi,

When we drag and drop an image. It will upload but not placed in the editor with the correct code.
I now need to manually copy the image location and click on the image icon or write the markdown.
Thats double work ofcourse.

Here is a Clip that shows you what happens.

![example of image upload-1 1](https://user-images.githubusercontent.com/672841/45673782-e97be980-bb2b-11e8-981a-478e9b021ddb.gif)

**Comment by JaxsonWang** [comment]
Oh, there is indeed this problem in Visual Composer.
I will solve it!

**Comment by kayvanaarssen** [comment]
You are awesome.
In the meantime, maybe you can check how the plugin system of Visual Composer works. 
And build a Markdown section.
So that we can use the Markdown Editor as a Building block if that's possible.

That would be really awesome.

Also for other people that want to give there KB a bit bit style and work with layouts and templates that's what Visual Composer is really good at.
