### ISSUE TITLE
更新最新的安装包 出现markdown 语法不支持

### ISSUE THREAD

**Issue by lovezeropython** [JaxsonWang/WP-Editor.md#251]
![image](https://user-images.githubusercontent.com/35518020/45726482-0844b380-bbf2-11e8-8ec8-4f71d23a1f3a.png)

**Comment by JaxsonWang** [comment]
以下并非BUG：

Q：打开历史文章，进入编辑器发现文章数据变成html数据？
A：这个主要是历史文章没有编辑器切换状态值，没有状态值就默认显示html数据。所以你需要在右边点击编辑器切换一次就正常了。（但这样会导致markdown风格异变，参考：https://github.com/JaxsonWang/WP-Editor.md/issues/246）

Q：前端文章数据变成markdown文章数据，没有解析怎么办？
A：请参考：https://github.com/JaxsonWang/WP-Editor.md/issues/247 我提供的截图。主要是“撰写 - markdown”选项需要打开。
