### ISSUE TITLE
6.1.5版本编辑器加载不出来

### ISSUE THREAD

**Issue by Ice-Hazymoon** [JaxsonWang/WP-Editor.md#253]
版本：6.1.5
wordpress版本：4.9.8
写文章时编辑器加载不出来，右侧“发布”工具栏里有一个启用 WP Editor.md 的选项，点了好几遍状态都没变化

上一个版本貌似没有这个问题

**Comment by JaxsonWang** [comment]
如果**标题**和**正文**没有内容的话，就会出现你这样的情况。想切换请填充标题内容。

**Comment by Ice-Hazymoon** [comment]
找到原因了，“Settings-->撰写-->启用markdown” 选项开启以后就好了，但上一个版本却不需要手动启用，更新日志里也没有对应的提示
