### ISSUE TITLE
升级最新版本后提示插件被禁用，插件文件不存在。

### ISSUE THREAD

**Issue by AragonSnow** [JaxsonWang/WP-Editor.md#254]
![image](https://user-images.githubusercontent.com/22835918/45800285-073f7f00-bce3-11e8-8b7a-3f94cad6bf81.png)

**Comment by JaxsonWang** [comment]
删除插件重新安装就行了，估计wp-editor.md文件不存在了

**Comment by AragonSnow** [comment]
> 删除插件重新安装就行了，估计wp-editor.md文件不存在了

![image](https://user-images.githubusercontent.com/22835918/45800711-56d27a80-bce4-11e8-8bc8-cecafa92fdc3.png)
在线重新安装后提示这个，并且后台打开的速度极慢。卡了一分钟才加载出来，停用插件后正常

**Comment by JaxsonWang** [comment]
插件设置 - 编辑器设置 - 编辑器静态资源地址中的值删除直接保存即可或者填入：“https://cdn.jsdelivr.net/wp/wp-editormd/tags/6.1.6”

如果你需要自定义地址请根据提示来设定。

**Comment by AragonSnow** [comment]
> 插件设置 - 编辑器设置 - 编辑器静态资源地址中的值删除直接保存即可或者填入：“[https://cdn.jsdelivr.net/wp/wp-editormd/tags/6.1.6”](https://cdn.jsdelivr.net/wp/wp-editormd/tags/6.1.6%E2%80%9D)
> 
> 如果你需要自定义地址请根据提示来设定。

默认就是这个设置，删除保存也没有效果，启用依然提示资源包已损坏

**Comment by JaxsonWang** [comment]
本地环境和绝大部分人都没有问题。不清楚你这是什么情况。如果有问题可以降级到6.1.4版本：https://github.com/JaxsonWang/WP-Editor.md/issues/249
