### ISSUE TITLE
Feature: Visual Composer Element / Plugin Support

### ISSUE THREAD

**Issue by kayvanaarssen** [JaxsonWang/WP-Editor.md#255]
Hi,

You know I allready asked for this in some issues. But i'll create a new "Feature" request for you so its better organised. Since I cannot read the Chinese labels I cannot create the issue in the right place so forgive me.

It would be very nice if you could build an element for visual composer that supports your markdown plugin like we spoke about in previous issues. So that we can use Visual Composer to make the documentation for clients but also add Markdown in it with your plugin in some columns without making the complete page/post markdown.

I know this is something you need to look into but I think its a nice feature to have.

Just let me know if its possible to make.

**Comment by JaxsonWang** [comment]
Yes, I do have an idea. This may require the user to fill in the element implementation. I try to implement it in a future version.

I think you may need to pay attention to: https://github.com/JaxsonWang/WP-Editor.md/wiki/06.-Multi-User-Blogs---%E5%A4%9A%E7%94%A8%E6%88%B7%E5%8D%9A%E5%AE%A2
