### ISSUE TITLE
更新到最新版后拖拽插入图片到文章有bug

### ISSUE THREAD

**Issue by tangino** [JaxsonWang/WP-Editor.md#258]
拖拽插入图片到文章，发布后图片信息显示会有点问题，不支持[caption]标签，
![snipaste_2018-09-21_14-01-42](https://user-images.githubusercontent.com/10190644/45863052-0708b780-bda7-11e8-8f21-c870f6e0cc22.png)
![snipaste_2018-09-21_14-02-31](https://user-images.githubusercontent.com/10190644/45863053-0708b780-bda7-11e8-875d-9ccb23a886fc.png)

好像是转义字符造成的问题。

**Comment by JaxsonWang** [comment]
不清楚caption是什么情况，我这测试插入图片直接标准markdown图片展示。
