### ISSUE TITLE
服务器在德国，问题有关代码和Katex

### ISSUE THREAD

**Issue by i-Yirannn** [JaxsonWang/WP-Editor.md#259]
1） Katex 可以正常识别 $$ 但是解析不正常，就是它会隐藏掉 $$ 并且 $$内的字体会出现变化，但不会被解析。
2） 之前下了一个 Cyaron 来显示代码，曾经把WP-Editor的代码显示关掉了，发现Cyaron显示不正常，卸载之后，把WP-Editor的代码显示打开，但是这时候却不能正常显示代码了

**Comment by JaxsonWang** [comment]
1. https://github.com/JaxsonWang/WP-Editor.md/wiki/03.-KaTeX-Document

2. 代码块设置开启并确保代码块写作是正确的：
例如：
```
    ```javascript
        console.log("hello world")
    ```
```

请注意它的声明语法类型。

**Comment by i-Yirannn** [comment]
1. 我的文章是一直没有变的 曾经使用您的 Editor 正常渲染过
2. 谢谢～

**Comment by i-Yirannn** [comment]
v6.1.6切换编辑器请慎重使用 这个是什么？

**Comment by i-Yirannn** [comment]
有关 Latex 炸的情况， 参见 [链接](https://yirannn.com/original/noip_2016/2/)
有关代码块炸的情况， 参见 [链接](https://yirannn.com/algorithm/search/bzoj_1330/)

**Comment by i-Yirannn** [comment]
再次感谢您的付出，用爱发电的人是伟大的，虽然我暂时无法资瓷。。

**Comment by i-Yirannn** [comment]
v6.1.6切换编辑器请慎重使用 这个是什么？ 哦，我看到了这个，谢谢，我去找个以前版本试试

**Comment by i-Yirannn** [comment]
我的设置和您的一样，我甚至尝试了重新安装，但是都没有效果，这和我的服务器位置有关么

**Comment by i-Yirannn** [comment]
更换自定义主题CSS时，字体的更换是正常的，但是高亮仍然没有
至于KaTex， 我已经回滚到6 1 4 但是还是无法正常渲染，尬

**Comment by i-Yirannn** [comment]
<img width="897" alt="default" src="https://user-images.githubusercontent.com/42791146/45874190-d2a4f380-bdc6-11e8-8905-5bb03aaa928a.png">
<img width="619" alt="default" src="https://user-images.githubusercontent.com/42791146/45874197-d6387a80-bdc6-11e8-8bcc-f0ca18c4aebb.png">
<img width="619" alt="default" src="https://user-images.githubusercontent.com/42791146/45874197-d6387a80-bdc6-11e8-8bcc-f0ca18c4aebb.png">
<img width="347" alt="default" src="https://user-images.githubusercontent.com/42791146/45874200-d89ad480-bdc6-11e8-8b38-e324a43062df.png">
<img width="897" alt="default" src="https://user-images.githubusercontent.com/42791146/45874190-d2a4f380-bdc6-11e8-8905-5bb03aaa928a.png">

**Comment by i-Yirannn** [comment]
哦抱歉，图片重复上传了
<img width="691" alt="2018-09-21 5 48 18" src="https://user-images.githubusercontent.com/42791146/45874309-1ac41600-bdc7-11e8-9f0a-dcb12f5c71ff.png">
