### ISSUE TITLE
最新的6.1.4~6.1.6版本因为不兼容旧版公式令我很头疼（最新版还有两个BUG）

### ISSUE THREAD

**Issue by lyy289065406** [JaxsonWang/WP-Editor.md#261]
这是一个很好的插件，我站点所有文章都是用这个插件去编辑的，
但是最近几个版本更新动作太大，尤其是**不兼容旧版格式，建议作者还是打分支**的好，我的站点有不少文章写了了大量公式，升级后都要重新排版。

--------

6.1.4 版本尚好，只是增加了行内公式的识别，批量把 $$ 改成 $ 就可以解决了，但是还是不得不重新审查所有相关文章是否有解析公式失效的情况。

6.1.5 版本并无特殊影响就略过了，

6.1.6 版本问题较大（markdown变成默认不开启就很郁闷，开关找了半天）
最可怕的是它直接把文章的特殊字符做了转义处理存储，使得【预览】功能完全失效，变成一坨无格式可言的文本。
而且这个举动连latex公式也受到影响的，例如公式定义了一个变量有 下划线，升级到这个版本后，markdown会自动在下划线前面加反斜杠做转义，而这么一来，公式就把这个转义后的下划线及其后一个字母解析成了下标，例如 $VAR_CONST$ 在显示的时候， “C”变成了下标。

--------

希望作者可以重视一下兼容性问题，或者是否能在设置加开关控制。
新站点或许没什么感觉，但是如果站点内容很多的时候，我现在升级就不得不谨慎了，因为每次升级都要重新审查所有历史文章，这是很可怕的事情。

**Comment by JaxsonWang** [comment]
下划线那个最近一直在寻找好的方案。如果有可能的可以使用老版本。当然新版会取消编辑器切换这块功能。
[WP-Editor.md-v6.1.7-Beta3.zip](https://github.com/JaxsonWang/WP-Editor.md/files/2408367/WP-Editor.md-v6.1.7-Beta3.zip)

**Comment by LittleJianCH** [comment]
我目前使用旧版中不能输入 $$<$$ ，如果解决？
