### ISSUE TITLE
6.1.6新BUG：使用MD写的文章，重新编辑后变成html了

### ISSUE THREAD

**Issue by lyy289065406** [JaxsonWang/WP-Editor.md#262]
这个版本升级后真的很郁闷，原本只有那些latex公式的文章有牵连，现在这么一来，所有文章都收到牵连了

**Comment by lyy289065406** [comment]
文章每次编辑后，都会在上次转义的基础上重新转义，这么搞的话都不敢随便编辑文章了，最坏的情况是要还原数据库。 后悔没有备份旧版的MD插件，这个版本6.1.6问题太多了。

还有个问题就是，编辑文章的时候，下面【启用】MD，编辑框反而变成传统风格，但是内容却是MD格式。而【禁用】MD，编辑框则变成MD风格，但是内容却是HTML，而且反复这么几次，文章内容就会不断重复转义，变得乱七八糟

**Comment by JaxsonWang** [comment]
下划线那个最近一直在寻找好的方案。如果有可能的可以使用老版本。当然新版会取消编辑器切换这块功能。
[WP-Editor.md-v6.1.7-Beta3.zip](https://github.com/JaxsonWang/WP-Editor.md/files/2408367/WP-Editor.md-v6.1.7-Beta3.zip)
