### ISSUE TITLE
链接中间带空格无法识别

### ISSUE THREAD

**Issue by aippcoder** [JaxsonWang/WP-Editor.md#266]
例如：[putExtra()](https://developer.android.com/reference/android/content/Intent.html#putExtra(java.lang.String, android.os.Bundle))，在java.lang.String,后有个空格，但是添加之后就无法识别为链接了

**Comment by JaxsonWang** [comment]
本插件依赖`marked.js`项目，请到：[https://marked.js.org/demo](https://marked.js.org/demo)检验是否有问题，如果有问题请到https://github.com/markedjs/marked/issues提交你所遇到的问题！

PS：你这个的确是Marked.js问题，不过他们处理效率不是很快。同样我也不可以修复内核问题，不然以后内核文件无法升级。
