### ISSUE TITLE
更新至最新版加载js失败，导致编辑器打不开

### ISSUE THREAD

**Issue by duwenfei** [JaxsonWang/WP-Editor.md#268]
GET https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.1/assets/Editormd/lib/mindMap.min.js 404 ()

Refused to execute script from 'https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.1/assets/Editormd/lib/mindMap.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by JaxsonWang** [comment]
You should change mindmap addres: `https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.1/assets/MindMap/mindMap.min.js`
