### ISSUE TITLE
最近一次升级后无法实时预览

### ISSUE THREAD

**Issue by malphitee** [JaxsonWang/WP-Editor.MD#27]
如题，升级到2.5版本之后，实时预览功能似乎没有生效，之前是好的，现在只能手动关闭再打开实时预览才能看到效果，已安装的插件有：
Crayon Syntax Highlighter(未启用)
Jetpack
WPJAM BASIC
WPJAM 七牛镜像存储
Akismet Anti-Spam(未启用)

其中jetpack没有开启自带的markdown功能

请问应该如何解决无法实时预览的问题？

**Comment by JaxsonWang** [comment]
首先你得需要在设置将选项`关闭同步滚动`关闭，开启是不支持同步预览的，这个编辑器本身就这样设计的

**Comment by malphitee** [comment]
好的，已经改过来了，多谢多谢，回复好及时：）
