### ISSUE TITLE
哪里可以下载打包的配套静态资源？

### ISSUE THREAD

**Issue by chenfanyue** [JaxsonWang/WP-Editor.md#270]
在插件的设置页面看到这样一段文字：

> 请确保编辑器静态资源为最新版，否则会出现一些莫名其妙的问题
请把资源（解压文件夹为assets）上传到你的服务器或者cdn，如果你的资源地址是：“http(s)://example.com/myfile/assets”，那么应该填入：“http(s)://example.com/myfile”。
状态：资源为最新版！

我想把包含着歌assets的资源包下载然后解压到国内的cdn，那么在哪里可以下载呢？

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/releases
