### ISSUE TITLE
标题总是被转移成html语言代码

### ISSUE THREAD

**Issue by JasonAn** [JaxsonWang/WP-Editor.md#271]
如果我使用markdown添加标题, (比如## 二级标题, ### 三级标题), 总是会转译成\<h2>\<h3>, 其他则不会被转译, 比如添加code, latex等等. 请问这是为什么呢? 有什么办法避免么

比如说
<img width="487" alt="image" src="https://user-images.githubusercontent.com/4537312/47413386-ff7c5b80-d722-11e8-8060-1c04ba91fc80.png">

**Comment by JaxsonWang** [comment]
这总是个很迷的问题，至今为止也不清楚这是怎么回事，干扰因素很多：

- 请不要使用清理垃圾数据的插件，它总会把Markdown字段数据清理；
- 请不要安装同类插件、例如`WP Markdown`、`WP Jetpack MD`等插件；
- 如果你安装了JetPack插件，请确定`Markdown`写作功能选项是**关闭状态**；
- 请不要执行任何奇怪的优化的操作；

诸多原因无法判断，如果你的问题可以复现的话请详细说下过程。

**Comment by JasonAn** [comment]
原始情况:
1. 安装了jetpack 插件, 但是并没有其他清理垃圾数据插件
2. jetpack 插件找那个markdown 功能是打开状态.

尝试1. 试图关闭jetpack markdown 功能, 显示400错误,并无法被关闭
尝试2. 删除jetpack 插件, 转译问题消失

**Comment by JaxsonWang** [comment]
好，之前测试jetpack没问题，估计jetpack又更新改动了什么。晚上回去我在测试看看。尽量兼容jetpack。

你现在可以尝试：
- 先停用wp editor.md插件
- 打开jetpack设置关闭markdown写作选项
- 再启用editor.md插件

如果还不管用请等待我下一步消息或者版本更新。

**Comment by JasonAn** [comment]
开心的是, 这个测试我做过了. 可以在不引发400错误的时候打开editor插件. 不幸的是, 这种情况下, head仍然会被转译, 包括code 和其他, latex 部分却不会. 

不过有一点好奇 HD Editor 和Editor 两个插件. 之后是共同维护么? 还是维护其中一个?

**Comment by JaxsonWang** [comment]
都是一个维护着，我现在想法就是wp-editor.md内核成熟后再移植到Hyper.md上。

**Comment by JasonAn** [comment]
一个? 一直? 

如果能做维护性更新, 就相当不容易了. 考虑donate, 不过发现你的donation 链接自动转成新blog .
