### ISSUE TITLE
Content rendered in rest api is omitted with HTML tags

### ISSUE THREAD

**Issue by vukasin0** [JaxsonWang/WP-Editor.MD#28]
## How to reproduce:
Here is example of MD entered in post:

```
### H2

`
Another (awesome) song by Jamiroquai!
`
```

## Result:
In api response:

**rest_api_response_object**.content.rendered:
```
"<p>### H2</p>↵<p>`<br />↵Another (awesome) song by Jamiroquai!<br />↵`</p>↵"
```

## How it should be:
It should be plain MD text.

**Comment by JaxsonWang** [comment]
You can customize the wp rest api interface and want it to display the markdown text of the article, output to the interface according to the `post_content_filtered` field in the data table `wp_posts`
