### ISSUE TITLE
设置PrismJS Syntax Highlight Style 前台显示正常后台没法看

### ISSUE THREAD

**Issue by xiebruce** [JaxsonWang/WP-Editor.md#280]
<img width="663" alt="xnip2018-11-11_23-31-44" src="https://user-images.githubusercontent.com/13575500/48314871-b2492680-e60a-11e8-9dc6-24827efd6068.png">
<img width="1303" alt="xnip2018-11-11_23-31-16" src="https://user-images.githubusercontent.com/13575500/48314872-b2492680-e60a-11e8-95d6-d554881a6e78.png">

**Comment by xiebruce** [comment]
不止这一种，所有PrismJS Syntax Highlight Style 都这样，试了好多个了

**Comment by JaxsonWang** [comment]
please read prism docments: [Supported languages](https://prismjs.com/#languages-list)

your codes type is `bash`!
