### ISSUE TITLE
Why is the preview effect different from the actual effect?

### ISSUE THREAD

**Issue by jiaolinfeng** [JaxsonWang/WP-Editor.md#285]
I got a problem when using the editor. 

-----
Here is the preview effect, which is also what I want.
![tim 20181204161106](https://user-images.githubusercontent.com/6848131/49427801-43ad5200-f7df-11e8-9147-3b0ce1667062.png)
However, when I publish the article, I met this:
![tim 20181204161121](https://user-images.githubusercontent.com/6848131/49427807-46a84280-f7df-11e8-92dd-683166f93e5c.png)
What causes this problem?
**Thank you for your help and excuse me for any possible offence.**

**Comment by lanyazhizhou** [comment]
me too

**Comment by jiaolinfeng** [comment]
@JaxsonWang Thank you for your attention.
是其他插件或者主题影响了吗？
要不我关掉其他插件或者换一个主题试一试？

**Comment by lanyazhizhou** [comment]
@jiaolinfeng 你的搞好了吗

**Comment by lanyazhizhou** [comment]
不是主题的原因，我换了主题，结果还是不行

**Comment by jiaolinfeng** [comment]
@lanyazhizhou 还没试呢，我博客也就是自己写着玩。忙工作了，还没花时间研究。

**Comment by lanyazhizhou** [comment]
@JaxsonWang 你好，请问这个是bug问题，还是我们自身的主题或者插件影响啊

**Comment by JaxsonWang** [comment]
@jiaolinfeng @lanyazhizhou 昨天我测试 应该是插件markdown内核解析问题。有时间修复这个问题

**Comment by jiaolinfeng** [comment]
@JaxsonWang 好的，谢谢~

**Comment by JaxsonWang** [comment]
@lanyazhizhou @jiaolinfeng 我看了markdown php语法文件，应该是不存在这个问题，只是语法严格：
![image](https://user-images.githubusercontent.com/16836692/49875305-a6e05980-fe5b-11e8-875f-937c5d0863d7.png)
![image](https://user-images.githubusercontent.com/16836692/49875312-ab0c7700-fe5b-11e8-8516-045fce5e67ed.png)

不同语法需要回车空一行才能生效！
