### ISSUE TITLE
更新10.0.2时候折腾出的小东西

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WP-Editor.md#296]
在兼容WP 5.0过程，大致看了下Gutenberg相关开发文档和扩展接口。然后花了一点时间写个小插件：

![qq 20181217014920](https://user-images.githubusercontent.com/16836692/50056923-686dd600-019e-11e9-94d7-d605aa4361cd.png)
![qq 20181217014940](https://user-images.githubusercontent.com/16836692/50056924-686dd600-019e-11e9-83f8-be28e776ac3e.png)

目前开源了：https://github.com/JaxsonWang/WP-Gutenberg.md

不过插件还未完善，有空再继续完善它。

不清楚大家对Gutenberg编辑器怎么看，但目前在wordpress使用第三方编辑器实在是太“危险”了，有条件的尽量还是选择原生编辑器写作吧。

**Comment by yilufengshun** [comment]
我只想说为了兼容md编辑器,我已经滚回4.9版本了....

**Comment by JaxsonWang** [comment]
插件版：
[WP-GMD.zip](https://github.com/JaxsonWang/WP-Editor.md/files/2695264/WP-GMD.zip)
