### ISSUE TITLE
升级到最新版的 WP-Editor.md 后，评论无法加载，只能回到经典版了。

### ISSUE THREAD

**Issue by itpubs** [JaxsonWang/WP-Editor.md#297]
升级到最新版的 WP-Editor.md 后，评论无法加载

<img width="798" alt="geektop 2018-12-17 16-38-47" src="https://user-images.githubusercontent.com/16533962/50075796-d526b600-021a-11e9-85e8-5fdb28bdd26e.png">

一直是 loading 的状态

**Comment by JaxsonWang** [comment]
不建议使用该功能，如果非得用话：

- 设置开启思维导图请切换更换地址：https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.2/assets/MindMap/mindMap.min.js

- 否则F12控制台提交错误信息

**Comment by itpubs** [comment]
好的，升级以后好像代码高亮也无效了

**Comment by JaxsonWang** [comment]
没有参考价值，无法判断原因，请提供有用的信息，例如文章控制台报错信息等

**Comment by itpubs** [comment]
我现在回退到以前的版本了，晚上再研究下新版
BYW: 谢谢
