### ISSUE TITLE
shell脚本无法启用代码高亮

### ISSUE THREAD

**Issue by wiloon** [JaxsonWang/WP-Editor.md#298]
shell脚本在编辑器里代码高亮正常，但是文章发布之后不能代码高亮.

浏览发布之后的文章, chrome控制台显示prism-shell.min.js 加载失败。
请求的URL：https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.2/assets/Prism.js/components/prism-shell.min.js, 返回404.

在编辑器里,请求的是prism.min.js
https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.2/assets/Editormd/lib/prism.min.js
prism.min.js能正常返回

WP-Editor.md版本: 10.0.2 
wordpress 版本: 5.0.1

**Comment by JaxsonWang** [comment]
参考：https://github.com/JaxsonWang/WP-Editor.md/issues/280

**Comment by JaxsonWang** [comment]
参考：https://github.com/JaxsonWang/WP-Editor.md/issues/284
参考：
参考：
参考：

**Comment by JaxsonWang** [comment]
如果是window环境语法是`powershell`并非`shell`。

如果是Linux环境是`bash`并非`shell`。
