### ISSUE TITLE
快速编辑修改发布时间后HTML不能解析为MD

### ISSUE THREAD

**Issue by TechCiel** [JaxsonWang/WP-Editor.MD#3]
RT，做了简单的测试，发现每次通过快速编辑修改发布时间就导致解析失效，加上新的md内容却只有新加部分能解析，再修改一次就又完了。

**Comment by JaxsonWang** [comment]
额，没试过快速编辑，有空看看

发自我的 iPhone

**Comment by JaxsonWang** [comment]
已修复，[详见](https://github.com/JaxsonWang/WP-Editor.MD/commit/007172da666ce39f46e1ebb12c93d9d813a4b7db)
