### ISSUE TITLE
wp 5.0.1

### ISSUE THREAD

**Issue by andrewufrank** [JaxsonWang/WP-Editor.md#300]
the loading scren (rotating blue sticks) do not go away... nothing happens, not usable!
please correct - i have 10.0.3 with wp 5.0.1, which seem not to cooperate!

**Comment by JaxsonWang** [comment]
update to mindmap addres: `https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.3/assets/MindMap/mindMap.min.js`
