### ISSUE TITLE
手贱更新5.0.2 现在卒了  一直转啊转

### ISSUE THREAD

**Issue by ileee** [JaxsonWang/WP-Editor.md#303]

**Comment by ileee** [comment]
https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.2/assets/MindMap/MindMap.min.js 
404

**Comment by JaxsonWang** [comment]
更新地址：https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.2/assets/MindMap/mindMap.min.js
