### ISSUE TITLE
最近几个版本出现编辑器无法加载的问题

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WP-Editor.md#304]
由于历史版本原因，不小心填错mindMap.js地址，你只需要更新下面版本：

mindMap地址：`https://cdn.jsdelivr.net/wp/wp-editormd/tags/{插件版本号}/assets/MindMap/mindMap.min.js`

例如你的插件版本号是10.0.2则是：`https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.2/assets/MindMap/mindMap.min.js`

**Comment by Fisher-Wong** [comment]
谢谢

**Comment by Fisher-Wong** [comment]
作者在这方面考虑的确很周到。把mindmap的地址接口也留出来给用户配置和更新了

**Comment by Thyiad** [comment]
谢谢。
没想到啊没想到，居然会是这个大小写的原因。。

**Comment by DennisCoder1024** [comment]
部署在国外的虚拟机的时候出现编辑器打不开的情况，我修改了mindMap.min.js的地址以后，结果连插件页面都打不开了，只好删了，再次安装也不行。
