### ISSUE TITLE
编辑器预览窗口与实际样式不一致

### ISSUE THREAD

**Issue by buyi998** [JaxsonWang/WP-Editor.md#305]
Wordpress版本: 5.0.2
编辑器： 经典编辑器
插件版本： 10.0.3

后台编辑预览样式和代码如下：
![1](https://user-images.githubusercontent.com/13196831/50428144-c6619280-08ef-11e9-8556-d814986fc778.png)
![2](https://user-images.githubusercontent.com/13196831/50428147-c8c3ec80-08ef-11e9-8a04-0c2c6da772d4.png)

前台样式和代码如下：
![3](https://user-images.githubusercontent.com/13196831/50428148-c9f51980-08ef-11e9-9284-25599c08d3a7.png)
![4](https://user-images.githubusercontent.com/13196831/50428151-ca8db000-08ef-11e9-810f-f80a7537158d.png)

貌似预览解析出来的html与实际发布的html不一致。但预览的样式是正确的。

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/wiki/07.-Code-block-%E4%BB%A3%E7%A0%81%E5%9D%97%E4%BD%BF%E7%94%A8

**Comment by buyi998** [comment]
我的意思是在前端展示的时候`pre`在`li`外面了。

**Comment by JaxsonWang** [comment]
markdown语法不严格，请参考文档学习：https://github.com/JaxsonWang/WP-Editor.md/wiki/02.-Markdown-Document
