### ISSUE TITLE
发布后的代码段宽度很窄，怎么调？

### ISSUE THREAD

**Issue by ljyfree** [JaxsonWang/WP-Editor.md#307]
代码段前后使用```来标识，文章发布出来后显示的有效宽度很窄，请问这个怎么调？
![md](https://user-images.githubusercontent.com/13234976/50470020-02791e00-09ea-11e9-8e93-f84ca82f5a43.png)

**Comment by JaxsonWang** [comment]
该问题和插件无关，插件只负责内容输出，不干预内容修饰。

如需修改请自定义主题样式即可。
