### ISSUE TITLE
WP-Editor.md-Assets-10.0.3.zip内静态资源库的版本依然为10.0.2

### ISSUE THREAD

**Issue by farmerluo** [JaxsonWang/WP-Editor.md#308]
WP-Editor.md-Assets-10.0.3.zip内静态资源库的版本依然为10.0.2，导致后台显示报错：检验到插件资源包已过时，请根据下面提示下载最新资源包。

![default](https://user-images.githubusercontent.com/1650698/50532419-fe690f80-0b53-11e9-9000-679ef04cfa0b.png)

**Comment by JaxsonWang** [comment]
https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.3/assets/version.json

**Comment by JaxsonWang** [comment]
https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.2/assets/version.json
