### ISSUE TITLE
预览时，表格显示正常，发布文章之后，查看文章不正常

### ISSUE THREAD

**Issue by SlowSlicing** [JaxsonWang/WP-Editor.md#309]
预览时，是好看的格式
在真正查看文章是，却不是，像是没有任何修饰、任何边框的表格

**Comment by JaxsonWang** [comment]
和插件无关，检查主题中的表格样式是否俱全，如果没有请联系主题作者完善样式，或者更换主题。

**Comment by SlowSlicing** [comment]
谢谢您的回答 @JaxsonWang
