### ISSUE TITLE
请问这个编辑器支持插入视频吗？

### ISSUE THREAD

**Issue by baiying** [JaxsonWang/WP-Editor.MD#31]
我在文章中使用video标签插入视频，预览是可以识别这个标签的，但是发布后就被过滤掉了，有办法解决吗？

**Comment by JaxsonWang** [comment]
没注意发布被过滤了，下个版本解决。

你可以暂时这样，打开文件https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Jetpack/markdown/xsshtml.class.php#L97

在下面添加：

```
'video'
```

标签即可
