### ISSUE TITLE
建议：粘贴图像的时候生成代码为嵌套格式（带链接的图片格式）

### ISSUE THREAD

**Issue by the-eric-kwok** [JaxsonWang/WP-Editor.md#310]
目前粘贴图像时自动生成的代码是这样的
```
![](http://demo.com/demo.jpg)
```

如果改成这样
```
[![](http://demo.com/demo.jpg)](http://demo.com/demo.jpg)
```
会不会好一些？

这样的话图片本身也是一个超链接，可以点击，起到一个放大的效果。

或者至少，增加一个设置项吧……

**Comment by JaxsonWang** [comment]
如果主题作者添加图片懒加载怎么办？那你说的功能就会让主题的懒加载图片功能毫无意义了。

**Comment by the-eric-kwok** [comment]
我不太清楚图片懒加载和图片超链接之间存在什么冲突关系诶……如果是冲突的，能不能把这个功能做一个设置项，交给用户来决定呢？

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/commit/375f4177d4cd9aac071cf0a438972bb4fc82a9d2
