### ISSUE TITLE
凡是文中带有$符号的，就会出问题

### ISSUE THREAD

**Issue by xiebruce** [JaxsonWang/WP-Editor.md#311]
用反斜杠`\$`会导致这个符号后面的所有内容都不显示，不加反斜杠会导致它后面的字体变的比较大，跟前面不一样，希望能解决

**Comment by JaxsonWang** [comment]
无法重现该问题，请贴出相关示例文章数据。

**Comment by xiebruce** [comment]
需要开启KaTeX才会有这个问题，这是测试数据：
[test.md.zip](https://github.com/JaxsonWang/WP-Editor.md/files/2721023/test.md.zip)

**Comment by JaxsonWang** [comment]
这个问题有点复杂，只要代码包括$符号就会被识别公式识别符，有空我再看看怎么解决吧。

**Comment by JaxsonWang** [comment]
![image](https://user-images.githubusercontent.com/16836692/51102848-7d7c6a00-181b-11e9-8e8a-4e5f3a4a91db.png)

https://github.com/JaxsonWang/WP-Editor.md/blob/master/src/App/KaTeX.php

初步判断还是正则问题，已经优化十几次依然还有问题。

**Comment by xiebruce** [comment]
好的，辛苦辛苦

**Comment by sangyunxin** [comment]
同样的问题，这是我的配置：
![image](https://user-images.githubusercontent.com/32364921/51980009-b67a3700-24c9-11e9-9f77-48fc9b3c685b.png)
插入代码如下：
`<dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>\${spring.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-beans</artifactId>
      <version>\${spring.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <version>\${spring.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context-support</artifactId>
      <version>\${spring.version}</version>
    </dependency>`
