### ISSUE TITLE
http跟https

### ISSUE THREAD

**Issue by star-Ming** [JaxsonWang/WP-Editor.md#312]
问题：我在wordpress使用markdown插件，挺好用的，但是当我wordpress开启HTTPS协议的时候，你那插件一直初始化不了，不知道为啥

**Comment by DennisCoder1024** [comment]
难道是因为https的原因？

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/issues/304

**Comment by DennisCoder1024** [comment]
http://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.3/assets/MindMap/mindMap.min.js 我下载的是最新版本，这个资源是http的，我启用了HTTPS，所以Chrome会报错。

**Comment by DennisCoder1024** [comment]
![image](https://user-images.githubusercontent.com/30309134/50720469-eb70b500-10e8-11e9-8cdf-f0e4a08f7212.png)

**Comment by DennisCoder1024** [comment]
我启用了不安全的JS就可以了。

**Comment by DennisCoder1024** [comment]
不知道楼主是不是可以提供一个不使用CDN的版本，这样所有的资源部署在自己的服务器上。

**Comment by DennisCoder1024** [comment]
![image](https://user-images.githubusercontent.com/30309134/50720855-2de9c000-10f0-11e9-9123-d7cd2fd7edc9.png)


![image](https://user-images.githubusercontent.com/30309134/50720858-36da9180-10f0-11e9-974f-d2f5fc3cd54c.png)

**Comment by DennisCoder1024** [comment]
下载了最新版，仍然提示过时？

**Comment by JaxsonWang** [comment]
@DennisCoder1024 打开资源包的`Version.json` 检查`"version": "10.0.3",`这个参数是否对应版本号，之前有个同学告诉我这里没改，我这里没时间上传新的，你看看是不是。

**Comment by DennisCoder1024** [comment]
是的，没有改，

**Comment by JaxsonWang** [comment]
@DennisCoder1024 改成最新版本即可`10.0.3`

**Comment by DennisCoder1024** [comment]
![image](https://user-images.githubusercontent.com/30309134/50720899-2545b980-10f1-11e9-8468-f9abe40d240c.png)

![image](https://user-images.githubusercontent.com/30309134/50720900-30004e80-10f1-11e9-90ca-21b89e12dd43.png)
这个资源还是存在http的问题。我修改了版本号，提示版本最新了。

**Comment by JaxsonWang** [comment]
@DennisCoder1024 这个去思维导图修改成：你的地址/assets/MindMap/mindMap.min.js就行了

**Comment by DennisCoder1024** [comment]
谢谢啦，之前这个地方改错了，还出现过修改完以后(如果有错误)，wordpress后台就打不开，重新安装插件也不行的情况。
![image](https://user-images.githubusercontent.com/30309134/50720948-1d3a4980-10f2-11e9-9242-5582ae71aad9.png)

**Comment by DennisCoder1024** [comment]
不过现在好了
