### ISSUE TITLE
流程图无法显示

### ISSUE THREAD

**Issue by fcying** [JaxsonWang/WP-Editor.md#313]
绘图设置里面已经打开流程图了.
实际预览和发布都看不到
```flow
st=>start: User login
op=>operation: lperation
cond=>condition: Successful Yes or No?
e=>end: Into admin
st->op->cond
cond(yes)->e
cond(no)->op
```

![image](https://user-images.githubusercontent.com/106934/50758544-75617f00-129d-11e9-9f74-c42983974bf6.png)

系统环境	Linux
运行环境	Apache/2.4.25 (Debian)
PHP版本	7.2.13
PHP运行环境	apache2handler
浏览器信息	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
WordPress版本	5.0.2
插件版本	10.0.3
jQuery版本	1.12.4
当前用户权限	administrator
WordPress地址	https://blog.fcying.com
站点地址	https://blog.fcying.com
常规设置	task_list => off 
imagepaste => on 
imagepaste_sm => off 
live_preview => on 
sync_scrolling => on 
html_decode => off 
support_front => off 
support_reply => off 
support_other_text => 
编辑器设置	theme_style => default 
code_style => default 
editor_addres => https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.3 
语法高亮设置	highlight_mode_auto => off 
line_numbers => off 
show_language => off 
copy_clipboard => off 
highlight_library_style => default 
customize_my_style => nothing 
highlight_mode_customize => off 
customize_highlight_style => nothing 
customize_highlight_javascript => nothing 
Emoji表情设置	support_emoji => off 
文章目录设置	support_toc => off 
科学公式设置	support_katex => off 
绘图设置	support_mermaid => on 
mermaid_config => { "theme": "dark", "logLevel": 5, "arrowMarkerAbsolute": false, "startOnLoad": true, "flowchart": { "htmlLabels": true, "curve": "linear" }, "sequence": { "diagramMarginX": 50, "diagramMarginY": 10, "actorMargin": 50, "width": 150, "height": 65, "boxMargin": 10, "boxTextMargin": 5, "noteMargin": 10, "messageMargin": 35, "mirrorActors": true, "bottomMarginAdj": 1, "useMaxWidth": true }, "gantt": { "titleTopMargin": 25, "barHeight": 20, "barGap": 4, "topPadding": 50, "leftPadding": 75, "gridLineStartPadding": 35, "fontSize": 11, "fontFamily": "\"Open-Sans\", \"sans-serif\"", "numberSectionStyles": 4, "axisFormat": "%Y-%m-%d" }, "class": {}, "git": {} } 
高级设置	jquery_compatible => off 
hide_ads => off

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/wiki/04.-Mermaid-Document

**Comment by fcying** [comment]
和原来用的语法不一样了....
感谢. 我看看去
