### ISSUE TITLE
和Autoptimize插件一起使用时，优化js后，components/prism-clike.min.js找不到

### ISSUE THREAD

**Issue by q398044828** [JaxsonWang/WP-Editor.md#314]
未开Autoptimize的js优化时，代码高亮主题文件   访问路径为
/assets/Prism.js/components/prism-clike.min.js  能正常访问正常显示

开了Autoptimize的js优化时，访问路径变为
/wp-content/cache/autoptimize/js/components/prism-clike.min.js, 页面显示文章时，此地址404，
导致md文章的代码高亮无法正常高亮

初步判断Autoptimize优化js时，将Prism.js路径判断为一个文件了

**Comment by JaxsonWang** [comment]
插件prism.js是动态加载语法类型样式，建议不要使用这类插件，或者将cdn排除亦或白名单。
