### ISSUE TITLE
不开启兼容模式则访问网站时无法加载（建议默认开启兼容模式）

### ISSUE THREAD

**Issue by samar1tan** [JaxsonWang/WP-Editor.md#318]
配置信息如下：
![image](https://user-images.githubusercontent.com/30967204/51604666-70145d80-1f48-11e9-84f2-907fa357c6c1.png)

不开启兼容模式时网站加载不出来。开启兼容模式后目前貌似一切正常（所以建议默认开启兼容模式？）

**Comment by JaxsonWang** [comment]
那就开启兼容模式启用，非兼容模式指的是wordpress默认主题正常使用的情况下。
