### ISSUE TITLE
while using Numbered Lists and Code block together, the Numbered Lists stops working

### ISSUE THREAD

**Issue by williamyinssw** [JaxsonWang/WP-Editor.MD#32]
e.g.  the below code doesn't do the number work in this editor, the 2nd point is still showing number 1. I had to add a dot (.) at the beginning of point 2.

1. In your solution (works on both Farm and Sandbox solution), create a new module, then update the Elements.xml file to the below:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
<CustomAction
ScriptSrc="~SiteCollection/Style Library/Customized/js/your.js"
Location="ScriptLink"
Sequence="100">
</CustomAction>
</Elements>
```
2. Create another module to deploy **your.js** into SharePoint to match the above location referred by **ScriptSrc**, the Elements.xml file looks like:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
<Module Name="Style Library" Path="Style Library\Customized\js" Url="Style Library/Customized/js">
<File Path="your.js" Url="your.js" ReplaceContent="TRUE" />
</Module>
</Elements>
```
![image](https://user-images.githubusercontent.com/14189481/28866707-19a1fe4c-77b7-11e7-9f9f-099870afa8d9.png)

(See my online page at http://blog.williamyin.com/easiest-way-to-apply-a-js-file-in-sharepoint-site-collection-scope/)

**Comment by JaxsonWang** [comment]
Thanks for feedback, in fact, you may be a little bit of writing an article, I write an example to you:

```
1. List 1

	```html
	<h1>1</h1>
	```

1. List 2

	```xml
	<?xml version="1.0" encoding="utf-8"?>
	<Elements xmlns="http://schemas.microsoft.com/sharepoint/">
	<CustomAction
	ScriptSrc="~SiteCollection/Style Library/Customized/js/your.js"
	Location="ScriptLink"
	Sequence="100">
	</CustomAction>
	</Elements>
	```

1. List 3
```
To add content between list codes, you need to click the `tap` key to distinguish between the upper and lower levels:

![](https://iiong.com/wp-content/uploads/2017/08/QQ20170802-175449.png)

**Comment by williamyinssw** [comment]
It works after having the Code Block indented, thank you very much :)
