### ISSUE TITLE
插件会和 Crayon Syntax Highlighter 冲突

### ISSUE THREAD

**Issue by SysConKonn** [JaxsonWang/WP-Editor.md#321]
在同时使用这个插件和 Crayon Syntax Highlighter 之后，博客内容是无法显示的。
不知道能不能解决。

**Comment by JaxsonWang** [comment]
插件自带语法高亮功能，如果选择第三方请关闭自带高亮，使用：https://github.com/JaxsonWang/WP-Editor.md/wiki/07.-Code-block-%E4%BB%A3%E7%A0%81%E5%9D%97%E4%BD%BF%E7%94%A8
