### ISSUE TITLE
插件失效

### ISSUE THREAD

**Issue by Javi2004** [JaxsonWang/WP-Editor.md#322]
献上调试信息：
![image](https://user-images.githubusercontent.com/32459390/51752699-0e442700-20f3-11e9-9f7e-0bfd7c627a50.png)
然后插件列表：
![image](https://user-images.githubusercontent.com/32459390/51752723-1e5c0680-20f3-11e9-9d36-72e872f18d3e.png)
主题：MDX
场面：
![image](https://user-images.githubusercontent.com/32459390/51752748-303da980-20f3-11e9-8485-a98f849887eb.png)
所以插件**去哪里**了？（~~被吃了~~）
www.javiblog.top

**Comment by Javi2004** [comment]
版本：WordPress 5.0.3

**Comment by JaxsonWang** [comment]
停用其他插件，使用默认插件再测试。
