### ISSUE TITLE
js加载失败，导致编辑器无限转圈加载

### ISSUE THREAD

**Issue by chenxuuu** [JaxsonWang/WP-Editor.md#323]
# 现象

打开任意一个文章编辑，编辑器无限转圈加载

# 复现方式

后台在思维导图选项卡，设置一个打开会404的网站
![image](https://user-images.githubusercontent.com/10357394/51963649-3fc84400-249f-11e9-8f94-dd912a4926fe.png)

# 正确情况下应该有的现象

加载失败就直接忽略，或者提示xx加载失败无法使用。不应该无限转圈加载

**Comment by justchen** [comment]
遇到同样的问题....很严重.无法使用

**Comment by sazima** [comment]
将思维导图功能关闭即可.
