### ISSUE TITLE
行号和代码不对齐

### ISSUE THREAD

**Issue by Cruii** [JaxsonWang/WP-Editor.md#325]
在编辑器里面是正常的显示，但是到了页面就会显示不对齐。都卸载重装好几次了

**Comment by JaxsonWang** [comment]
切换默认主题看看，应该是主题样式干扰。

**Comment by Cruii** [comment]
确实可以，但是我原来也是用的这个主题当时也没有出现这个情况，那就这样吧，我就用默认主题吧。
