### ISSUE TITLE
插入视频bug

### ISSUE THREAD

**Issue by RRRaymond** [JaxsonWang/WP-Editor.md#327]
点击编辑器左上角“添加媒体”按钮插入视频后
插入了如下文本
> \[video width="544" height="960" mp4="https://closecv.com/wp-content/uploads/2019/02/1550940813814846.mp4"\]\[/video\]

每个方括号前有一个转义符`\`，导致视频显示不出来，手动删除每个方括号前的转义符后可以正常显示
本来想自己稍微改一下代码的，但是是实在不太懂js，只好来提issue了
我也不太确定是不是WP Editor的问题，还是和其他插件有冲突
我使用的WP版本是4.99，WP Editor的版本是10.0.3

**Comment by JaxsonWang** [comment]
不建议使用wp短代码插入，可以用h5的 video标签 插入
