### ISSUE TITLE
https协议加载插件失败

### ISSUE THREAD

**Issue by e-lionel** [JaxsonWang/WP-Editor.md#328]
Mixed Content: The page at 'https://www.e-lionel.com/wp-admin/post-new.php' was loaded over HTTPS, but requested an insecure script 'http://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.3/assets/MindMap/mindMap.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by wucongyou** [comment]
点击思维导图设置，把思维导图资源库的地址改为 https 协议即可。
