### ISSUE TITLE
在编辑预览时没问题，文章发表后却只有一部分内容，后面就没了

### ISSUE THREAD

**Issue by flyhero99** [JaxsonWang/WP-Editor.md#329]
如图，我的markdown代码写的有点长，但是在编辑页面下预览是没问题的：
![image](https://user-images.githubusercontent.com/23097808/53746273-cd9eb100-3edb-11e9-9052-973143871bdc.png)
然而，发表了wen zhan文章后，不管怎么改、怎么刷新，都只显示到前面一点点。。后面大部分的内容都没有了T_T请问是什么原因？难道是文章长度有限制？但也不应该这么短吧？？（如下图）
![image](https://user-images.githubusercontent.com/23097808/53746202-a811a780-3edb-11e9-866a-95fab1409f6e.png)

**Comment by JaxsonWang** [comment]
你开启科学公式？可能文章包含多个`$`符号导致文章截取了，算是插件一个bug，目前这个bug并不好解决。
