### ISSUE TITLE
LaTeX科学公式在前台没有显示

### ISSUE THREAD

**Issue by shi-yang** [JaxsonWang/WP-Editor.MD#33]
已经在插件配置中开启LaTeX科学公式支持选项

写LaTeX科学公式时，在编辑器中能正确显示，到前台就没有显示，是不是还得自己安装相应插件？

Chrome 控制台console提示说：
`Uncaught ReferenceError: katex is not defined`

**Comment by JaxsonWang** [comment]
请到后台Edior.md设置，再次点击`保存更改`的按钮，估计是引入库没有加载到数据库。

**Comment by shi-yang** [comment]
懂了，是我这里用了Autoptimize插件，用这个插件优化 JavaScript 代码后，导致 katex 没能加载进来，得把Autoptimize插件优化 JavaScript 代码功能关了才可以正常显示．
谢了
