### ISSUE TITLE
可以添加页面内锚点吗

### ISSUE THREAD

**Issue by qnlz** [JaxsonWang/WP-Editor.md#332]

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/Editormd/commit/3a086189217de4fee7842d1a03a015bde92b31b1

使用方法参考：https://github.com/JaxsonWang/WP-Editor.md/wiki/02.-Markdown-Document#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%87%E9%A2%98%E6%8F%8F%E7%82%B9
