### ISSUE TITLE
加载有问题,一直加载不出编辑器

### ISSUE THREAD

**Issue by huanhaokj** [JaxsonWang/WP-Editor.md#335]

**Comment by JaxsonWang** [comment]
如果你开启MindMap功能发现编辑器无法打开请替换思维导图地址：https://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.3/assets/MindMap/mindMap.min.js或者再次刷新网页。

最近比较忙没看到。这个bug修个版本修复！

**Comment by JaxsonWang** [comment]
Bug：思维地图依赖库地址不正确导致编辑器无法正常加载

**Comment by 897354667** [comment]
作者你好，粘贴完图像会跳到顶部问题确实有点烦，有时候写了很长给跳回去了

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/commit/12ec6f9e7925bb7d4930d2dfef72b3369f47c495
