### ISSUE TITLE
目录支持有些问题

### ISSUE THREAD

**Issue by liangsaifei** [JaxsonWang/WP-Editor.md#336]
下载了Table of Contents Plus,也启用了，编辑文章加目录，左右预览打开 是显示目录的，但是文章更新后 查看文章只有[TOC]。

**Comment by JaxsonWang** [comment]
如果我记得没错的话 应该是小写的 `[toc]`

**Comment by liangsaifei** [comment]
> 如果我记得没错的话 应该是小写的 `[toc]`

好的。改了好了。
