### ISSUE TITLE
是否支持图片大小调整？

### ISSUE THREAD

**Issue by xindoo** [JaxsonWang/WP-Editor.md#337]
是否支持图片大小调整？

**Comment by JaxsonWang** [comment]
标准Markdown语法不支持，暂时不考虑添加该特性。

----------
永远年轻，永远热泪盈眶！

--------------原始邮件--------------
发件人："Weber Zhang "<notifications@github.com>;
发送时间：2019年8月18日(星期天) 下午4:35
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[JaxsonWang/WP-Editor.md] 是否支持图片大小调整？ (#337)
-----------------------------------

 
是否支持图片大小调整？
