### ISSUE TITLE
代码高亮自定义怎么设置

### ISSUE THREAD

**Issue by lyjzsyzlt** [JaxsonWang/WP-Editor.md#338]
![image](https://user-images.githubusercontent.com/30644064/63503501-2c93c900-c502-11e9-92c6-4282a165a33e.png)
这个地址该怎么填，能否举个例子？
另外，代码为shell的时候无法高亮（但是预览的时候可以），python等语言可以高亮

**Comment by JaxsonWang** [comment]
自定义高亮类库请到[这儿](https://github.com/JaxsonWang/Prism.js-Style)下载，该选项满足喜欢自定义选高亮风格的人群，链接地址只需要填写样式的服务器绝对路径即可，例如将 `xxx.css` 放入您的服务器，填写 `https://exmail.com/xxx.css` 即可。

语法类型请在 [PrismJS Supported Languages](https://prismjs.com/#supported-languages) 查询相关支持的语法高亮类型，您的 `shell` 渲染高亮类型即是 `bash` 类型。

如有问题请再开 issue 谢谢！
