### ISSUE TITLE
katex的行内公式支持似乎有问题

### ISSUE THREAD

**Issue by ChenghuiS** [JaxsonWang/WP-Editor.md#339]
使用单行公式   `$ $`   在实时预览时显示没问题，可以一旦发布文章就无法正常显示了。

编辑预览的时候：
![image](https://user-images.githubusercontent.com/22197327/63701454-8de7cf00-c857-11e9-8714-0c10fe909b33.png)

发布之后:
![image](https://user-images.githubusercontent.com/22197327/63701632-e15a1d00-c857-11e9-8a0d-e60dc7745d30.png)

不过如果是使用多行公式 `$$   $$`的话又可以正常显示。

**Comment by JaxsonWang** [comment]
好的，我有时间看看是否确定有问题，感谢反馈！

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/commit/12ec6f9e7925bb7d4930d2dfef72b3369f47c495
