### ISSUE TITLE
Conflict with Divi Builder

### ISSUE THREAD

**Issue by lbngoc** [JaxsonWang/WP-Editor.MD#34]
If I switch to visual builder mode (Divi, Visual Composer), the content is not saved, it's keep current version in Markdown.

**Comment by JaxsonWang** [comment]
You can use Divi Builder to get the data ID into here to convert markdown data: https: //github.com/JaxsonWang/WP-Editor.MD/blob/master/Jetpack/markdown/easy-markdown.php#L78
