### ISSUE TITLE
加载不出来

### ISSUE THREAD

**Issue by gybpython** [JaxsonWang/WP-Editor.md#341]
更新到最新，编辑文章会一直转圈圈，加载不出来markdown编辑页面

**Comment by JaxsonWang** [comment]
麻烦打开浏览器到编辑器界面 `F12` 打开界面后在 console 窗口截图看看，如果有红色报错的话。

**Comment by gybpython** [comment]
> 麻烦打开浏览器到编辑器界面 `F12` 打开界面后在 console 窗口截图看看，如果有红色报错的话。

我找到问题了，requested an insecure script 'http://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.3/assets/MindMap/mindMap.min.js'. This request has been blocked; the content must be served over HTTPS. 如果您不忙的话，麻烦教一下这里如何把cdn的http改为https？

**Comment by JaxsonWang** [comment]
请到插件设置中的思维导图设置一下就行了

----------
永远年轻，永远热泪盈眶！

--------------原始邮件--------------
发件人："Kirito "<notifications@github.com>;
发送时间：2019年9月5日(星期四) 下午5:44
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："Jaxson Wang "<i@iiong.com>;"Comment "<comment@noreply.github.com>;
主题：Re: [JaxsonWang/WP-Editor.md] 加载不出来 (#341)
-----------------------------------

  
麻烦打开浏览器到编辑器界面 F12 打开界面后在 console 窗口截图看看，如果有红色报错的话。
  
我找到问题了，requested an insecure script 'http://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.3/assets/MindMap/mindMap.min.js'. This request has been blocked; the content must be served over HTTPS. 如果您不忙的话，麻烦教一下这里如何把cdn的http改为https？

**Comment by JaxsonWang** [comment]
如有问题请再重开该 issue
