### ISSUE TITLE
代码段中的双引号会显示为&quot;

### ISSUE THREAD

**Issue by xxhddt163** [JaxsonWang/WP-Editor.md#342]
没有安装任何别的插件 只安装了markdown.md  在编辑器里双引号是正常的
发布或者预览后双引号就变成&quot;了（我没有安装别的插件） 大佬快点修复吧 没有你的markdown编辑器生活不能自理了

**Comment by JaxsonWang** [comment]
晚上下班回去看看

----------
永远年轻，永远热泪盈眶！

--------------原始邮件--------------
发件人："xxhddt163 "<notifications@github.com>;
发送时间：2019年9月5日(星期四) 下午5:40
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[JaxsonWang/WP-Editor.md] 代码段中的双引号会显示为&quot; (#342)
-----------------------------------

 
没有安装任何别的插件 只安装了markdown.md  在编辑器里双引号是正常的
 发布或者预览后双引号就变成"了（我没有安装别的插件） 大佬快点修复吧 没有你的markdown编辑器生活不能自理了

**Comment by JaxsonWang** [comment]
![image](https://user-images.githubusercontent.com/16836692/64340854-b327ca80-d019-11e9-8514-50ad5131a2a1.png)

![image](https://user-images.githubusercontent.com/16836692/64340863-b622bb00-d019-11e9-9088-d0e39dd45794.png)

目前测试环境没有出现你说的问题，请复现该bug的步骤

**Comment by wolfdan666** [comment]
![8EF9BA64-602A-4B2B-B868-FA01A8167BBB](https://user-images.githubusercontent.com/37760924/64345743-75c83a80-d023-11e9-801e-29d9da8842c8.png)
**是的，预览没有问题，但是实际展示有问题，之前的版本没问题，今天更新后出问题了**

**Comment by JaxsonWang** [comment]
我测试依然无法复现你说的问题，请修复文章错误后点击按钮再更新试试。如果还出现问题请提交文章测试数据，我再来看看。

**Comment by wolfdan666** [comment]
emmm,我的文章发布在hexo上面是正常的，而且以前的wordpress的文章也是正常的，就是今天插件更新后发布的文章不正常，预览也是正常，我也不知道出错在哪

**Comment by xxhddt163** [comment]
> emmm,我的文章发布在hexo上面是正常的，而且以前的wordpress的文章也是正常的，就是今天插件更新后发布的文章不正常，预览也是正常，我也不知道出错在哪

是不是只要是添加在代码框里的就会有问题 不在代码框的就不会

**Comment by wolfdan666** [comment]
> > emmm,我的文章发布在hexo上面是正常的，而且以前的wordpress的文章也是正常的，就是今天插件更新后发布的文章不正常，预览也是正常，我也不知道出错在哪
> 
> 是不是只要是添加在代码框里的就会有问题 不在代码框的就不会

是的，就是这样的

**Comment by xxhddt163** [comment]
> 我测试依然无法复现你说的问题，请修复文章错误后点击按钮再更新试试。如果还出现问题请提交文章测试数据，我再来看看。
[http://www.xianxuehai.top/wp-content/uploads/2019/09/1.png](url)
[http://www.xianxuehai.top/wp-content/uploads/2019/09/2.png](url)
[http://www.xianxuehai.top/wp-content/uploads/2019/09/3.png](url)
[http://www.xianxuehai.top/wp-content/uploads/2019/09/4.png](url)



语法高亮设置：
highlight_mode_auto => on 
line_numbers => on 
show_language => off 
copy_clipboard => off 
highlight_library_style => dark 
customize_my_style => nothing

**Comment by xxhddt163** [comment]
> > > emmm,我的文章发布在hexo上面是正常的，而且以前的wordpress的文章也是正常的，就是今天插件更新后发布的文章不正常，预览也是正常，我也不知道出错在哪
> > 
> > 
> > 是不是只要是添加在代码框里的就会有问题 不在代码框的就不会
> 
> 是的，就是这样的

大佬 我不会发图- - ！

**Comment by JaxsonWang** [comment]
@xxhddt163 @wolfdan666 请在设置
![image](https://user-images.githubusercontent.com/16836692/64348268-7662d000-d027-11e9-95f9-ce66585c23e5.png)打开该选项再重试！

**Comment by xxhddt163** [comment]
好了 不愧是大佬

**Comment by hygf99** [comment]
> 好了，不愧是大佬
