### ISSUE TITLE
刚更新的Version 10.0.4行号不对

### ISSUE THREAD

**Issue by xiebruce** [JaxsonWang/WP-Editor.md#344]
bug如下，最后的行没有行号：
![image](https://user-images.githubusercontent.com/13575500/64424059-9acbb480-d0da-11e9-811e-6ac861b13375.png)

我在编辑器里是这么写的：
![image](https://user-images.githubusercontent.com/13575500/64424107-c189eb00-d0da-11e9-9e58-6dd562f97652.png)

```bash
# 添加
git add .

# 提交
git commit -a -m "First commit"

# 推送到github
git push
```

页面：[https://www.xiebruce.top/663.html](https://www.xiebruce.top/663.html)，在页面最后。
还有这个页面最后也是，而且情况更严重：[https://www.xiebruce.top/609.html](https://www.xiebruce.top/609.html)

**Comment by JaxsonWang** [comment]
请切换默认主题再重试，如果默认主题没有问题的话，那么判断你现在所用的主题样式干扰的。

**Comment by xiebruce** [comment]
@JaxsonWang 随便换了个主题，确实没问题了，不过，我在前一个版本一直没问题，更新这个版本就有问题了😂 我再找找是啥问题吧

**Comment by xiebruce** [comment]
@JaxsonWang 找出问题了，是因为新的prism.css有这个字号1em，如果去掉就没问题了：
![image](https://user-images.githubusercontent.com/13575500/64470672-b934bd00-d179-11e9-88d5-ae40f50f2a6d.png)

但是如果不去掉那个font-size的话，怎么把行号也跟着变大呢？我试着加个行号，不行，能帮忙看看要在哪加吗？
![image](https://user-images.githubusercontent.com/13575500/64470696-41b35d80-d17a-11e9-8a67-4ecd0840184b.png)

**Comment by JaxsonWang** [comment]
@xiebruce 
```css
.line-numbers-rows > span {
    line-height: 27px;
}
```

27px 微调下
