### ISSUE TITLE
请问10.0.4中WP的段代码是不是被过滤了？

### ISSUE THREAD

**Issue by minorowe** [JaxsonWang/WP-Editor.md#345]
RT，我在WP（5.2.3）中，点“添加媒体”后插入了一个视频链接，然后编辑器内就被添加了转义符。我又换了h5的video标签，结果发布后也被过滤掉，直接输出了代码，随后我发现只要是代码都会被原样输出，例如`<center>居中内容</center>`就会被输出“`<center>居中内容</center>`”，不知道是什么原因，在一个版本并未出现这样的错误。

**Comment by JaxsonWang** [comment]
参考：https://github.com/JaxsonWang/WP-Editor.md/issues/342

**Comment by minorowe** [comment]
> 参考：#342

勾选“支持HTML”后就正常了，谢回复。
