### ISSUE TITLE
[BUG] 更新后会将HTML代码原样输出？

### ISSUE THREAD

**Issue by aitlp** [JaxsonWang/WP-Editor.md#347]
更新版本10.0.4后，网页展示出现问题，对HTML代码会原格式展示。

![image](https://user-images.githubusercontent.com/4659346/64469128-8d0c4280-d15f-11e9-9da4-273a7c03fa44.png)

**Comment by JaxsonWang** [comment]
参考：https://github.com/JaxsonWang/WP-Editor.md/issues/342
