### ISSUE TITLE
引用出锅

### ISSUE THREAD

**Issue by xht37** [JaxsonWang/WP-Editor.md#349]
我这里的引用不是指双引号的问题，而是指

> 引用

会显示成

\> 引用

详见 [https://www.xht37.com/oi-blogs/](url)

**Comment by xht37** [comment]
[https://www.xht37.com/oi-blogs/](https://www.xht37.com/oi-blogs/)

**Comment by JaxsonWang** [comment]
你先把html解析打开再试试

----------
永远年轻，永远热泪盈眶！

--------------原始邮件--------------
发件人："xht37 "<notifications@github.com>;
发送时间：2019年9月8日(星期天) 晚上7:34
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[JaxsonWang/WP-Editor.md] 引用出锅 (#349)
-----------------------------------

 
我这里的引用不是指双引号的问题，而是指
  
引用
  
会显示成
 
> 引用
 
详见 https://www.xht37.com/oi-blogs/

**Comment by xht37** [comment]
好了，感谢！
