### ISSUE TITLE
无法启用代码高亮

### ISSUE THREAD

**Issue by yuzenan888** [JaxsonWang/WP-Editor.MD#35]
您好。我开启了前端支持代码高亮之后，编辑器显示正常，但文章发布之后代码高亮就无法显示。Chrome控制台有一个错误：`Uncaught ReferenceError: Prism is not defined`。请问是什么问题？主题用的是自带的TwentyFifteen，只有WP-Editor.MD这个插件。

**Comment by JaxsonWang** [comment]
请到后台Edior.md设置，再次点击保存更改的按钮，估计是引入库没有加载到数据库。

**Comment by yuzenan888** [comment]
您好，尝试之后依然不行。您这么说的话请问能否直接修改数据库？

**Comment by JaxsonWang** [comment]
wp_options表中的`editormd_options`就是存入本插件的设置数据

**Comment by JaxsonWang** [comment]
在此之前建议你开启debug模式。

如何开启：
在你的wp根目录有个wp-config.php，打开寻找define('WP_DEBUG', false);修改成define('WP_DEBUG', true);保存即可。

在保存设置中可能会提示代码调试功能输出，请帖上来。

**Comment by yuzenan888** [comment]
您好。我修改了`wp-config.php`之后，找不到`wp-content/error.log`，不知道是不是哪里错了。要是不行的话今晚我看看数据库。
```
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define( 'SAVEQUERIES', true );
```

**Comment by yuzenan888** [comment]
您好。WordPress不知怎么的老是无法生成日志文件，下面贴上我数据库的查询结果。
```
a:11:{s:17:"support_highlight";s:1:"1";s:25:"support_highlight_library";s:59:"http://pi/wp-content/plugins/wp-editormd/Prism/";s:31:"support_highlight_library_style";s:7:"default";s:21:"support_emoji_library";s:63:"http://pi/wp-content/plugins/wp-editormd/Emojify.js";s:30:"support_latex_editormd_library";s:58:"http://pi/wp-content/plugins/wp-editormd/KaTeX";s:25:"support_flowchart_library";s:62:"http://pi/wp-content/plugins/wp-editormd/FlowChart";s:32:"support_jquery_flowchart_library";s:62:"http://pi/wp-content/plugins/wp-editormd/FlowChart";s:24:"support_sequence_library";s:61:"http://pi/wp-content/plugins/wp-editormd/Sequence";s:23:"support_raphael_library";s:60:"http://pi/wp-content/plugins/wp-editormd/Raphael";s:26:"support_underscore_library";s:63:"http://pi/wp-content/plugins/wp-editormd/Underscore";s:22:"support_jquery_library";s:59:"http://pi/wp-content/plugins/wp-editormd/jQuery";}
```

**Comment by JaxsonWang** [comment]
你这个看起来没有问题，确保环境是干净的

**Comment by yuzenan888** [comment]
您好。可能是我的问题，打算重装整个Wordpress再试。您先close吧。

**Comment by WillisSt** [comment]
先别close，我也是同样问题：
> 前端的代码无法高亮显示，代码风格也不起作用。
chrome检查一个错误如下：
```
Uncaught ReferenceError: Prism is not defined
    at HTMLElement.<anonymous> (?p=91&preview=true:345)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at HTMLDocument.<anonymous> (?p=91&preview=true:344)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
```
插件设置中，尝试修改 Prism语法高亮加载库
发现是能写入 editormd_options 数据库中的，值如下：(站点域名用xxx.com代替)
```
a:14:{s:17:"support_highlight";s:1:"1";s:25:"support_highlight_library";s:38:"https://cdn.staticfile.org/prism/1.6.0";s:31:"support_highlight_library_style";s:4:"dark";s:13:"support_emoji";s:1:"1";s:21:"support_emoji_library";s:64:"https://xxx.com/log/wp-content/plugins/wp-editormd/Emojify.js";s:30:"support_latex_editormd_library";s:59:"https://xxx.com/log/wp-content/plugins/wp-editormd/KaTeX";s:17:"support_flowchart";s:1:"1";s:25:"support_flowchart_library";s:63:"https://xxx.com/log/wp-content/plugins/wp-editormd/FlowChart";s:32:"support_jquery_flowchart_library";s:63:"https://xxx.com/log/wp-content/plugins/wp-editormd/FlowChart";s:16:"support_sequence";s:1:"1";s:24:"support_sequence_library";s:62:"https://xxx.com/log/wp-content/plugins/wp-editormd/Sequence";s:23:"support_raphael_library";s:61:"https://xxx.com/log/wp-content/plugins/wp-editormd/Raphael";s:26:"support_underscore_library";s:64:"https://xxx.com/log/wp-content/plugins/wp-editormd/Underscore";s:22:"support_jquery_library";s:60:"https://xxx.com/log/wp-content/plugins/wp-editormd/jQuery";}
```
另外，支持文章目录 的插件尝试了下，似乎也不行。

大佬，这个插件真的很好，支持您！！  恳请解决～

**Comment by JaxsonWang** [comment]
@WillisSt 这个原因太多了。首先你得排除其他优化插件的干扰，有的请停用，以及主题可能会干扰，请切换到默认主题。

建议开启debug模式，上面我提到了。

如果以上都做到还出现原因，请打开浏览器F12开发者控制台（以Chrome为例），请切换到`Network`选项卡，寻找prism文件是否加载进来，实在不知道是什么文件，干脆找`prism-core.min.js`这个文件是否出现列表（需要在Network选项卡中再次刷新页面，确保资源是否全部加载进来）。

**Comment by WillisSt** [comment]
好的，谢谢～

**Comment by yuzenan888** [comment]
照着您的说法做了一下，prism-core.min.js这个文件并没有被加载。我已经把整个站点的权限改成了777，依然无法加载。不知道会不会是PHP少了什么模块。
> @WillisSt 这个原因太多了。首先你得排除其他优化插件的干扰，有的请停用，以及主题可能会干扰，请切换到默认主题。
> 
> 建议开启debug模式，上面我提到了。
> 
> 如果以上都做到还出现原因，请打开浏览器F12开发者控制台（以Chrome为例），请切换到Network选项卡，寻找prism文件是否加载进来，实在不知道是什么文件，干脆找prism-core.min.js这个文件是否出现列表（需要在Network选项卡中再次刷新页面，确保资源是否全部加载进来）。

**Comment by JaxsonWang** [comment]
@yuzenan888 问题已确定，请用github版本，wp库版本今晚推送新版本号

**Comment by blackcat-tech** [comment]
@yuzenan888 代码高亮问题，解决了吗？

**Comment by blackcat-tech** [comment]
@JaxsonWang 代码高亮问题解决了吗？

**Comment by JaxsonWang** [comment]
@blackcat-tech 2.8已经推送了，解决了

**Comment by blackcat-tech** [comment]
@JaxsonWang  我用的 WordPress 4.7.5，后台设置开启了代码高亮，样式默认是：Default 。但是，前端还是没有高亮显示~

**Comment by yuzenan888** [comment]
代码高亮确实解决了。但是好像不能识别Shell语言。还有代码怎么改字体？

**Comment by JaxsonWang** [comment]
@blackcat-tech 首先你得排除其他优化插件的干扰，有的请停用，以及主题可能会干扰，请切换到默认主题。

**Comment by JaxsonWang** [comment]
@yuzenan888 https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Document/use-zh_CN.md#前端支持语法高亮

请务必填写语法类型，否则无法加载语法类型的高亮文件，语法类型请参考[Prism.js Languages](http://prismjs.com/download.html)

请正确声明语法类型，shell类型有`bash`或者`powershell`，只支持小写。

代码字体的大小，是受你的主题样式影响

**Comment by blackcat-tech** [comment]
@JaxsonWang 使用了加载库：http://cdn.staticfile.org/prism/1.6.0 ，OK了。

额外提点优化的地方：主题的代码块，如果有自动换行的功能，就更完美了。哈哈

**Comment by JaxsonWang** [comment]
@blackcat-tech 这个同样也是受到主题影响
