### ISSUE TITLE
参考#342后依然不管用

### ISSUE THREAD

**Issue by Smi1eSEC** [JaxsonWang/WP-Editor.md#350]
![image](https://user-images.githubusercontent.com/39610144/64589525-e2528900-d3d7-11e9-85b2-838626f8bb95.png)

![image](https://user-images.githubusercontent.com/39610144/64589539-e9799700-d3d7-11e9-9cef-ef9025120910.png)

**Comment by JaxsonWang** [comment]
进入文章管理 打开 点击 `更新` 按钮重新渲染下文章。
