### ISSUE TITLE
<!--more--> 标签无法解析

### ISSUE THREAD

**Issue by yuzenan888** [JaxsonWang/WP-Editor.md#351]
WordPress 版本：5.2.3
WP Editor.md 版本：10.0.4
经典编辑器版本：1.5
在插入 `<!--more-->` 标签之后，编辑器无法正确解析，在文章中呈现出：

```
<!–more–>
```

请及时跟进，谢谢！

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/issues/342
