### ISSUE TITLE
KaTeX parse error

### ISSUE THREAD

**Issue by ni-chen** [JaxsonWang/WP-Editor.md#352]
您好，KaTex不支持Latex公式的样子，不知道能不能解决？我报错如下：
ParseError: KaTeX parse error: No such environment: equation at position 7: \begin{̲e̲q̲u̲a̲t̲i̲o̲n̲}̲

公式是按Latex写的：
$$
\begin{equation}
\begin{aligned}
F\left(\xi,\eta; z \right)
&= \iint\limits_{-\infty}^\infty{A(x,y)\exp\left\{j2\pi\left[x\xi + y \eta + z\sqrt{\left(\frac{1}\lambda \right)^2 - x^2 - y^2} \right] \right\}dxdy} \\
&= \iint\limits_{-\infty}^\infty{A(x,y)\exp\left\{j2\pi\left[x\xi + y\eta + z\left[\frac{1}{\lambda}-\frac{\lambda}{2}\left(x^2 + y^2 \right)\right] \right] \right\}dxdy} \\
\end{aligned}
\end{equation}
$$

**Comment by JaxsonWang** [comment]
@ni-chen 您好，我对 latex 公式不是太熟悉，之前搜索过 `\begin{equation}` 应该类似格式化功能，在 `katex` 应该有其他方式替代的。

在 latex `\begin{equation}` 应该是多行公式环境，在 `katex` 应该 `$$` 包裹即可。

如有我理解错误请说明下，我个人猜测。

> 参考：[https://github.com/KaTeX/KaTeX/issues/445](https://github.com/KaTeX/KaTeX/issues/445)

**Comment by ni-chen** [comment]
我用的就是$$包裹，里面采用了 \begin{equation} 。在其他makrdown编辑器里面是可以渲染的，比方VS
code。我猜是一个什么开关的问题吧。

**Comment by SamDu1998** [comment]
同出错，求问如何解决

**Comment by Ken-Leo** [comment]
解决了吗？
