### ISSUE TITLE
实时保存

### ISSUE THREAD

**Issue by huangwb8** [JaxsonWang/WP-Editor.md#353]
刚刚上手markdown，有一些word的习惯没改过来
请问这个没有Ctrl+S保存当前工作的快捷键呢？好像没看到~但感觉这种简单的功能应该不会没考虑到。
望指教，谢谢！

**Comment by JaxsonWang** [comment]
WP自带自动保存功能，和插件无关。
如果自动保存功能失效请检查函数禁用导致的。

**Comment by huangwb8** [comment]
好的，谢谢~自动保存功能是有效的，只是自己习惯了写完一段就Ctrl+S一下。谢谢解答！
