### ISSUE TITLE
" > " 符号不能渲染成 " 引用格式 " ，在预览里表现的好好的，但是实际生成的网页就不行

### ISSUE THREAD

**Issue by hygf99** [JaxsonWang/WP-Editor.md#354]
很奇怪， " > " 符号不能渲染成 " 引用格式 " ，在预览里表现的好好的，但是实际生成的网页就不行，" > “ 符号还是原来的样子，跟纯文本一样，没有变成想要的引用格式。

这个bug我是第二次遇到了，上次不知道设置了哪里，莫名其妙就好了，我还以为只是偶然情况，谁曾想换了台服务器又遇到这个情况，该怎么办呢？

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/issues/342

----------
永远年轻，永远热泪盈眶！

--------------原始邮件--------------
发件人："hygf99 "<notifications@github.com>;
发送时间：2019年9月15日(星期天) 下午3:32
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[JaxsonWang/WP-Editor.md] " > " 符号不能渲染成 " 引用格式 " ，在预览里表现的好好的，但是实际生成的网页就不行 (#354)
-----------------------------------

 
很奇怪， " > " 符号不能渲染成 " 引用格式 " ，在预览里表现的好好的，但是实际生成的网页就不行，" > “ 符号还是原来的样子，跟纯文本一样，没有变成想要的引用格式。
 
这个bug我是第二次遇到了，上次不知道设置了哪里，莫名其妙就好了，我还以为只是偶然情况，谁曾想换了台服务器又遇到这个情况，该怎么办呢？
