### ISSUE TITLE
代码块出锅

### ISSUE THREAD

**Issue by xht37** [JaxsonWang/WP-Editor.md#355]
```cpp
#include <bits/stdc++.h>
```

会被渲染成

```cpp
#include 
```

`<>` 和内部的东西都丢了

详见 [Link](https://www.xht37.com/io-%e4%bc%98%e5%8c%96-%e5%ad%a6%e4%b9%a0%e7%ac%94%e8%ae%b0/)

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.md/commit/cdc62ed75b5923c789f1e9d215bd2084d2f452b9

请耐心等待 v10.0.6 版本
