### ISSUE TITLE
无法启用插件，因为它引起了一个致命错误（fatal error）

### ISSUE THREAD

**Issue by meibin08** [JaxsonWang/WP-Editor.md#357]
下载之后启用，一直报这个错，对php了解不多，求解～
```
Fatal error: Uncaught Error: Class 'SettingsApi\SettingsApi' not found in /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Utils/Settings.php:31 Stack trace: 
#0 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Main.php(77): EditormdUtils\Settings->__construct('WP Editor.md', '10.0.6', 'editormd') 
#1 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Main.php(63): Editormd\Main->run_core() #2 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/wp-editormd.php(59): Editormd\Main->__construct() 
#3 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/wp-editormd.php(66): EditormdRoot\run_editormd() #4 /usr/share/nginx/wordpressBlog/wp-admin/includes/plugin.php(2141): include('/usr/share/ngin...') 
#5 /usr/share/nginx/wordpressBlog/wp-admin/plugins.php(175): plugin_sandbox_scrape('WP-Editor/wp-ed...') #6 {main} thrown in /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Utils/Settings.php on line 31
```
![image](https://user-images.githubusercontent.com/18324563/65308271-43d6dc80-dbbc-11e9-959d-f238af9e62df.png)

**Comment by JaxsonWang** [comment]
php版本太低了

----------
永远年轻，永远热泪盈眶！

--------------原始邮件--------------
发件人："苏南 "<notifications@github.com>;
发送时间：2019年9月20日(星期五) 下午3:36
收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[JaxsonWang/WP-Editor.md] 无法启用插件，因为它引起了一个致命错误（fatal error） (#357)
-----------------------------------

 
下载之后启用，一直报这个错，对php了解不多，求解～
 Fatal error: Uncaught Error: Class 'SettingsApi\SettingsApi' not found in /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Utils/Settings.php:31 Stack trace:  #0 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Main.php(77): EditormdUtils\Settings->__construct('WP Editor.md', '10.0.6', 'editormd')  #1 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Main.php(63): Editormd\Main->run_core() #2 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/wp-editormd.php(59): Editormd\Main->__construct()  #3 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/wp-editormd.php(66): EditormdRoot\run_editormd() #4 /usr/share/nginx/wordpressBlog/wp-admin/includes/plugin.php(2141): include('/usr/share/ngin...')  #5 /usr/share/nginx/wordpressBlog/wp-admin/plugins.php(175): plugin_sandbox_scrape('WP-Editor/wp-ed...') #6 {main} thrown in /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Utils/Settings.php on line 31

**Comment by meibin08** [comment]
> php版本太低了
> […](#)
> ---------- 永远年轻，永远热泪盈眶！
> --------------原始邮件-------------- 发件人："苏南 "<notifications@github.com>; 发送时间：2019年9月20日(星期五) 下午3:36 收件人："JaxsonWang/WP-Editor.md" <WP-Editor.md@noreply.github.com>; 抄送："Subscribed "<subscribed@noreply.github.com>; 主题：[JaxsonWang/WP-Editor.md] 无法启用插件，因为它引起了一个致命错误（fatal error） (#357) ----------------------------------- 下载之后启用，一直报这个错，对php了解不多，求解～ Fatal error: Uncaught Error: Class 'SettingsApi\SettingsApi' not found in /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Utils/Settings.php:31 Stack trace: #0 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Main.php(77): EditormdUtils\Settings->__construct('WP Editor.md', '10.0.6', 'editormd') #1 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Main.php(63): Editormd\Main->run_core() #2 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/wp-editormd.php(59): Editormd\Main->__construct() #3 /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/wp-editormd.php(66): EditormdRoot\run_editormd() #4 /usr/share/nginx/wordpressBlog/wp-admin/includes/plugin.php(2141): include('/usr/share/ngin...') #5 /usr/share/nginx/wordpressBlog/wp-admin/plugins.php(175): plugin_sandbox_scrape('WP-Editor/wp-ed...') #6 {main} thrown in /usr/share/nginx/wordpressBlog/wp-content/plugins/WP-Editor/src/Utils/Settings.php on line 31 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

![IT平头哥联盟，苏南的博客](https://user-images.githubusercontent.com/18324563/65309137-155a0100-dbbe-11e9-8af5-6dcd2c37e3cc.png)
php装了两个版本，要怎么处理？有没有地方指定？
