### ISSUE TITLE
引用的js里面存在一个http请求，导致chrome和firefox报错

### ISSUE THREAD

**Issue by CubeAlbert** [JaxsonWang/WP-Editor.md#363]
Mixed Content: The page at 'https://*****/wp-admin/post.php?post=137&action=edit' was loaded over HTTPS, but requested an insecure script 'http://cdn.jsdelivr.net/wp/wp-editormd/tags/10.0.5/assets/MindMap/mindMap.min.js'. This content should also be served over HTTPS.

**Comment by JaxsonWang** [comment]
请到编辑器思维导图中资源地址修改成`https`即可
