### ISSUE TITLE
Abnormal calls to syntax highlighting libraries

### ISSUE THREAD

**Issue by liwanglin12** [JaxsonWang/WP-Editor.MD#38]
![AInU.png](https://img.cdn.lwl12.com/images/2017/08/15/AInU.png)

**Comment by giuem** [comment]
Can you make a list of your environment? It works well for me.

**Comment by JaxsonWang** [comment]
你这个应该是自己CDN库？没有缓存到CDN。

或者你可以尝试用第三方的：`https://cdn.staticfile.org/prism/1.6.0/`

**Comment by liwanglin12** [comment]
@JaxsonWang 这个和CDN应该没关系吧，明显是HTML反复输出了很多次重复内容

**Comment by JaxsonWang** [comment]
@liwanglin12 你说这个，我也发现了，有时间我会优化下
