### ISSUE TITLE
行内LaTex公式无法显示

### ISSUE THREAD

**Issue by violencemofrog** [JaxsonWang/WP-Editor.md#381]
行内Tex公式只能显示原文，行间Tex公式正常

**Comment by LuRenJiasWorld** [comment]
可以给出相关的信息吗（例如截图、你的LaTeX代码等），便于复现，最新版本经测试没有发现你所说的问题。无论单行还是多行均测试通过。

相关图片：

[![](https://untitled.pw/wp-content/uploads/2019/11/QQ20191118-164458@2x-1024x530.png)](https://untitled.pw/wp-content/uploads/2019/11/QQ20191118-164458@2x-scaled.png)

[![](https://untitled.pw/wp-content/uploads/2019/11/QQ20191118-164953@2x-1024x955.png)](https://untitled.pw/wp-content/uploads/2019/11/QQ20191118-164953@2x.png)

提供一份测试代码给你，你可以粘贴进编辑器之后，截图给我看一下你这边的结果吗？

代码：[测试代码](https://untitled.pw/wp-content/uploads/2019/11/testlatex.txt "测试代码")

**Comment by violencemofrog** [comment]
WordPress版本5.3，WP-Editor.md版本10.0.7
测试代码结果：
![Snipaste_2019-11-18_19-03-59](https://user-images.githubusercontent.com/54209561/69047796-f7324500-0a36-11ea-9e7b-c43d1f1ec2d8.png)
并且行间公式不支持 \dfrac，修改后才能显示
********
Wiki中显示支持KeTex的行内公式
但使用中并不支持(之前5.2版本也不行)
如下：
![22Snipaste_2019-11-18_19-21-45](https://user-images.githubusercontent.com/54209561/69048546-b1767c00-0a38-11ea-93f7-c464dd4e86a3.png)
*********
并且更新WordPress后不仅编辑文章的面板消失了，设置也出现了问题：
![Snipaste_2019-11-18_19-08-20](https://user-images.githubusercontent.com/54209561/69048320-285f4500-0a38-11ea-9bdc-9b283da81e4c.png)
无论点到哪个设置页面，都只会显示这个页面，导致现在无法更改任何设置

**Comment by LuRenJiasWorld** [comment]
有尝试过以下两个方法吗：
1.  尝试关闭其他插件，只保留WP Editor.md插件
2. 尝试更换其他主题

**Comment by LuRenJiasWorld** [comment]
> WordPress版本5.3，WP-Editor.md版本10.0.7
> 测试代码结果：
> ![Snipaste_2019-11-18_19-03-59](https://user-images.githubusercontent.com/54209561/69047796-f7324500-0a36-11ea-9e7b-c43d1f1ec2d8.png)
> 并且行间公式不支持 \dfrac，修改后才能显示
> 
> Wiki中显示支持KeTex的行内公式
> 但使用中并不支持(之前5.2版本也不行)
> 如下：
> ![22Snipaste_2019-11-18_19-21-45](https://user-images.githubusercontent.com/54209561/69048546-b1767c00-0a38-11ea-93f7-c464dd4e86a3.png)
> 
> 并且更新WordPress后不仅编辑文章的面板消失了，设置也出现了问题：
> ![Snipaste_2019-11-18_19-08-20](https://user-images.githubusercontent.com/54209561/69048320-285f4500-0a38-11ea-9bdc-9b283da81e4c.png)
> 无论点到哪个设置页面，都只会显示这个页面，导致现在无法更改任何设置

请参考 https://github.com/JaxsonWang/WP-Editor.md/pull/383 对你的插件进行修改，新版本将于不久后发布。如果修改后还有问题，请继续反馈。
