### ISSUE TITLE
【转让维护】转让新的维护者

### ISSUE THREAD

**Issue by JaxsonWang** [JaxsonWang/WP-Editor.md#382]
由于本人近来业务繁忙，无力维护插件更新，故需要转让插件源码交于他人维护。

要求：

- 解决三个已确认的 Bug

我会抽出时间审查代码，如通过，转让项目交于维护，包括 wp 官方插件 svn 密码等相关资料。

**Comment by LuRenJiasWorld** [comment]
你好，我已使用该插件两年多，有计划接手维护。请问BUG来源是Issues吗？

**Comment by JaxsonWang** [comment]
@LuRenJiasWorld 是的

**Comment by LuRenJiasWorld** [comment]
明白了，我最近有空先解决一些问题，目前收集到的问题有五个：

- WordPress5.3兼容性（已解决） https://github.com/JaxsonWang/WP-Editor.md/issues/380
- 打开LaTeX功能之后，凡文中包含`$`符号均被解析，无论是正文还是代码块中  https://github.com/JaxsonWang/WP-Editor.md/issues/359
- MacOS下粘贴图片上传功能无效（已提交PR等待Merge） https://github.com/JaxsonWang/WP-Editor.md/issues/377
- 上传图片到图床功能不稳定，经常出现问题 https://github.com/JaxsonWang/WP-Editor.md/issues/377
- 代码段转义问题 https://github.com/JaxsonWang/WP-Editor.md/issues/356

接下来的一个月时间里，我会尝试逐一解决以上问题，如果出现突发BUG我会优先解决，发现更多问题也会尝试逐一解决。

如果遇到不方便在Issue里沟通的情况，欢迎通过邮件联系我，我的邮箱地址是loli@lurenjia.in。
