### ISSUE TITLE
Temporarily switch back to TinyMCE's source file functionality

### ISSUE THREAD

**Issue by liwanglin12** [JaxsonWang/WP-Editor.MD#39]
提供按钮可以切换回WP原生编辑器的源代码功能方便进行不想被MD解析的操作

**Comment by JaxsonWang** [comment]
可以，尝试实现这个需求

**Comment by liwanglin12** [comment]
（道理上既然要处理这个issue的话不应该打一个enchantment的Label然后等做完了Commit的时候提交信息来一个 #39 Close 么）
