### ISSUE TITLE
插入代码块，页面展示不换行

### ISSUE THREAD

**Issue by JanWarlen** [JaxsonWang/WP-Editor.MD#4]
在markdown的预览里是正常的，但是发布到页面就挤一块了

**Comment by JaxsonWang** [comment]
好的，有空排查下 
------------------ Original ------------------

**Comment by JanWarlen** [comment]
我的猜测应该很有可能是和别的主题的冲突了，正在排查看看，会尽快给你反馈

**Comment by JanWarlen** [comment]
基本确定和主题冲突了，更换主题之后虽然不是markdown的预览效果，但不至于没换行了
