### ISSUE TITLE
流程图的语法问题

### ISSUE THREAD

**Issue by linroylin** [JaxsonWang/WP-Editor.MD#45]
以下语法连续写两遍画两个流程图就出问题，一遍就正常
$flow
st=>start: User login
op=>operation: lperation
cond=>condition: Successful Yes or No?
e=>end: Into admin
st->op->cond
cond(yes)->e
cond(no)->op
$

**Comment by JaxsonWang** [comment]
[Fixed](https://github.com/JaxsonWang/WP-Editor.MD/commit/23565b8794339e00b190d0786c3e8b99debd6389)
