### ISSUE TITLE
编辑页面无法载入插件

### ISSUE THREAD

**Issue by cs-suncc** [JaxsonWang/WP-Editor.MD#6]
Uncaught ReferenceError: editormd is not defined
    at HTMLDocument.<anonymous> (post-new.php:756)
    at i (load-scripts.php:2)
    at Object.fireWith [as resolveWith] (load-scripts.php:2)
    at Function.ready (load-scripts.php:2)
    at HTMLDocument.K (load-scripts.php:2)

```php
...
//Emoji表情自定义服务器地址
editormd.emoji     = {
   path  : 'https:' === document.location.protocol ? "https://staticfile.qnssl.com/emoji-cheat-sheet/1.0.0/" : 
  "http://cdn.staticfile.org/emoji-cheat-sheet/1.0.0/",
    ext   : ".png"
};
...
```

**Comment by JaxsonWang** [comment]
请确保不是个例问题，我这儿不存在此问题！

**Comment by TechCiel** [comment]
说具体点就是：
换默认主题、关其他插件、重装WP、重装浏览器、换台电脑试试🌚

**Comment by cs-suncc** [comment]
不清楚情况，前几天还很正常，今天更新4.7.4以后就这样了。并不写做前端所以错误也看不懂，似乎是editormd.min.js还是ace.js里产生的异常
（插件就装了个EWWW 和 Akismet，实在没有头绪我还是回去用JP Markdown好了
除了编辑器的部分似乎都没有问题，还是能正常转换md和html
ace.js?ver=0.3.7:1 console.trace
t @ ace.js?ver=0.3.7:1
(anonymous) @ editormd.min.js?ver=1.5:formatted:7
(anonymous) @ editormd.min.js?ver=1.5:formatted:12
```js
;(function(factory) {
    "use strict";
    if (typeof require === "function" && typeof exports === "object" && typeof module === "object") {
        module.exports = factory
    } else if (typeof define === "function") {
        if (define.amd) {} else {
            define(["jquery"], factory) // <= LINE 7 HERE
        }
    } else {
        window.editormd = factory()
    }
}(function() {
```

**Comment by JaxsonWang** [comment]
WordPress 4.7.4不存在这个问题

而且ace.js不是此插件的依赖文件...
