### ISSUE TITLE
I can't use this plugin

### ISSUE THREAD

**Issue by poke3** [JaxsonWang/WP-Editor.MD#67]
WordPress version: 4.8.1
Plugin version: 3.0

I had activated WP Editor.md.

![default](https://user-images.githubusercontent.com/30792424/29769807-7f47fc76-8c1e-11e7-80b1-8f1785ba03d2.png)

But when I add a post，it's a regular editor.

![default](https://user-images.githubusercontent.com/30792424/29769854-b69c1d38-8c1e-11e7-9dea-53ae61e91aca.png)

**Comment by JaxsonWang** [comment]
@poke3开启debug看看

**Comment by poke3** [comment]
@JaxsonWang 开户 debug 没有任何报错，不过找到原因了，因为用的是多站点，插件不能在网络中激活，而只能在单独站点中开启。
