### ISSUE TITLE
能否改的更接近标准markdown一点

### ISSUE THREAD

**Issue by cww97** [JaxsonWang/WP-Editor.MD#70]
```c++
//codes
```
这样的代码块匹配不上
```
//codes
```
还有
```

//comments
```

会变成

<br>//comments

**Comment by cww97** [comment]
突然发现github评论是markdown，智障了,本来数字1左边的那个符号点点点三下是代码块的高亮标识，如果，在三个点后面加上c++之类，就好智障

**Comment by JaxsonWang** [comment]
你说的这样有问题？

所有的语法都在这儿：http://prismjs.com/download.html

**Comment by JaxsonWang** [comment]
![qq 20170905192607](https://user-images.githubusercontent.com/16836692/30059058-1ab0f0a8-9270-11e7-89e2-70d909bf7bb4.png)
![qq 20170905192615](https://user-images.githubusercontent.com/16836692/30059059-1aba12fa-9270-11e7-8b0c-e89b2928c1d2.png)

主要是标识语法类型有特殊符号如 c++的++ c#的# 会导致语法高亮失效...
