### ISSUE TITLE
插件能否支持多站点

### ISSUE THREAD

**Issue by poke3** [JaxsonWang/WP-Editor.MD#74]
WordPress version: 4.8.1
Plugin version: 3.1

插件在子站点中单独启用时，进入设置页点【保存设置】就提示`抱歉，您不能访问此页面。`。

后面试着从整个网络启用，但又发现一个问题，进入子站设置页点【保存设置】自动跳转到网络中。也就是说不能在子站中开启功能，比如想开启支持粘贴图片。

**Comment by JaxsonWang** [comment]
你这个我这儿没有更好的解决方案，除非我重写选项页，有这个计划，但最近没有时间。

有个临时方案，请自行修改这段的代码：[https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Admin/skelet/core/core.php#L368-L376](https://github.com/JaxsonWang/WP-Editor.MD/blob/master/Admin/skelet/core/core.php#L368-L376)
