### ISSUE TITLE
表情功能不能使用

### ISSUE THREAD

**Issue by winsonet** [JaxsonWang/WP-Editor.MD#77]
你好，我在使用Emoji表情的時候出現以下錯誤：

```
Uncaught TypeError: Cannot read property 'title' of undefined
    at init.exports.fn.emojiDialog (emoji-dialog.js:115)
    at editormd.min.js?ver=3.2:1
    at editormd.min.js?ver=3.2:1
    at HTMLScriptElement.script.onload (editormd.min.js?ver=3.2:1)
```

請問是什麼問題呢？

**Comment by JaxsonWang** [comment]
具体是怎么使用的

**Comment by winsonet** [comment]
哦，我發現如果我直接在頁面打上表情如 :)  這個是可以的，但當我點擊表情按鈕的時候，就出現以上JS錯誤了，我是在console裏看到這些錯誤的，頁面上是沒有任何提示的，就是點了沒反應

**Comment by winsonet** [comment]
還有，其實我點擊添加表格的時候也有問題，出現以下錯誤：

```
Uncaught TypeError: Cannot read property 'cellsLabel' of undefined
    at init.exports.fn.tableDialog (table-dialog.js:84)
    at editormd.min.js?ver=3.2:1
    at editormd.min.js?ver=3.2:1
    at HTMLScriptElement.script.onload (editormd.min.js?ver=3.2:1)
```
也是沒有東西彈出來

**Comment by JaxsonWang** [comment]
目前wp仓库版本没问题V3.3的。

这样，请你把除了编辑器插件停用再看看是否管用，个人觉得可能插件受到影响了

**Comment by winsonet** [comment]
哦，其實我是新裝的WP，所以只裝了你的這個插件還有Table of Contents Plus，其他都沒裝了，我是直接在WP後臺添加安裝的插件，不知是否最新版的了

**Comment by winsonet** [comment]
原來最新版是3.3？ 我發現直接在WP裏裝的版本是3.2哦，以下是我使用的截圖。除了表格、表情還有那個go to line按鈕有問題，其他都沒問題的：

![image](https://user-images.githubusercontent.com/1869995/30519380-b42d0e8c-9bc7-11e7-9864-8fa0fc9341a4.png)

另，你這個插件真的是非常COOL哦，謝謝啦！！

**Comment by JaxsonWang** [comment]
确定WP是最新版吗？

还有主题是默认官方的版本？

你设备是Mac？浏览器是什么以及版本号

**Comment by winsonet** [comment]
1. 我直接WP安裝的版本是3.2的，是否需要我手工下載最新版安裝？
2. 是官方默認主題，因為新裝的所以什麼都沒有改過
3. 我用的是MAC，瀏覽器是Chrome 版本 60.0.3112.101（正式版本） （64 位）

**Comment by JaxsonWang** [comment]
WordPress最好用最新版，你先试试最新版怎么样

**Comment by winsonet** [comment]
OH，sorry，我看錯了，我剛才以為你問我插件的版本，WP用的是最新版的，剛在官方下載的，你的插件版本是3.2，好吧，我看看直接在這裏下載你最新版本試試吧
