### ISSUE TITLE
A button about generating titles' directory 

### ISSUE THREAD

**Issue by xkungfu** [JaxsonWang/WP-Editor.MD#79]
make a button about TOC feature and insert it on editor buttons' panel.
after clicking this button, the directory of all titles displayed on a popup.
Then, the author can select some titles to generating directory of the article.
thanks.

**Comment by xkungfu** [comment]
additional:
another solution maybe more accord with markdown style.
after clicking button, a directory of all titles be instered to top of the article .
and author can manual edit the directory. delete some unuseful titles.

**Comment by JaxsonWang** [comment]
[https://github.com/JaxsonWang/WP-Editor.MD/commit/4e53c588e6e28b3acfc0947491f328e18251340b](https://github.com/JaxsonWang/WP-Editor.MD/commit/4e53c588e6e28b3acfc0947491f328e18251340b)

**Comment by xkungfu** [comment]
Good. the button works,
