### ISSUE TITLE
請問能否resize圖片？

### ISSUE THREAD

**Issue by winsonet** [JaxsonWang/WP-Editor.MD#81]
如我想設置圖片的高度和寬度，可以做到嗎？否則每次都顯示原圖好大，其實我想在頁面讓用戶點擊圖片再彈出lightbox放大觀看

嘗試了一般的markdown resize image的語法，但都沒效果 :(

**Comment by JaxsonWang** [comment]
原生的Markdown并不支持。

不过你可以从wp的多媒体库选择图片大小

**Comment by winsonet** [comment]
哦，好的，謝謝啦！

**Comment by winsonet** [comment]
我之後找到了解決辦法，但只能hardcode上圖片size，不過對我來說是可以了，就是直接修改Jetpack lib的文件：
Jetpack/lib/markdown/extra.php   line 2449，添加上img的相關屬性：

```
$result = "<a href=\"$url\"><img width=600 class='alignnone size-medium wp-image-9'  src=\"$url\" alt=\"$alt_text\"";
		if (isset($title)) {
			$title = $this->encodeAttribute($title);
			$result .=  " title=\"$title\""; # $title already quoted
		}
		$result .= $attr;
		$result .= $this->empty_element_suffix;
		$result .= "</a>"; //for <a>
```
這樣就可以使用lightbox功能了，當然如果你可以更完善地讓參數傳遞進來那就更好了！

**Comment by JaxsonWang** [comment]
好，感谢提供代码，当然欢迎PR。谢谢~

**Comment by wuchlei** [comment]
跪求大佬加上image resize

**Comment by wuchlei** [comment]
以及img的属性需要这样修改
`$result = "<a href=\"$url\"><img style=\"height:200px;\" class='aligncenter'  src=\"$url\" alt=\"$alt_text\"";`
否则会被stylesheet override
<https://blog.wuchlei.xyz/hard-coded-image-resizing-in-wp-editor-md/>
