### ISSUE TITLE
锚点转换有问题

### ISSUE THREAD

**Issue by 52fisher** [JaxsonWang/WP-Editor.MD#84]
使用`<a href="#id">demo</a>`
或者`[demo](#id)`
在编辑器转换之后，前台被转换为`<a href="http://#id">demo</a>`
导致锚点失效.

**Comment by JaxsonWang** [comment]
[Fix](https://github.com/JaxsonWang/WP-Editor.MD/commit/ef1f1f8815f58b7cbba291792cfaed8180510179)

[Fix](https://github.com/JaxsonWang/WP-Editor.MD/commit/e1779253012d02e78b9e62885b5c6957db06cc67)
