### ISSUE TITLE
启用此插件自带的“支持Emoji表情”功能后，小影志的Minty主题报错

### ISSUE THREAD

**Issue by mokeyjay** [JaxsonWang/WP-Editor.MD#86]
JS控制台报错：_wpemojiSettings is not defined
据小影说Minty主题用到了WP自带的Emoji功能。是否说明此插件自带的Emoji跟WP自带的相互冲突呢？

**Comment by JaxsonWang** [comment]
这个插件选项有个emoji表情，该功能的确会禁用wp自带的emoji表情，如果你想用自带的表情，请禁用插件的该选项。
