### ISSUE TITLE
单行代码中的左右尖括号不正常

### ISSUE THREAD

**Issue by yuzenan888** [JaxsonWang/WP-Editor.MD#87]
输入:
```
`>`
```
会变成:
```
&gt
```
然后成对的尖括号：
```
`<aaa>`
```
完全无法显示。

**Comment by JaxsonWang** [comment]
Fix https://github.com/JaxsonWang/WP-Editor.MD/commit/d3173e9a0be6efcff5c35f47b08810f1f5c3a8cc
