### ISSUE TITLE
How to call markdown editor on frontend ？

### ISSUE THREAD

**Issue by xkungfu** [JaxsonWang/WP-Editor.MD#88]
Example of wordpress official editor and call function ：

`wp_editor(  wpautop($post_content), 'post_content', array('media_buttons'=>true, 'quicktags'=>true, 'editor_class'=>'form-control', 'editor_css'=>'<style>.wp-editor-container{border:1px solid #ddd;}.switch-html, .switch-tmce{height:25px !important}</style>',  'textarea_rows'=>5 ) ); `

Can WP-Editor.MD be called on front end of Wordpress like this way?

**Comment by JaxsonWang** [comment]
找到前端评论框的ID替换这一行就行了https://github.com/JaxsonWang/WP-Editor.MD/blob/master/editormd_class.php#L62

建议单独写个吧
