### ISSUE TITLE
能否添加判断，在手机上使用时自动关闭实时预览？

### ISSUE THREAD

**Issue by NorthNanmu** [JaxsonWang/WP-Editor.MD#89]
RT
在手机上使用会导致屏幕写作空间极其狭小
关掉后在电脑上使用又要重新开启一遍

**Comment by JaxsonWang** [comment]
https://github.com/JaxsonWang/WP-Editor.MD/commit/37a588c87dd76e5a987a6b71a9fc2f4ec9ca4cec
