### ISSUE TITLE
更换语法高亮库为Prism后插件主页说明未修改

### ISSUE THREAD

**Issue by kewell-tsao** [JaxsonWang/WP-Editor.MD#9]
https://wordpress.org/plugins/wp-editormd/

> 语法高亮库
> 不填为空则默认主题，请在highlightjs。请在左边下侧选择自己喜欢的主题，引入主题资源地址即可。不过建议选择CDN静态资源文件。

**Comment by JaxsonWang** [comment]
呃...好的，我改。
