### ISSUE TITLE
视频类插件冲突

### ISSUE THREAD

**Issue by NorthNanmu** [JaxsonWang/WP-Editor.MD#90]
部分插件依赖于在编辑器中自动识别视频网站链接来转换标签，如：Smartideo、WP Youku等，
而WP-Editor.MD实际上在这些插件起作用之前将连接转换为了<a>标签，导致这类插件直接失效
WP-Editor.MD有计划增加视频插入功能吗？或者是增加链接判断，将这些视频类链接不做<a>标签转换？

**Comment by JaxsonWang** [comment]
我不理解，看了这几个插件不就是插入超链接么？编辑器又不会去改变它

**Comment by NorthNanmu** [comment]
这类视频插件会将视频网站的链接自动更改为嵌入式视频播放器，而WP-Editor.MD在这些插件识别之前已经提前将这类视频网站链接加上了<a>标签，于是这类插件的识别就失效了

**Comment by JaxsonWang** [comment]
可以提供插件名字吗？我想自己去测试下，谢谢！
