### ISSUE TITLE
语法高亮中注释显示异常

### ISSUE THREAD

**Issue by mightbxg** [JaxsonWang/WP-Editor.MD#91]
多行代码中只要出现注释，被注释的文字下面就会出现一个大白框，非常影响美观，而且会遮挡其它行的代码。cpp中```//```和bash中```#```都会被识别为注释，但bash中的```#```有时候其实并不是注释（比如```FILEPATH=${1#*file://}```）
![截图](http://ov1kvsbhe.bkt.clouddn.com/20171013164247.png "截图")

**Comment by JaxsonWang** [comment]
个例问题，建议切换别的主题看看。可能是你的主题样式干扰到高亮了~

**Comment by mightbxg** [comment]
看来确实跟主题有关系
