### ISSUE TITLE
与插件 All in One SEO Pack 存在兼容问题

### ISSUE THREAD

**Issue by netAir** [JaxsonWang/WP-Editor.MD#92]
启用All in One SEO Pack时,markdown编辑器将无法显示,只有默认的文本框

**Comment by JaxsonWang** [comment]
我安装该插件，没有出现你说的情况...是不是有其他插件或者是你的主题某些函数导致的

**Comment by netAir** [comment]
我又测试了一下,您的编辑器与插件中的`社交Meta`功能存在兼容问题.
在功能管理中开启此功能将导致编辑器无法显示.

**Comment by autocar23** [comment]
同样的问题，看了这个issus把社交Meta关闭了就好了，Thank you
