### ISSUE TITLE
表格加载问题

### ISSUE THREAD

**Issue by songzuotao** [JaxsonWang/WP-Editor.MD#95]
表格在实时预览是OK的，但是发布后页面显示表格格式就没有了。
使用这种格式：
|   |   |
| ------------ | ------------ |
|   |   |
|   |   |

**Comment by JaxsonWang** [comment]
具体请看：https://raw.githubusercontent.com/JaxsonWang/WP-Editor.MD/master/Document/markdown.md
相关语法
