### ISSUE TITLE
希望能增加内联代码功能

### ISSUE THREAD

**Issue by H-adorable** [JaxsonWang/WP-Editor.MD#97]
有些时候不需要断行写那么多代码，只需要在一行中插入一句。希望能支持这样的功能。
比如这样子``` cout << "hello world!" << endl ```
文字底部略有阴影就好

**Comment by JaxsonWang** [comment]
这不就是\`代码\`么？

**Comment by H-adorable** [comment]
那应该是 theme 对内联的代码没有支持。
网页源码里看到 内联的代码块 被<code> 标签包裹住了，但是没有特效显示

**Comment by JaxsonWang** [comment]
您的主题没有该样式，请参考[这个issues](https://github.com/JaxsonWang/WP-Editor.MD/issues/36)
