### ISSUE TITLE
bug 数字列表在网页无法正常显示

### ISSUE THREAD

**Issue by H-adorable** [JaxsonWang/WP-Editor.MD#98]
在编辑器中可以正常看到
1. 11111
```
kkk
```
2. 2222
```
iii
```

但是，在网页中，所有的序号都编程了1.

**Comment by JaxsonWang** [comment]
请看表格相关文档：https://raw.githubusercontent.com/JaxsonWang/WP-Editor.MD/master/Document/markdown.md

其实编辑器对markdown语法很严格，你看到的编辑器那个偏松点。
