### ISSUE TITLE
安装jetpack的情况下，无法正常打开新建文章页面

### ISSUE THREAD

**Issue by H-adorable** [JaxsonWang/WP-Editor.MD#99]
已经关闭了 Jetpack 的markdown功能。
安装本插件，启用，点击新建文章，无法开启页面。
浏览器提示，Erro 500

**Comment by H-adorable** [comment]
尝试先关闭`Jetpack` 和`WP-Editor.MD`。然后启动 `WP-Editor.MD`，再启动`Jetpack`。
此时，新建文章页面可以访问，编辑器可以正常使用。

**Comment by JaxsonWang** [comment]
收到，下个版本修复
